/**
 * Short lines for the Focus screen, written for Tars. They are not quotations
 * and carry no attribution: nothing here is a real person's words. House style
 * applies (sentence case, no exclamation marks, curly apostrophes), and each
 * line is short enough to read in a glance between two thoughts.
 *
 * The file is loaded on demand (see wallpaper/useAmbience.ts), so the 500-odd
 * lines never weigh on start-up. quotes.test.ts keeps them unique and short.
 */

const FOCUS = [
  'One page, fully read, beats ten pages skimmed.',
  'Attention is the only thing you really spend.',
  'Close the other tabs in your head.',
  'Stay with the paragraph until it gives way.',
  'The work is in front of you. That is enough direction.',
  'Do this one thing as if nothing else were waiting.',
  'A narrow beam lights more than a wide glow.',
  'What you attend to is what you become good at.',
  'Give the next twenty minutes a single job.',
  'Depth is just staying a little longer than is comfortable.',
  'Your mind wanders. Walk it back, kindly, and continue.',
  'The question in front of you deserves all of you.',
  'Noise is everywhere. So is the choice to ignore it.',
  'Focus is not force. It is returning, again and again.',
  'Let the phone be bored for a while.',
  'A quiet desk is a small act of respect for the work.',
  'One clear hour is worth a scattered afternoon.',
  'You do not need more time. You need this time, whole.',
  'Read slowly enough to disagree with the book.',
  'Hold one idea until you can turn it over in your hands.',
  'Nothing urgent lives in the next notification.',
  'Be where your pen is.',
  'The mind settles like water when you stop stirring it.',
  'Finish the thought before you open the next one.',
  'Every distraction is a trade. Check the price.',
  'This session is a room. Shut the door.',
  'Single-tasking is a quiet kind of power.',
  'Stay in the chair. The clarity comes to those who wait there.',
  'You can do anything for twenty-five minutes.',
  'Let this hour be about less, done properly.',
  'A full mind learns nothing. Empty it of everything but the page.',
  'The easiest way to go deep is to stop going wide.',
  'Protect the first minutes. They decide the rest.',
  'Attention grows where you keep placing it.',
  'Look at the problem until it starts looking back.',
  'There is nothing to check. There is only this.',
  'Your best thinking needs your whole afternoon’s patience in one sitting.',
  'Let the outside world keep its own time for now.',
  'When you notice you have drifted, that is the practice working.',
  'A sharp hour cuts further than a dull day.',
  'Sit with what is difficult. It gets shorter.',
  'Work on what is in your hands, not what is in your feed.',
  'The timer is running. Everything else can wait its turn.',
  'Think of one sentence at a time.',
  'Stillness first, then speed.',
  'You are allowed to be unreachable for an hour.',
  'Clarity is attention that stayed.',
  'Turn down the world a little and listen to the page.',
  'Do the reading the way you would listen to a friend.',
  'One window. One book. One line at a time.',
  'The page will hold you if you let it.',
  'Small circle of light, large amount of progress.',
  'Let the hard paragraph take as long as it takes.',
  'Where your eyes rest, your mind follows. Choose the resting place.',
  'A calm mind reads twice as fast and forgets half as much.',
  'Be greedy with your attention and generous with your effort.',
  'This is the only task that exists until the bell.',
  'The urge to check will pass in about ninety seconds.',
  'Follow the argument all the way to its end.',
  'You are not behind. You are here. Begin.',
  'Hold the line of thought like a thread through a needle.',
  'Good focus feels ordinary while it is happening.',
  'Give the chapter the dignity of your full attention.',
  'The mind likes one thing at a time. Indulge it.',
  'Rest your eyes on the work and your thoughts will arrive.',
  'Less switching, more finishing.',
  'A session is a promise small enough to keep.',
  'Ignore the clock and it becomes generous.',
  'Go slowly enough to notice what you do not understand.',
  'The interesting part is always one layer further down.',
  'Stay curious about the sentence you are on.',
  'What is the single next line? Write that.',
  'Half attention gives quarter results.',
  'Concentration is a muscle, and this is the gym.',
  'Leave the door closed a little longer.',
  'If it matters, it can wait until the break.',
  'An undivided hour is a rare gift. Give it to yourself.',
  'You sharpen the mind by using it on one edge.',
  'Keep the thread. Lose the rest.',
  'This is quiet work. Let it be quiet.',
  'A good session leaves you a little tired and a little proud.',
  'The work asks for presence, not perfection.',
  'Even ten deep minutes change the shape of a day.',
  'Read the question again. It usually answers a part of itself.',
  'Let your attention be a lamp, not a lighthouse.',
  'Sink into it. The surface is where the noise lives.',
  'Nothing is as productive as not interrupting yourself.',
  'Draw a line around this hour and stay inside it.',
  'Be loyal to the task you chose.',
  'The fastest route through a chapter is straight through it.',
]

const DISCIPLINE = [
  'Show up before you feel ready.',
  'Motivation visits. Routine lives here.',
  'Do it tired, do it small, but do it.',
  'The plan only works on the days you follow it.',
  'Keep the promise you made to yourself this morning.',
  'Consistency is talent with the lights off.',
  'A dull day done is still a day done.',
  'Sit down at the same hour and the work learns to meet you.',
  'You do not have to feel like it. You only have to start.',
  'Discipline is remembering what you want most.',
  'Small rules, kept daily, move mountains quietly.',
  'Decide once, then stop negotiating.',
  'The streak is built on unremarkable days.',
  'Start on time. The rest follows.',
  'Let your schedule be the adult in the room.',
  'An ordinary effort repeated is an extraordinary result.',
  'Do today’s share. Tomorrow will bring its own.',
  'What you repeat unobserved is what you can rely on.',
  'The syllabus does not shrink while you wait.',
  'One more session is always smaller than it looks.',
  'Guard your study hours like appointments with someone important.',
  'Effort is a habit before it is a virtue.',
  'Begin badly if you must, but begin on schedule.',
  'There is freedom in not having to decide again.',
  'Honour the timetable and the timetable will honour you.',
  'It counts most on the days it is hardest to count.',
  'A missed day is a lesson. Two is a pattern. Come back today.',
  'Lay one brick well, then another.',
  'Skip the excuse and the session is half done.',
  'Your future self is built out of today’s hours.',
  'Standards are kept in private.',
  'Make the right thing the easy thing, then do it daily.',
  'Finish what you scheduled before you reward yourself.',
  'Work first. Feelings will catch up.',
  'The desk is not asking for inspiration, only attendance.',
  'Routine is a kindness to the tired version of you.',
  'Hard choices now, easier choices later.',
  'Rest when it is time to rest. Work when it is time to work.',
  'Nothing compounds like a habit left unbroken.',
  'Wake up, sit down, open the book. Three steps.',
  'Be stubborn about your mornings.',
  'A calendar kept is a quiet form of courage.',
  'The dull middle is where the result is made.',
  'Arrive at the desk like you arrive at work: without a debate.',
  'Let the timer carry what your willpower cannot.',
  'Whatever you practise, you keep. Practise the right thing.',
  'Rules you set calmly protect you when you are not calm.',
  'Do the page you planned, not the page you fancy.',
  'Count sessions, not moods.',
  'Self-control is easier at the start of an urge than at its end.',
  'The work you avoid grows. The work you face shrinks.',
  'Stay on plan for one more block.',
  'Your word to yourself is worth keeping.',
  'There is no trick. There is the chair and the hours.',
  'A good day is a kept schedule, not a perfect one.',
  'Earn your evening.',
  'Tidy desk, set timer, first line. Repeat.',
  'Protect the routine and the routine protects the goal.',
  'Do not wait for a better mood. Build one by working.',
  'Reliable beats brilliant over a long syllabus.',
  'Each session quietly settles who you are.',
  'The daily hour outweighs the occasional heroic day.',
  'Start the clock. The hesitation ends there.',
  'Order in the morning, ease in the evening.',
  'Refuse the small delay and you refuse the large one.',
  'Sit through the restless minute. The steady hour is behind it.',
  'Do the revision you scheduled when you were wiser.',
  'A habit is a decision you no longer have to make.',
  'The bell rings for everyone. Be working when it does.',
  'Push the start time earlier, not the finish later.',
  'Quiet diligence outlasts loud ambition.',
  'You will not always want to. Do it as a favour to tomorrow.',
  'Trust the process you chose on a clear day.',
  'Being regular is a form of being brave.',
  'It is only one block. Then decide about the next.',
  'Commit to the hour, not the outcome.',
  'Self-respect is built in sessions.',
  'The same desk, the same time, the same intention.',
  'Hold the standard gently, but hold it.',
  'Let effort be automatic and attention deliberate.',
  'Put the hours in the bank. They earn interest.',
  'Keep going at the pace you can keep.',
  'A firm routine makes a soft landing on hard days.',
  'First the task, then the tea.',
  'You promised an hour. Give sixty minutes.',
  'Tired is a feeling. The schedule is a fact.',
  'Lean on the plan when the will is thin.',
  'A streak is easiest to keep on the day you nearly broke it.',
  'Every kept session makes the next one lighter.',
  'The work is the reward’s older sibling.',
]

const LEARNING = [
  'Understanding is slower than memory and lasts longer.',
  'Explain it to a beginner. Where you stumble is where to study.',
  'Ask why until the answer stops surprising you.',
  'Mistakes are the syllabus teaching you personally.',
  'Recall it with the book closed. That is the real test.',
  'A map learned by drawing stays drawn.',
  'Read to understand, revise to remember.',
  'Confusion is the feeling of a mind stretching.',
  'Every expert was once puzzled by this exact page.',
  'Write it in your own words or you have only borrowed it.',
  'Connect the new fact to an old one and it will stay.',
  'Learning is mostly re-learning, a little faster each time.',
  'Questions are better teachers than answers.',
  'What you revise today, you keep in three months.',
  'Test yourself before the exam does.',
  'A wrong answer examined is worth two right ones forgotten.',
  'Knowledge compounds. Start the account early.',
  'Do not collect notes. Collect understanding.',
  'The second reading is where the book opens up.',
  'Teach the wall. If the wall would follow, you have it.',
  'Details stick to a clear outline.',
  'Curiosity makes the hours shorter.',
  'Go slowly until it is smooth, and speed arrives on its own.',
  'Learn the map and the news starts to make sense.',
  'Old questions are the examiner thinking out loud.',
  'Forgetting is part of learning. Returning is the other part.',
  'One concept understood unlocks ten facts.',
  'Underline less. Think more.',
  'Draw the diagram until you no longer need it.',
  'Your notes should be shorter than the chapter and smarter than a list.',
  'The mind keeps what it has struggled for.',
  'Leave the easy topic. Go where your marks are leaking.',
  'Review yesterday before you start today.',
  'An honest mock is worth a week of comfortable reading.',
  'Learn the rivers and you learn the country.',
  'Read the original line, then ask what it changes.',
  'If it will not fit on one page, you have not finished thinking.',
  'A good question is half a good answer.',
  'Revise in layers: outline, then detail, then exceptions.',
  'Memory loves a story. Give the fact one.',
  'On exam day you bring your revision, not your hopes.',
  'Let each mistake visit only once.',
  'First principles first. Shortcuts later.',
  'What can you say about this without looking?',
  'Clarity comes from writing, not from re-reading.',
  'Space your revision and time will do part of the work.',
  'The weak chapter is waiting patiently. Go and meet it.',
  'Learn it today so that tomorrow you only have to remember it.',
  'A fact with a place on the map is hard to lose.',
  'Do not fear the long answer. Build it one point at a time.',
  'Being stuck is information. Find out what it is telling you.',
  'Read the question the examiner wrote, not the one you prepared for.',
  'Small, frequent recall beats one long cram.',
  'To know the present, read the past patiently.',
  'Simplify until a beginner could follow, then you are ready.',
  'Each revision is a little faster and a little deeper.',
  'Keep a list of what fooled you. Read it weekly.',
  'Good notes are a conversation with your later self.',
  'Understanding one cause explains a dozen events.',
  'The index of the book is a syllabus in disguise.',
  'Learn the exceptions last. Learn the rule well.',
  'Ask what would change if this fact were different.',
  'Depth in a few sources beats a glance at many.',
  'Put the answer into a structure before you put it into words.',
  'A place, a date, a reason. Hang the fact on all three.',
  'You remember what you use. Use it today.',
  'Let the atlas stay open beside the textbook.',
  'Reading is collecting. Recalling is owning.',
  'Every topic was hard before it was familiar.',
  'Check the answer, then check why the others were wrong.',
  'Brief notes, long thinking.',
  'A timeline turns a pile of dates into a story.',
  'If two things confuse you, study their difference.',
  'Learn the shape of the subject before its texture.',
  'What you cannot recall, you have only met.',
  'The best summary is the one you wrote from memory.',
  'Bring a question to every page.',
  'Linking chapters is where understanding becomes an answer.',
  'An example makes a definition breathe.',
  'Go back to the basics when the advanced feels heavy.',
  'Familiar is not the same as known. Test the difference.',
  'Let the news send you back to the textbook.',
  'One mapped place a day fills an atlas in a year.',
  'Old notes are a ladder. Climb them, do not rewrite them.',
  'Read the conclusion first, then earn it.',
  'Ask the chapter what it is trying to prove.',
  'The answer you can sketch is the answer you can write.',
  'Curiosity is revision that does not feel like revision.',
  'A fact learned in context is learned once.',
  'Slow down at the part you would like to skip.',
]

const CALM = [
  'Breathe out longer than you breathe in.',
  'Nothing needs to be solved in this breath.',
  'You have time for the next step.',
  'Quiet is not empty. It is full of room.',
  'Unclench your jaw. Drop your shoulders. Continue.',
  'A calm start is a fast start.',
  'Worry is practising a problem you may never get.',
  'Let the thought pass like weather.',
  'You are doing enough for this hour.',
  'Slow your hands and your mind will follow.',
  'Peace is a way of working, not a reward for finishing.',
  'The exam is one day. Today is another. Be in this one.',
  'Rest is part of the plan, not a break from it.',
  'Let the rain do the hurrying.',
  'Lower the volume of your expectations and raise your attention.',
  'It is all right to go gently and still go far.',
  'One breath, one line.',
  'Stillness is where the answer has room to arrive.',
  'You do not have to carry the whole syllabus tonight.',
  'A soft mind bends around hard problems.',
  'Calm is a skill. Each session is a rehearsal.',
  'Put the weight down between repetitions.',
  'The night is long enough. There is no need to rush it.',
  'Pressure makes diamonds only of what stays steady.',
  'Make tea. Sit down. Start small.',
  'Your pace is allowed to be yours.',
  'What is here now? A desk, a page, a breath.',
  'Be patient with the slow parts of yourself.',
  'Anxiety says later. The page says now.',
  'A settled mind remembers more.',
  'Leave the result where it belongs: after the work.',
  'There is a quiet under the noise. Work from there.',
  'Unhurried does not mean unproductive.',
  'Let the hour be as wide as it is.',
  'The lamp is on. The room is warm. Begin.',
  'A steady breath is the oldest study aid.',
  'You can be serious without being tense.',
  'Tomorrow can look after itself for forty minutes.',
  'Thoughts drift across like clouds. Let them go by.',
  'The body sits. The mind arrives a moment later. Wait for it.',
  'Ease into it like cold water: one step, then another.',
  'Nothing is being asked of you but this page.',
  'A gentle effort, held for long, goes deep.',
  'Notice the window. Notice the light. Return.',
  'If the mind is loud, write the noise down and set it aside.',
  'You are safe to concentrate.',
  'Evening settles. Let your thoughts settle with it.',
  'Trust that a clear head is worth the pause.',
  'Do less at once and more in total.',
  'Soft focus, firm intention.',
  'The break is coming. You can rest then.',
  'Let silence be the background music.',
  'Hurry is a thief of understanding.',
  'There is no race in this room.',
  'Feel your feet on the floor and read the next line.',
  'A calm hour repairs a frantic day.',
  'Hold your goals loosely and your routine firmly.',
  'Let go of the last session. This one is new.',
  'You are allowed to enjoy the quiet.',
  'Even the sea rests between waves.',
  'The mind clears when the hands slow down.',
  'This moment asks for very little. Give it that.',
  'Be the still point in a noisy week.',
  'Kindness to yourself is not the opposite of rigour.',
  'Warm light, slow breath, one clear task.',
  'Let the city hum without you for a while.',
  'Where there is no hurry, there are fewer mistakes.',
  'Pause at the full stop. Then go on.',
  'Carry today only.',
  'A walk in the break solves what the chair could not.',
  'Enough is a good place to work from.',
  'Listen to the rain and let the reading find its rhythm.',
  'The deep breath is free and always available.',
  'Sit comfortably. You will be here a while, and that is fine.',
  'Mountains are patient. So is good preparation.',
  'When it feels like too much, do the next small thing.',
  'A peaceful mind is the sharpest tool on the desk.',
  'You have survived every hard chapter so far.',
  'Close your eyes for ten seconds. Open them on the same line.',
  'Still water shows the bottom.',
]

const PERSEVERANCE = [
  'Keep going. The hill is shorter from the other side.',
  'Progress is quiet most of the time.',
  'Fall behind, then catch up. That is the whole story.',
  'The long road is walked in ordinary steps.',
  'You are closer than the tired part of you believes.',
  'Not yet is a different sentence from never.',
  'One more attempt is how every result began.',
  'Rivers reach the sea by not stopping.',
  'The bad session still counted.',
  'Stay in the game long enough to get good.',
  'Slow progress is progress wearing plain clothes.',
  'You have restarted before. You know the way.',
  'Hard days make the easy ones possible.',
  'Endure the plateau. The climb resumes without warning.',
  'A setback pauses the sentence. You still get to finish it.',
  'The mountain does not get lower. You get stronger.',
  'Tired legs still cover distance.',
  'It is supposed to be difficult. That is how you know it counts.',
  'Continue at the speed of today.',
  'What feels like standing still is often roots growing.',
  'The attempt that fails teaches the attempt that works.',
  'Return to the desk. That is the victory for now.',
  'Long preparations are won in the middle months.',
  'You only have to outlast this one hour.',
  'Keep the lamp lit a little longer.',
  'Doubt is loud at night. Work in the morning will answer it.',
  'Every day you do not quit is a day you win.',
  'Stone by stone, the path appears.',
  'The marks you want are hidden in the chapters you avoid.',
  'Begin again as many times as it takes.',
  'A year from now you will be glad you stayed.',
  'Grit is mostly patience with a deadline.',
  'When the result is far, measure the effort instead.',
  'Storms pass. Students who kept reading remain.',
  'You are not starting over. You are starting from experience.',
  'Keep the pace you can keep until the end.',
  'Let the result be late. Do not let the effort be.',
  'Roots first, then height.',
  'The hardest chapter is the one before it gets easier.',
  'Stay. The understanding is on its way.',
  'Do not count the pages left. Count the page you are on.',
  'Strength is what is left after the excuses are used up.',
  'The summit is just the last of many small ledges.',
  'There is no wasted effort, only delayed results.',
  'Carry on quietly. Loud quitters are forgotten.',
  'A long syllabus is a short list of days well used.',
  'Bend like bamboo, and keep growing.',
  'What you repeat through boredom becomes mastery.',
  'The night shift of effort pays in the morning.',
  'Lose the day, not the week.',
  'Lose the week, not the month. Then come back.',
  'Your attempt today is training for the one that counts.',
  'Walk when you cannot run. Sit and read when you cannot walk.',
  'Hold on through the dull part. It is most of the journey.',
  'An ember kept alive becomes a fire again.',
  'Water shapes the rock by coming back every day.',
  'The exam rewards those who kept showing up in March.',
  'A tired mind still learns something. Give it a little.',
  'It did not go well. Go again.',
  'Persistence is the art of unremarkable days.',
  'The last revision feels the heaviest and matters the most.',
  'Stay the course until the course becomes the habit.',
  'Courage is opening the book you failed in.',
  'You have more attempts in you than you think.',
  'Keep faith with the plan through the grey weeks.',
  'The distance is real. So is the ground you have covered.',
  'No one sees the foundations. Lay them anyway.',
  'Finish the block. Decide about quitting afterwards.',
  'The seed does not see the tree. It grows all the same.',
  'What is difficult today is the warm-up of next month.',
  'Trust the slow accumulation.',
  'Come back after the break. That is all perseverance is.',
  'If you are weary, shorten the step, not the journey.',
  'Results are shy. Keep working and they come out.',
  'The road does not need you to be fast, only present.',
  'You have come a long way. The rest is the same walk.',
  'Add today to the pile. The pile is how it is done.',
  'Mile by mile, the map gets filled in.',
  'Being steady is a kind of being unstoppable.',
  'Winter study, summer harvest.',
  'Hold out for the version of you that finishes.',
  'The clock keeps going. So can you.',
  'Each revision is a brick. The wall is nearly there.',
  'Leave the worrying to the weather and keep reading.',
  'Another hour of effort is another door unlocked.',
  'Stay until the bell. Then stay proud.',
  'Hope is a habit of continuing.',
  'After the difficult hour, the ordinary ones feel easy.',
  'You are building something that will hold.',
  'Go on. The page after this one is lighter.',
]

const BEGINNING = [
  'Start with the smallest true step.',
  'Open the book. That is the hard part done.',
  'Five minutes is a beginning. Beginnings grow.',
  'You do not need a plan for the year. You need one for this hour.',
  'Write the first line badly and fix it later.',
  'Starting is a skill. Practise it daily.',
  'Clear the desk, clear the start.',
  'A day is long enough if you begin it.',
  'The first session is the lever for all the others.',
  'Make it so small you cannot refuse.',
  'Begin where you are, with what you know.',
  'Do the first question. Momentum handles the second.',
  'A good morning is decided in its first half hour.',
  'Read one page and see what happens.',
  'Lower the bar to get moving, then raise it.',
  'Switch on the lamp. The dark was never the problem.',
  'The task looks larger from outside it.',
  'Put the first tick on the list early.',
  'Start now. Tidy up the plan as you go.',
  'Today is a blank page with the pen already in your hand.',
  'Pick the next action, not the whole project.',
  'Half an hour early beats an hour of regret.',
  'An imperfect start is still a start.',
  'Set the timer and let it be the brave one.',
  'What is one thing you can finish before the break?',
  'Morning effort is paid at a higher rate.',
  'Open the atlas and find one place.',
  'A small win before breakfast changes the day.',
  'You will feel like it after you begin, not before.',
  'Let the first block be easy and the second be honest.',
  'The gap between idea and action is one click wide.',
  'Sharpen the pencil, then use it.',
  'Decide the first topic tonight and wake to a head start.',
  'Momentum is made, not found.',
  'Take the first step. The second will show itself.',
  'New day, same goal, fresh attempt.',
  'Start with what you dread and the rest is downhill.',
  'Start with what you like and the dread gets smaller.',
  'One clean hour and the day already belongs to you.',
  'There is a version of today that goes well. Start it.',
  'You only need enough light for the next step.',
  'Tiny is fine. Zero is the only bad number.',
  'Do a little, then a little more.',
  'The list gets shorter one line at a time.',
  'First block of the day: the most important thing.',
  'Stand up, stretch, sit down, begin.',
  'Let the start be clumsy. Let it be now.',
  'A chapter begun is a chapter half feared.',
  'It will never be less work than it is today.',
  'Choose the page. Press start.',
  'Begin with a question you want answered.',
  'A fresh hour is a second chance at the day.',
  'Nothing changes until the first minute is spent.',
  'Fill one line of the notebook and the page is no longer empty.',
  'You have begun harder things than this.',
  'This morning has gone. This minute has not.',
  'Get the first paragraph down and the essay knows where to go.',
  'Momentum is a quiet friend. Go and meet it.',
  'Set out before you feel certain.',
  'One place on the map, then its neighbours.',
  'Make the first move small and exact.',
  'A session started is already a different kind of day.',
  'You can start before the whole route is clear.',
  'Turn the page. Then turn the next.',
  'Let today’s first action be the one tomorrow thanks you for.',
  'The alarm, the water, the desk. Then the work.',
  'Be the kind of person who starts on time.',
  'An early page is worth two late ones.',
  'You can begin again in the middle of any day.',
  'Small steps do not look like much until you look back.',
  'Ease the door open. Walk through.',
  'The hardest sentence to write is the first. Write it anyway.',
  'A plan on paper is a path. Take the first metre.',
  'Commit to the opening ten minutes only.',
  'Wherever you stopped yesterday is the start line today.',
  'Curiosity is the easiest way in.',
  'Pick up the pen. The rest is arithmetic.',
  'Even a short session moves the needle.',
  'There is always something small you can do right now.',
  'Start, and the fear loses its best argument.',
]

/** Every line, in a stable order (the order is part of what makes "random" repeatable per day). */
export const QUOTES: readonly string[] = [...FOCUS, ...DISCIPLINE, ...LEARNING, ...CALM, ...PERSEVERANCE, ...BEGINNING]

export default QUOTES
