/** Editorial coverage aliases connect common news vocabulary to existing concepts; PYQ counts/index stay unchanged. */
export const COVERAGE_ALIASES: Record<string, string[]> = {
  'RBI': ['currency management', 'foreign exchange management', 'master circular', 'monetary policy committee'],
  'Fiscal policy': ['gdp', 'gross domestic product', 'capex', 'government expenditure', 'bond yields', 'treasury yields', 'fiscal deficit', 'double deflation'],
  'industrial policy': ['industrial output', 'industrial production', 'manufacturing output'],
  'digital payments': ['upi', 'unified payments interface'],
  'Parliamentary Committees': ['jpc', 'joint parliamentary committee'],
  'Governance': ['fcra', 'foreign contribution regulation', 'foreign contribution regulation act'],
  'ECI': ['electoral roll', 'electoral rolls', 'voter registration'],
  'public health': ['drug pricing', 'medicines are priced', 'contraceptive', 'contraceptive pill', 'food safety', 'fssai'],
  'Geography': ['el nino', 'la nina', 'glacier', 'glaciers', 'landslide', 'landslides', 'drought', 'freshwater resources', 'himalayas', 'floods'],
  'Environmental regulation': ['green crackers', 'air pollution', 'coalmine', 'coal mine', 'coal mining', 'leachate', 'landfill', 'landfills', 'sewage', 'solid waste'],
  'Biodiversity': ['orangutan', 'orangutans', 'habitat loss', 'wildlife conservation'],
  'Climate change': ['wildfires', 'global warming', 'sea level rise', 'carbon neutral', 'carbon neutrality'],
  'renewable energy': ['green energy corridor', 'solar power', 'wind power', 'green hydrogen', 'cbg', 'compressed biogas', 'energy storage'],
  'sustainable development': ['land degradation', 'land degraded'],
  'Space exploration': ['nuclear power moves into space', 'microgravity', 'lunar exploration'],
  'Biotechnology': ['genetic engineering', 'gene editing', 'crispr'],
  'Technology policy': ['deep technology', 'artificial intelligence', 'semiconductor', 'semiconductors'],
  'South Asia': ['sri lanka', 'maldives', 'nepal', 'bangladesh'],
  'Security': ['ukraine', 'gaza', 'ceasefire', 'nuclear safety'],
  'gender justice': ['women remain underrepresented', 'women in politics'],
  'Culture': ['swadesh darshan', 'archaeological', 'archaeology'],
}
