import { P } from './dsl.mjs'

/** Plateaus, plains, deserts, valleys, coasts, deltas, islands, capes and the seas around India. */
export default [
  // ── Plateaus ────────────────────────────────────────────────────────────
  P('plateau', 'Deccan Plateau', 17.5, 76.8, { lvl: 1, st: ['maharashtra', 'karnataka', 'telangana', 'andhra-pradesh'], region: 'peninsular-plateau', f: ['Triangular tableland between the Western and Eastern Ghats, sloping gently east.', 'Its north-west is covered by the Deccan Traps basalt, weathered into black (regur) cotton soil.'] }),
  P('plateau', 'Malwa Plateau', 23.3, 75.9, { lvl: 1, st: ['madhya-pradesh', 'rajasthan'], f: ['Basaltic plateau north of the Vindhya, drained by the Chambal and Betwa.', 'Indore, Ujjain and Bhopal lie on it.'] }),
  P('plateau', 'Chota Nagpur Plateau', 23.4, 85.3, { lvl: 1, st: ['jharkhand', 'chhattisgarh', 'odisha', 'west-bengal'], f: ['The “mineral heartland” of India: coal, iron ore, mica, bauxite and uranium.', 'Ranchi and Hazaribagh plateaus; the Damodar flows through a rift valley here.'] }),
  P('plateau', 'Meghalaya Plateau', 25.5, 91.4, { lvl: 1, st: 'meghalaya', aka: ['Shillong Plateau'], f: ['A detached part of the peninsular plateau, separated by the Garo–Rajmahal gap.', 'Its south face catches the monsoon: Mawsynram and Sohra are among the wettest places on Earth.'] }),
  P('plateau', 'Bundelkhand', 25.2, 79.3, { lvl: 1, st: ['uttar-pradesh', 'madhya-pradesh'], f: ['Granite and gneiss upland between the Yamuna and the Vindhya; drought-prone.', 'Jhansi, Banda and Chitrakoot lie here; the Betwa and Ken drain it.'] }),
  P('plateau', 'Baghelkhand', 24.3, 81.5, { lvl: 3, st: 'madhya-pradesh', f: ['Upland east of Bundelkhand around Rewa, between the Son and the Kaimur.'] }),
  P('plateau', 'Karnataka Plateau', 13.6, 76.3, { lvl: 3, st: 'karnataka', aka: ['Mysore Plateau'], f: ['Southern Deccan, divided into the hilly Malnad and the plains of Maidan.'] }),
  P('plateau', 'Telangana Plateau', 17.8, 79.0, { lvl: 3, st: 'telangana', f: ['Eastern Deccan of Archaean gneiss, drained by the Godavari and Krishna.'] }),
  P('plateau', 'Dandakaranya', 19.3, 81.9, { lvl: 3, st: ['chhattisgarh', 'odisha'], aka: ['Bastar Plateau'], f: ['Forested plateau of Bastar and Koraput drained by the Indravati.'] }),
  P('plateau', 'Amarkantak Plateau', 22.67, 81.75, { lvl: 1, st: 'madhya-pradesh', rel: { range: 'range.maikal-range' }, f: ['Source of the Narmada and Son (and the Johila); a pilgrimage centre.', 'Part of the Achanakmar-Amarkantak biosphere reserve.'] }),
  P('plateau', 'Changthang', 33.4, 78.9, { lvl: 2, st: 'ladakh', f: ['High, cold plateau of eastern Ladakh, home of the Changpa herders and Pashmina goats.', 'Pangong Tso and Tso Moriri lie here.'] }),

  // ── Deserts, plains and valleys ─────────────────────────────────────────
  P('desert', 'Thar Desert', 27.0, 71.2, { lvl: 1, st: ['rajasthan', 'gujarat'], aka: ['Great Indian Desert'], region: 'indian-desert', f: ['Lies west of the Aravalli; receives less than 150 mm of rain in the far west.', 'The Luni is its only large river; the Desert National Park protects the Great Indian Bustard.'] }),
  P('desert', 'Rann of Kutch', 23.9, 70.2, { lvl: 1, st: 'gujarat', sub: 'Salt marsh', f: ['A seasonal salt marsh: flooded in the monsoon, a white salt flat in winter.', 'The Great Rann borders Pakistan; the Little Rann shelters the Indian wild ass.'] }),
  P('plain', 'Indo-Gangetic Plain', 26.6, 81.5, { lvl: 1, st: ['punjab', 'haryana', 'uttar-pradesh', 'bihar', 'west-bengal'], aka: ['Northern Plains'], f: ['One of the world’s largest alluvial plains, built by the Indus, Ganga and Brahmaputra.', 'Older alluvium is bhangar; newer floodplain alluvium is khadar.'] }),
  P('plain', 'Ganga–Yamuna Doab', 27.4, 79.0, { lvl: 2, st: 'uttar-pradesh', f: ['The fertile land between the Ganga and Yamuna, from Haridwar to Prayagraj.'] }),
  P('plain', 'Terai', 28.2, 81.5, { aka: ['Tarai'], lvl: 1, st: ['uttarakhand', 'uttar-pradesh', 'bihar', 'west-bengal'], f: ['A marshy, forested belt south of the Bhabar where streams re-emerge.', 'Dudhwa, Pilibhit and Valmiki reserves protect its grasslands.'] }),
  P('plain', 'Bhabar', 29.35, 79.2, { lvl: 2, st: 'uttarakhand', f: ['A narrow belt of pebbles at the foot of the Shiwalik where streams disappear underground.'] }),
  P('plain', 'Punjab Plains', 30.6, 75.3, { lvl: 2, st: ['punjab', 'haryana'], f: ['Formed by the Indus tributaries; its doabs are Bist, Bari, Rechna, Chaj and Sind Sagar.'] }),
  P('valley', 'Brahmaputra Valley', 26.6, 92.8, { lvl: 1, st: 'assam', f: ['A long, narrow alluvial valley between the Himalaya and the Meghalaya plateau.', 'Rich in tea, with Kaziranga and Majuli along the river.'] }),
  P('valley', 'Barak Valley', 24.75, 92.65, { lvl: 3, st: 'assam', f: ['Southern Assam around Silchar, drained by the Barak.'] }),
  P('valley', 'Kashmir Valley', 34.05, 74.8, { lvl: 1, st: 'jammu-and-kashmir', f: ['A basin between the Pir Panjal and the Great Himalaya, drained by the Jhelum.', 'Its lake deposits (karewas) are known for saffron.'] }),
  P('valley', 'Kullu Valley', 32.0, 77.12, { lvl: 2, st: 'himachal-pradesh', rel: { onRiver: ['river.beas'] }, f: ['The Beas valley between Mandi and Manali, the “valley of gods”.'] }),
  P('valley', 'Kangra Valley', 32.1, 76.3, { lvl: 3, st: 'himachal-pradesh', f: ['Below the Dhauladhar; known for tea and miniature painting.'] }),
  P('valley', 'Lahaul Valley', 32.57, 77.03, { lvl: 3, st: 'himachal-pradesh', f: ['Chandra–Bhaga valley north of the Rohtang pass.'] }),
  P('valley', 'Spiti Valley', 32.25, 78.03, { lvl: 2, st: 'himachal-pradesh', f: ['A cold-desert valley on the Tibet border; Key monastery and Pin Valley National Park.'] }),
  P('valley', 'Nubra Valley', 34.6, 77.55, { lvl: 2, st: 'ladakh', f: ['Valley of the Shyok and Nubra north of Khardung La, with Bactrian camels at Hunder.'] }),
  P('valley', 'Galwan Valley', 34.75, 78.2, { lvl: 2, st: 'ladakh', f: ['Aksai Chin border valley, site of the June 2020 India–China clash.'] }),
  P('valley', 'Doon Valley', 30.32, 78.0, { lvl: 2, st: 'uttarakhand', f: ['A longitudinal valley (dun) between the Shiwalik and the Lesser Himalaya, with Dehradun.'] }),
  P('valley', 'Narmada Valley', 22.8, 77.0, { lvl: 2, st: 'madhya-pradesh', sub: 'Rift valley', f: ['A rift valley between the Vindhya and Satpura; the Narmada flows west along it.'] }),
  P('valley', 'Damodar Valley', 23.7, 86.4, { lvl: 2, st: ['jharkhand', 'west-bengal'], sub: 'Rift valley', f: ['A rift valley holding Gondwana coal: Jharia, Raniganj and Bokaro coalfields.'] }),
  P('valley', 'Imphal Valley', 24.75, 93.9, { aka: ['Imphal Basin'], lvl: 3, st: 'manipur', f: ['An oval basin in the Manipur hills with Loktak lake at its south.'] }),
  P('valley', 'Araku Valley', 18.33, 82.87, { lvl: 3, st: 'andhra-pradesh', f: ['Eastern Ghats valley known for coffee and the Borra caves.'] }),
  P('valley', 'Chumbi Valley', 27.45, 88.95, { lvl: 3, co: 'CHN', f: ['A Tibetan wedge between Sikkim and Bhutan, reached by the Nathu La and Jelep La.'] }),

  // ── Coasts and deltas ───────────────────────────────────────────────────
  P('coast', 'Konkan Coast', 17.6, 73.25, { lvl: 1, st: ['maharashtra', 'goa'], region: 'coastal-plains', f: ['Rocky, indented coast from Daman to Goa, with the Konkan Railway.'] }),
  P('coast', 'Kanara Coast', 14.0, 74.45, { lvl: 3, st: 'karnataka', region: 'coastal-plains', aka: ['Karavali'], f: ['Karnataka coast from Goa to Mangaluru, with waterfalls from the Ghats.'] }),
  P('coast', 'Malabar Coast', 10.9, 75.85, { lvl: 1, st: 'kerala', region: 'coastal-plains', f: ['Kerala coast with lagoons and backwaters (kayals) behind sand bars.', 'Historic spice coast: Kozhikode, where Vasco da Gama landed in 1498.'] }),
  P('coast', 'Coromandel Coast', 12.4, 80.1, { lvl: 1, st: ['tamil-nadu', 'puducherry', 'andhra-pradesh'], region: 'coastal-plains', f: ['Tamil Nadu coast from Pulicat to Point Calimere.', 'Gets most of its rain from the north-east (retreating) monsoon in winter.'] }),
  P('coast', 'Northern Circars', 17.35, 82.45, { lvl: 1, st: 'andhra-pradesh', region: 'coastal-plains', f: ['Andhra coast between the Krishna and Mahanadi deltas.'] }),
  P('coast', 'Utkal Coast', 20.1, 86.5, { lvl: 3, st: 'odisha', region: 'coastal-plains', f: ['Odisha coast with the Mahanadi delta and Chilika lake.'] }),
  P('region', 'Kathiawar Peninsula', 21.8, 70.9, { lvl: 1, st: 'gujarat', aka: ['Kathiawar', 'Saurashtra'], f: ['Peninsula between the Gulfs of Kutch and Khambhat; the Gir forest and Girnar hills lie at its centre.'] }),
  P('delta', 'Sundarbans Delta', 22.0, 88.9, { lvl: 1, st: 'west-bengal', aka: ['Ganga–Brahmaputra Delta'], f: ['The world’s largest delta, shared by India and Bangladesh.', 'Named after the sundari mangrove tree.'] }),
  P('delta', 'Mahanadi Delta', 20.3, 86.3, { lvl: 2, st: 'odisha', f: ['Densely populated delta around Cuttack; one of the most cyclone-prone coasts.'] }),
  P('delta', 'Godavari Delta', 16.65, 82.05, { lvl: 2, st: 'andhra-pradesh', f: ['Rice bowl of Andhra Pradesh, with the Coringa mangroves.'] }),
  P('delta', 'Krishna Delta', 15.95, 81.0, { lvl: 3, st: 'andhra-pradesh', f: ['Joins with the Godavari delta; Kolleru lake lies between them.'] }),
  P('delta', 'Kaveri Delta', 10.9, 79.45, { lvl: 2, st: 'tamil-nadu', f: ['The “rice bowl of Tamil Nadu” around Thanjavur.'] }),

  // ── Islands and capes ───────────────────────────────────────────────────
  P('island', 'Majuli', 26.95, 94.17, { lvl: 1, st: 'assam', rel: { onRiver: ['river.brahmaputra'] }, f: ['One of the world’s largest river islands, in the Brahmaputra.', 'India’s first island district (2016), a centre of Vaishnavite satras.'] }),
  P('island', 'Umananda', 26.2, 91.75, { lvl: 3, st: 'assam', rel: { onRiver: ['river.brahmaputra'] }, f: ['Among the smallest inhabited river islands, in the Brahmaputra at Guwahati.'] }),
  P('island', 'Andaman Islands', 12.3, 92.8, { lvl: 1, st: 'andaman-and-nicobar', f: ['Peaks of a submarine range continuing the Arakan Yoma.', 'Separated from the Nicobars by the Ten Degree Channel.'] }),
  P('island', 'Nicobar Islands', 8.2, 93.5, { lvl: 1, st: 'andaman-and-nicobar', f: ['Southern group of the UT; Car Nicobar in the north, Great Nicobar in the south.'] }),
  P('island', 'Great Nicobar', 7.0, 93.85, { lvl: 2, st: 'andaman-and-nicobar', f: ['Largest of the Nicobars; a UNESCO biosphere reserve.', 'Site of the Great Nicobar transshipment port and township project.'] }),
  P('island', 'Swaraj Dweep', 11.98, 93.0, { lvl: 3, st: 'andaman-and-nicobar', aka: ['Havelock Island'], f: ['Renamed in 2018; known for Radhanagar beach.'] }),
  P('island', 'Shaheed Dweep', 11.83, 93.03, { lvl: 3, st: 'andaman-and-nicobar', aka: ['Neil Island'], f: ['Renamed in 2018, south of Swaraj Dweep.'] }),
  P('island', 'Netaji Subhas Chandra Bose Dweep', 11.67, 92.76, { lvl: 3, st: 'andaman-and-nicobar', aka: ['Ross Island'], f: ['Former British headquarters off Port Blair, renamed in 2018.'] }),
  P('island', 'North Sentinel Island', 11.55, 92.24, { lvl: 2, st: 'andaman-and-nicobar', f: ['Home of the Sentinelese, one of the world’s last uncontacted peoples; entry is prohibited.'] }),
  P('island', 'Lakshadweep Islands', 10.57, 72.64, { lvl: 1, st: 'lakshadweep', f: ['Coral atolls on the Chagos–Laccadive ridge; 36 islands, about 10 inhabited.'] }),
  P('island', 'Minicoy', 8.28, 73.05, { lvl: 2, st: 'lakshadweep', aka: ['Maliku'], f: ['Southernmost island of Lakshadweep, between the Nine and Eight Degree Channels.'] }),
  P('island', 'Rameswaram', 9.29, 79.31, { lvl: 1, st: 'tamil-nadu', aka: ['Rameshwaram', 'Pamban Island'], f: ['Linked to the mainland by the Pamban bridges, including India’s first vertical-lift sea bridge (2025).', 'Adam’s Bridge (Ram Setu), a chain of shoals, runs from here towards Sri Lanka.'] }),
  P('island', 'Sriharikota', 13.72, 80.23, { lvl: 1, st: 'andhra-pradesh', f: ['Barrier island between Pulicat lake and the sea.', 'Satish Dhawan Space Centre, ISRO’s launch port, is here.'] }),
  P('island', 'Abdul Kalam Island', 20.76, 87.09, { lvl: 2, st: 'odisha', aka: ['Wheeler Island'], f: ['Missile test range off the Odisha coast, renamed in 2015.'] }),
  P('island', 'Elephanta Island', 18.963, 72.931, { lvl: 2, st: 'maharashtra', aka: ['Gharapuri'], f: ['Island in Mumbai harbour with rock-cut Shaiva caves, a World Heritage Site.'] }),
  P('island', 'Diu', 20.71, 70.98, { lvl: 3, st: 'dnh-and-dd', f: ['Island off the Kathiawar coast; part of the UT of Dadra and Nagar Haveli and Daman and Diu.'] }),
  P('island', 'Katchatheevu', 9.38, 79.52, { lvl: 2, co: 'LKA', f: ['Islet in the Palk Strait ceded by India to Sri Lanka in 1974.'] }),
  P('cape', 'Kanyakumari', 8.078, 77.55, { lvl: 1, st: 'tamil-nadu', aka: ['Cape Comorin'], f: ['Southern tip of mainland India, where the Arabian Sea, Indian Ocean and Bay of Bengal meet.', 'Vivekananda Rock Memorial and the Thiruvalluvar statue stand offshore.'] }),
  P('cape', 'Indira Point', 6.75, 93.84, { lvl: 1, st: 'andaman-and-nicobar', f: ['India’s southernmost point, on Great Nicobar.', 'Its lighthouse area subsided in the 2004 tsunami.'] }),
  P('cape', 'Point Calimere', 10.29, 79.86, { lvl: 2, st: 'tamil-nadu', aka: ['Kodiakkarai'], f: ['Where the Coromandel coast turns west; a Ramsar wildlife sanctuary for flamingos.'] }),
  P('cape', 'Dhanushkodi', 9.15, 79.44, { lvl: 3, st: 'tamil-nadu', f: ['Tip of Rameswaram island, destroyed by the 1964 cyclone; closest point to Sri Lanka.'] }),
  P('region', 'Adam’s Bridge', 9.12, 79.52, { id: 'adams-bridge', lvl: 2, st: 'tamil-nadu', aka: ['Ram Setu'], sub: 'Chain of shoals', f: ['A chain of limestone shoals between Pamban and Mannar island, separating the Palk Bay from the Gulf of Mannar.'] }),

  // ── Seas, gulfs and channels ────────────────────────────────────────────
  P('sea', 'Arabian Sea', 15.0, 66.0, { lvl: 1, geom: 'marine:arabian-sea', f: ['North-western arm of the Indian Ocean between India and the Arabian peninsula.'] }),
  P('sea', 'Bay of Bengal', 15.0, 88.0, { lvl: 1, geom: 'marine:bay-of-bengal', f: ['The world’s largest bay; the Ganga, Brahmaputra, Mahanadi, Godavari, Krishna and Kaveri drain into it.'] }),
  P('sea', 'Andaman Sea', 11.0, 96.0, { lvl: 2, geom: 'marine:andaman-sea', f: ['Lies east of the Andaman and Nicobar Islands, bordered by Myanmar and Thailand.'] }),
  P('sea', 'Lakshadweep Sea', 9.5, 75.0, { lvl: 2, geom: 'marine:lakshadweep-sea', aka: ['Laccadive Sea'], f: ['Between Lakshadweep, Kerala and the Maldives.'] }),
  P('gulf', 'Gulf of Kutch', 22.6, 69.6, { lvl: 1, st: 'gujarat', geom: 'marine:gulf-of-kutch', f: ['Home of India’s first marine national park; Kandla (Deendayal) and Mundra ports lie on it.', 'Has one of India’s highest tidal ranges, suitable for tidal energy.'] }),
  P('gulf', 'Gulf of Khambhat', 21.6, 72.5, { lvl: 1, st: 'gujarat', geom: 'marine:gulf-of-khambhat', aka: ['Gulf of Cambay'], f: ['Receives the Sabarmati, Mahi, Narmada and Tapi.', 'Very high tides; the Alang ship-breaking yard is on its western shore.'] }),
  P('gulf', 'Gulf of Mannar', 8.9, 79.0, { lvl: 1, st: 'tamil-nadu', geom: 'marine:gulf-of-mannar', f: ['A marine national park and biosphere reserve rich in coral reefs, seagrass and dugongs.', 'Separated from the Palk Bay by Adam’s Bridge.'] }),
  P('gulf', 'Palk Bay', 9.7, 79.3, { lvl: 2, st: 'tamil-nadu', f: ['Shallow bay between Tamil Nadu and northern Sri Lanka.'] }),
  P('strait', 'Palk Strait', 10.0, 79.75, { lvl: 1, geom: 'marine:palk-strait', rel: { connects: ['sea.bay-of-bengal', 'gulf.palk-bay'] }, f: ['Separates Tamil Nadu from the Jaffna peninsula of Sri Lanka.', 'Too shallow for large ships (the Sethusamudram canal was proposed to fix this).'] }),
  P('strait', 'Ten Degree Channel', 10.0, 92.75, { lvl: 1, st: 'andaman-and-nicobar', f: ['Separates Little Andaman from Car Nicobar along the 10°N parallel.'] }),
  P('strait', 'Nine Degree Channel', 9.0, 73.0, { lvl: 1, st: 'lakshadweep', f: ['Separates Minicoy from the main Lakshadweep islands.'] }),
  P('strait', 'Eight Degree Channel', 7.8, 73.2, { lvl: 1, f: ['Separates Minicoy (India) from the Maldives.'] }),
  P('strait', 'Duncan Passage', 11.4, 92.6, { lvl: 2, st: 'andaman-and-nicobar', f: ['Separates South Andaman from Little Andaman.'] }),
  P('strait', 'Coco Channel', 13.75, 93.1, { lvl: 3, f: ['Separates North Andaman from Myanmar’s Coco Islands.'] }),
  P('strait', 'Great Channel', 6.2, 94.4, { lvl: 3, aka: ['Six Degree Channel'], f: ['Separates Great Nicobar from Sumatra (Indonesia).'] }),
  P('region', 'Sir Creek', 23.75, 68.55, { lvl: 2, st: 'gujarat', sub: 'Tidal estuary', f: ['A 96 km tidal estuary in the Rann of Kutch marshes, disputed between India and Pakistan.'] }),

  // ── Strategic and border regions ────────────────────────────────────────
  P('region', 'Siliguri Corridor', 26.7, 88.4, { lvl: 1, st: 'west-bengal', aka: ['Chicken’s Neck'], f: ['A strip about 20–22 km wide linking the Northeast with the rest of India, between Nepal and Bangladesh.'] }),
  P('region', 'Doklam', 27.29, 88.93, { lvl: 2, co: 'BTN', f: ['A plateau at the India–Bhutan–China trijunction; site of the 2017 standoff.'] }),
  P('region', 'Aksai Chin', 35.0, 79.2, { lvl: 1, st: 'ladakh', f: ['High cold desert in eastern Ladakh claimed by India and occupied by China.'] }),
  P('region', 'Kalapani', 30.21, 80.98, { lvl: 3, st: 'uttarakhand', f: ['Area near the Lipulekh pass at the source of the Kali; claimed by Nepal.'] }),

  // ── Added for previous-year papers (M7): position and facts from the cited sources (src) ──
  P('region', 'Shaksgam Valley', 36.6241, 76.2046, { lvl: 2, st: 'ladakh', f: ['The Shaksgam River is a left tributary of the Yarkand River.', 'The river is also known as the Kelechin River and Muztagh River.'], src: [{ title: 'Wikipedia: Shaksgam River', url: 'https://en.wikipedia.org/wiki/Shaksgam_River' }] }),
  P('valley', 'Nelang Valley', 31.1125, 79.0047, { lvl: 3, f: ['Nelang or Nilang river valley containing a small eponymous village, part of Jadh Ganga valley of the Himalayas, in the Uttarkashi District of Uttarakhand state of India is close to the disputed Sino-Indian Line of Actual Control.'], src: [{ title: 'Wikipedia: Nelang', url: 'https://en.wikipedia.org/wiki/Nelang' }] }),
  P('valley', 'Markha Valley', 34.0031, 77.2117, { lvl: 3, f: ['The Markha River is a river in Ladakh, India.', 'It is a tributary of the Zanskar River and starts at the junction of the Langtang Chu and Nimaling Chu.'], src: [{ title: 'Wikipedia: Markha River (India)', url: 'https://en.wikipedia.org/wiki/Markha_River_(India)' }] }),
  P('valley', 'Dzukou Valley', 25.5533, 94.0671, { lvl: 3, aka: ['Dzüko Valley'], f: ['The Dzukou Valley is a high-altitude valley in Northeast India, straddling the inter-state border of the states of Nagaland and Manipur.'], src: [{ title: 'Wikipedia: Dzukou Valley', url: 'https://en.wikipedia.org/wiki/Dzukou_Valley' }] }),
  P('valley', 'Sangla Valley', 31.4264, 78.265, { lvl: 3, f: ['Sangla is a town in the Baspa Valley, in the Kinnaur District of Himachal Pradesh, India, close to the border with Tibet.'], src: [{ title: 'Wikipedia: Sangla, India', url: 'https://en.wikipedia.org/wiki/Sangla,_India' }] }),
  P('valley', 'Yumthang Valley', 27.8268, 88.6959, { lvl: 3, f: ['The Yumthang Valley or Sikkim Valley of Flowers sanctuary, is a nature sanctuary with river, hot springs, yaks and grazing pasture on rolling meadows surrounded by the Himalayan mountains in Yumthang in the Mangan district of Sikkim state in India.'], src: [{ title: 'Wikipedia: Yumthang Valley of Flowers', url: 'https://en.wikipedia.org/wiki/Yumthang_Valley_of_Flowers' }] }),
  P('valley', 'Gandikota Canyon', 14.8147, 78.2867, { lvl: 3, aka: ['Gandikota'], f: ['Gandikota is a village and historical fort on the right bank of the Penna river, 15 km from Jammalamadugu in Kadapa district, Andhra Pradesh, India.'], src: [{ title: 'Wikipedia: Gandikota', url: 'https://en.wikipedia.org/wiki/Gandikota' }] }),
  P('region', 'Kuttanad', 9.425, 76.4639, { lvl: 2, f: ['Kuttanad is a river delta landscape region in the state of Kerala, India, known for its vast paddy fields and geographical peculiarities.'], src: [{ title: 'Wikipedia: Kuttanad', url: 'https://en.wikipedia.org/wiki/Kuttanad' }] }),
  P('region', 'Malnad', 13.1667, 75.5, { lvl: 3, aka: ['Malenadu'], f: ['Malenadu is a geographical region in the state of Karnataka, India.', 'It covers the western and eastern slopes of the Western Ghats mountain range, it also covers the Eastern Ghats range partly.'], src: [{ title: 'Wikipedia: Malenadu', url: 'https://en.wikipedia.org/wiki/Malenadu' }] }),
  P('region', 'Kori Creek', 23.5833, 68.3667, { lvl: 3, f: ['The Kori Creek is a tidal creek in the Kutch region of the Indian state of Gujarat.', 'It lies just to the west of the Great Rann of Kutch area of India.'], src: [{ title: 'Wikipedia: Kori Creek', url: 'https://en.wikipedia.org/wiki/Kori_Creek' }] }),
  P('grassland', 'Banni Grasslands', 23.55, 69.2667, { lvl: 3, aka: ['Banni Grassland'], f: ['Banni Grasslands Reserve or Banni grasslands form a belt of arid grassland ecosystem on the outer southern edge of the desert of the marshy salt flats of Rann of Kutch in Kutch District, Gujarat State, India.'], src: [{ title: 'Wikipedia: Banni Grasslands Reserve', url: 'https://en.wikipedia.org/wiki/Banni_Grasslands_Reserve' }] }),
  P('island', 'Salsette Island', 19.2, 72.9, { lvl: 3, aka: ['Salsette'], f: ['Salsette Island is an island in Konkan division of the state of Maharashtra, along India’s west coast.', 'The cities of Mumbai, Thane and Mira-Bhayandar lie on it, making it one of the most populous islands in the world.'], src: [{ title: 'Wikipedia: Salsette Island', url: 'https://en.wikipedia.org/wiki/Salsette_Island' }] }),
  P('island', 'Car Nicobar', 9.17, 92.78, { lvl: 3, f: ['Car Nicobar is the northernmost of the Nicobar Islands.', 'It is also one of the three local administrative divisions of the Indian district of Nicobar, part of the Indian union territory of the Andaman and Nicobar Islands.'], src: [{ title: 'Wikipedia: Car Nicobar', url: 'https://en.wikipedia.org/wiki/Car_Nicobar' }] }),
  P('island', 'Middle Andaman', 12.5, 92.8333, { lvl: 3, f: ['Middle Andaman Island is an island of the Andaman Islands.', 'It belongs to the North and Middle Andaman administrative district, part of the Indian union territory of Andaman and Nicobar Islands.'], src: [{ title: 'Wikipedia: Middle Andaman Island', url: 'https://en.wikipedia.org/wiki/Middle_Andaman_Island' }] }),
  P('island', 'Little Andaman', 10.65, 92.49, { lvl: 3, f: ['Little Andaman Island is the fourth largest of the Andaman Islands of India with an area of 707 km2, lying at the southern end of the archipelago.'], src: [{ title: 'Wikipedia: Little Andaman', url: 'https://en.wikipedia.org/wiki/Little_Andaman' }] }),
  P('island', 'North Andaman', 13.25, 92.93, { lvl: 3, f: ['North Andaman Island is the northern island of Great Andaman of the Andaman Islands.', 'It belongs to the North and Middle Andaman administrative district, part of the Indian union territory of Andaman and Nicobar Islands. the island is lying 137 km north from Port Blair.'], src: [{ title: 'Wikipedia: North Andaman Island', url: 'https://en.wikipedia.org/wiki/North_Andaman_Island' }] }),
  P('island', 'Piram Island', 21.5983, 72.3533, { lvl: 3, aka: ['Piram'], f: ['Piram Island or Piram Bet is an island in Gulf of Cambay of Arabian Sea which falls under Bhavnagar district of Gujarat state, India.'], src: [{ title: 'Wikipedia: Piram Island', url: 'https://en.wikipedia.org/wiki/Piram_Island' }] }),
  // ── end of previous-year-paper additions ──
]
