import { P } from './dsl.mjs'

const R = ['ramsar']

/** Lakes, wetlands, confluences, waterfalls, dams and barrages. */
export default [
  // ── Lakes and lagoons ───────────────────────────────────────────────────
  P('lake', 'Wular Lake', 34.36, 74.6, { lvl: 1, st: 'jammu-and-kashmir', tags: R, rel: { onRiver: ['river.jhelum'] }, f: ['One of Asia’s largest freshwater lakes, formed by tectonic activity and fed by the Jhelum.', 'A Ramsar site (1990).'] }),
  P('lake', 'Dal Lake', 34.12, 74.87, { lvl: 1, st: 'jammu-and-kashmir', f: ['Srinagar’s lake of houseboats and floating gardens (rad).'] }),
  P('lake', 'Pangong Tso', 33.75, 78.66, { lvl: 1, st: 'ladakh', f: ['A 134 km long endorheic brackish lake at about 4,225 m, about a third in India.', 'The Line of Actual Control crosses it; site of the 2020–21 standoff.'] }),
  P('lake', 'Tso Moriri', 32.9, 78.3, { lvl: 2, st: 'ladakh', tags: R, f: ['High-altitude lake in Changthang; breeding ground of the bar-headed goose and black-necked crane.'] }),
  P('lake', 'Tso Kar', 33.3, 78.0, { lvl: 3, st: 'ladakh', tags: R, f: ['Saline lake complex of Changthang, a Ramsar site since 2020.'] }),
  P('lake', 'Chandra Taal', 32.48, 77.61, { lvl: 3, st: 'himachal-pradesh', tags: R, f: ['Crescent lake near the source of the Chandra, in Lahaul-Spiti.'] }),
  P('lake', 'Renuka Lake', 30.61, 77.46, { lvl: 3, st: 'himachal-pradesh', tags: R, f: ['The largest natural lake of Himachal Pradesh, in Sirmaur.'] }),
  P('lake', 'Nainital', 29.39, 79.45, { lvl: 3, st: 'uttarakhand', aka: ['Naini Lake'], f: ['A tectonic lake of the Kumaon; the “lake district of India”.'] }),
  P('lake', 'Loktak Lake', 24.55, 93.8, { lvl: 1, st: 'manipur', tags: [...R, 'montreux'], f: ['The largest freshwater lake of the Northeast, known for floating phumdis.', 'Keibul Lamjao, the only floating national park, lies on it; on the Montreux Record.'] }),
  P('lake', 'Chilika Lake', 19.72, 85.32, { lvl: 1, st: 'odisha', tags: R, f: ['Asia’s largest brackish-water lagoon and India’s first Ramsar site (1981).', 'Winter home of migratory birds and of Irrawaddy dolphins; Nalabana is a bird sanctuary.'] }),
  P('lake', 'Pulicat Lake', 13.55, 80.17, { lvl: 1, st: ['andhra-pradesh', 'tamil-nadu'], f: ['India’s second-largest brackish lagoon; Sriharikota separates it from the sea.'] }),
  P('lake', 'Kolleru Lake', 16.65, 81.2, { lvl: 2, st: 'andhra-pradesh', tags: R, f: ['Large freshwater lake between the Godavari and Krishna deltas.'] }),
  P('lake', 'Vembanad Lake', 9.6, 76.4, { lvl: 1, st: 'kerala', tags: R, aka: ['Vembanad-Kol'], f: ['India’s longest lake and Kerala’s largest; Kochi port lies at its mouth.', 'Scene of the Nehru Trophy boat race; the Kuttanad below-sea-level farms border it.'] }),
  P('lake', 'Ashtamudi Lake', 8.95, 76.58, { lvl: 3, st: 'kerala', tags: R, f: ['Palm-shaped estuary near Kollam, the gateway to the backwaters.'] }),
  P('lake', 'Sasthamkotta Lake', 9.03, 76.63, { lvl: 3, st: 'kerala', tags: R, f: ['The largest freshwater lake of Kerala.'] }),
  P('lake', 'Sambhar Lake', 26.96, 75.08, { lvl: 1, st: 'rajasthan', tags: R, f: ['India’s largest inland saline lake and a major source of salt.'] }),
  P('lake', 'Pushkar Lake', 26.49, 74.55, { lvl: 3, st: 'rajasthan', f: ['Sacred lake near Ajmer with the rare Brahma temple; famous camel fair.'] }),
  P('lake', 'Lonar Lake', 19.98, 76.51, { lvl: 1, st: 'maharashtra', tags: R, f: ['A saline lake in a meteorite impact crater in basalt, about 50,000 years old.'] }),
  P('lake', 'Hussain Sagar', 17.42, 78.47, { lvl: 3, st: 'telangana', f: ['A 16th-century lake between Hyderabad and Secunderabad.'] }),
  P('lake', 'Sukhna Lake', 30.74, 76.81, { lvl: 3, st: 'chandigarh', f: ['Man-made lake at the foot of the Shiwalik in Chandigarh.'] }),
  P('lake', 'Gurudongmar Lake', 28.03, 88.71, { lvl: 3, st: 'sikkim', f: ['One of the world’s highest lakes (about 5,150 m), in north Sikkim.'] }),
  P('lake', 'Tsomgo Lake', 27.37, 88.76, { lvl: 3, st: 'sikkim', aka: ['Changu Lake'], f: ['Glacial lake on the road from Gangtok to Nathu La.'] }),
  P('lake', 'Manasarovar', 30.67, 81.47, { lvl: 1, co: 'CHN', aka: ['Mapam Yumco'], f: ['Sacred freshwater lake near Mount Kailash, at about 4,590 m.', 'Pilgrims reach it by the Lipulekh and Nathu La routes.'] }),
  P('lake', 'Rakshastal', 30.7, 81.25, { lvl: 3, co: 'CHN', f: ['Saline lake west of Manasarovar; the Sutlej rises near it.'] }),

  // ── Wetlands ────────────────────────────────────────────────────────────
  P('wetland', 'Harike Wetland', 31.17, 75.0, { lvl: 1, st: 'punjab', tags: R, rel: { onRiver: ['river.sutlej', 'river.beas'] }, f: ['Formed by the Harike barrage at the confluence of the Sutlej and Beas.', 'Source of the Indira Gandhi Canal that irrigates the Thar.'] }),
  P('wetland', 'Deepor Beel', 26.12, 91.66, { lvl: 3, st: 'assam', tags: R, f: ['Permanent freshwater lake in a former Brahmaputra channel near Guwahati.'] }),
  P('wetland', 'Kanwar Taal', 25.62, 86.13, { lvl: 3, st: 'bihar', tags: R, aka: ['Kabartal'], f: ['Bihar’s first Ramsar site, an oxbow lake of the Gandak in Begusarai.'] }),
  P('wetland', 'East Kolkata Wetlands', 22.55, 88.45, { lvl: 2, st: 'west-bengal', tags: R, f: ['Treats Kolkata’s sewage naturally through fisheries and farms.'] }),
  P('wetland', 'Rudrasagar Lake', 23.5, 91.32, { lvl: 3, st: 'tripura', tags: R, f: ['Lake with the Neermahal water palace.'] }),
  P('wetland', 'Nal Sarovar', 22.8, 72.04, { lvl: 3, st: 'gujarat', tags: R, f: ['Gujarat’s largest wetland bird sanctuary.'] }),
  P('wetland', 'Hokersar', 34.1, 74.72, { lvl: 3, st: 'jammu-and-kashmir', tags: R, f: ['“Queen of wetlands” of Kashmir, near Srinagar.'] }),
  P('wetland', 'Nawabganj Bird Sanctuary', 26.61, 80.66, { lvl: 3, st: 'uttar-pradesh', tags: R, aka: ['Nawabganj Wetland'], f: ['Ramsar site between Lucknow and Kanpur.'] }),
  P('wetland', 'Sur Sarovar', 27.23, 77.84, { lvl: 3, st: 'uttar-pradesh', tags: R, aka: ['Keetham Lake'], f: ['Ramsar site near Agra on the Yamuna.'] }),
  P('wetland', 'Sultanpur National Park', 28.46, 76.89, { lvl: 3, st: 'haryana', tags: R, f: ['Bird sanctuary near Gurugram, a Ramsar site.'] }),

  // ── Confluences ─────────────────────────────────────────────────────────
  P('confluence', 'Devprayag', 30.146, 78.598, { lvl: 1, st: 'uttarakhand', rel: { onRiver: ['river.bhagirathi', 'river.alaknanda', 'river.ganga'] }, f: ['The Bhagirathi and Alaknanda meet here to form the Ganga; the last of the Panch Prayag.'] }),
  P('confluence', 'Rudraprayag', 30.285, 78.981, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Mandakini, from Kedarnath, joins the Alaknanda.'] }),
  P('confluence', 'Karnaprayag', 30.263, 79.221, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Pindar joins the Alaknanda.'] }),
  P('confluence', 'Nandprayag', 30.333, 79.328, { lvl: 3, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Nandakini joins the Alaknanda.'] }),
  P('confluence', 'Vishnuprayag', 30.565, 79.575, { lvl: 3, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Dhauliganga joins the Alaknanda; the first of the Panch Prayag.'] }),
  P('confluence', 'Triveni Sangam', 25.424, 81.885, { lvl: 1, st: 'uttar-pradesh', rel: { onRiver: ['river.ganga', 'river.yamuna'] }, f: ['Meeting of the Ganga, the Yamuna and the mythical Saraswati at Prayagraj.', 'Site of the Kumbh and Maha Kumbh melas.'] }),
  P('confluence', 'Tandi', 32.55, 76.97, { lvl: 2, st: 'himachal-pradesh', rel: { onRiver: ['river.chenab'] }, f: ['The Chandra and Bhaga meet to form the Chenab (Chandrabhaga) in Lahaul.'] }),
  P('confluence', 'Nimmu', 34.19, 77.33, { lvl: 2, st: 'ladakh', rel: { onRiver: ['river.indus', 'river.zanskar'] }, f: ['The Zanskar joins the Indus west of Leh.'] }),
  P('confluence', 'Sadiya', 27.83, 95.65, { lvl: 2, st: 'assam', rel: { onRiver: ['river.brahmaputra', 'river.siang', 'river.dibang', 'river.lohit'] }, f: ['Near here the Siang, Dibang and Lohit unite as the Brahmaputra.'] }),
  P('confluence', 'Kaleshwaram', 18.81, 79.91, { lvl: 3, st: 'telangana', rel: { onRiver: ['river.godavari'] }, f: ['The Pranhita joins the Godavari; site of the Kaleshwaram lift irrigation project.'] }),
  P('confluence', 'Koodli', 13.87, 75.72, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.tungabhadra'] }, f: ['The Tunga and Bhadra meet to form the Tungabhadra.'] }),
  P('confluence', 'Pachnada', 26.43, 79.24, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.yamuna', 'river.chambal'] }, f: ['Five rivers meet: the Yamuna, Chambal, Sind, Kwari and Pahuj.'] }),

  // ── Waterfalls ──────────────────────────────────────────────────────────
  P('waterfall', 'Jog Falls', 14.229, 74.812, { lvl: 1, st: 'karnataka', el: 253, rel: { onRiver: ['river.sharavathi'] }, f: ['The Sharavathi plunges 253 m in four streams: Raja, Rani, Roarer and Rocket.'] }),
  P('waterfall', 'Kunchikal Falls', 13.53, 75.05, { lvl: 3, st: 'karnataka', f: ['Often cited as India’s highest waterfall (about 455 m), on the Varahi.'] }),
  P('waterfall', 'Nohkalikai Falls', 25.27, 91.69, { lvl: 2, st: 'meghalaya', f: ['India’s tallest plunge waterfall (about 340 m), near Sohra.'] }),
  P('waterfall', 'Dudhsagar Falls', 15.318, 74.314, { lvl: 2, st: 'goa', rel: { onRiver: ['river.mandovi'] }, f: ['Four-tiered falls on the Mandovi on the Goa–Karnataka border.'] }),
  P('waterfall', 'Athirappilly Falls', 10.285, 76.57, { lvl: 2, st: 'kerala', f: ['The largest waterfall of Kerala, on the Chalakudy river.'] }),
  P('waterfall', 'Chitrakote Falls', 19.206, 81.699, { lvl: 1, st: 'chhattisgarh', rel: { onRiver: ['river.indravati'] }, f: ['The widest waterfall in India, the “Niagara of India”, on the Indravati.'] }),
  P('waterfall', 'Dhuandhar Falls', 23.12, 79.8, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.narmada'] }, f: ['The Narmada’s “smoke cascade” at Bhedaghat, below the marble rocks.'] }),
  P('waterfall', 'Hundru Falls', 23.45, 85.65, { lvl: 3, st: 'jharkhand', rel: { onRiver: ['river.subarnarekha'] }, f: ['The Subarnarekha falls about 98 m near Ranchi.'] }),
  P('waterfall', 'Shivanasamudra Falls', 12.29, 77.17, { lvl: 2, st: 'karnataka', rel: { onRiver: ['river.kaveri'] }, f: ['Asia’s first hydroelectric station was built here in 1902.'] }),
  P('waterfall', 'Hogenakkal Falls', 12.12, 77.78, { lvl: 3, st: 'tamil-nadu', rel: { onRiver: ['river.kaveri'] }, f: ['Kaveri falls on carbonatite rocks, known for coracle rides.'] }),
  P('waterfall', 'Gokak Falls', 16.2, 74.78, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.ghataprabha'] }, f: ['Horseshoe falls on the Ghataprabha.'] }),

  // ── Dams and barrages ───────────────────────────────────────────────────
  P('dam', 'Bhakra Nangal Dam', 31.41, 76.43, { lvl: 1, st: 'himachal-pradesh', rel: { onRiver: ['river.sutlej'] }, f: ['Concrete gravity dam on the Sutlej forming the Gobind Sagar reservoir.', 'Called a “temple of resurgent India” by Nehru; serves Punjab, Haryana and Rajasthan.'] }),
  P('dam', 'Pong Dam', 31.97, 75.95, { lvl: 2, st: 'himachal-pradesh', tags: R, rel: { onRiver: ['river.beas'] }, f: ['Earth-fill dam on the Beas; its reservoir, Maharana Pratap Sagar, is a Ramsar site.'] }),
  P('dam', 'Ranjit Sagar Dam', 32.44, 75.73, { lvl: 3, st: 'punjab', aka: ['Thein Dam'], rel: { onRiver: ['river.ravi'] }, f: ['On the Ravi on the Punjab–J&K border.'] }),
  P('dam', 'Salal Dam', 33.14, 74.81, { lvl: 3, st: 'jammu-and-kashmir', rel: { onRiver: ['river.chenab'] }, f: ['Run-of-the-river project on the Chenab near Reasi.'] }),
  P('dam', 'Baglihar Dam', 33.16, 75.33, { lvl: 3, st: 'jammu-and-kashmir', rel: { onRiver: ['river.chenab'] }, f: ['Chenab project whose design was examined by a neutral expert under the Indus Waters Treaty (2007).'] }),
  P('dam', 'Tehri Dam', 30.38, 78.48, { lvl: 1, st: 'uttarakhand', rel: { onRiver: ['river.bhagirathi'] }, f: ['India’s tallest dam (about 260 m), on the Bhagirathi.'] }),
  P('dam', 'Farakka Barrage', 24.8, 87.93, { lvl: 1, st: 'west-bengal', rel: { onRiver: ['river.ganga'] }, f: ['Diverts Ganga water to the Hooghly to keep Kolkata port navigable.', 'Water sharing is governed by the India–Bangladesh Ganga Treaty (1996).'] }),
  P('dam', 'Rihand Dam', 24.2, 83.01, { lvl: 2, st: 'uttar-pradesh', aka: ['Govind Ballabh Pant Sagar'], f: ['Its reservoir, Govind Ballabh Pant Sagar, is one of India’s largest artificial lakes.', 'The Singrauli power hub surrounds it.'] }),
  P('dam', 'Matatila Dam', 25.1, 78.37, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.betwa'] }, f: ['On the Betwa near Lalitpur on the UP–MP border.'] }),
  P('dam', 'Gandhi Sagar Dam', 24.7, 75.55, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.chambal'] }, f: ['First of the Chambal valley dams, upstream of Rana Pratap Sagar and Jawahar Sagar.'] }),
  P('dam', 'Indira Sagar Dam', 22.28, 76.47, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.narmada'] }, f: ['Has India’s largest reservoir by volume, on the Narmada.'] }),
  P('dam', 'Sardar Sarovar Dam', 21.83, 73.75, { lvl: 1, st: 'gujarat', rel: { onRiver: ['river.narmada'] }, f: ['Concrete gravity dam on the Narmada at Kevadia; the Statue of Unity stands downstream.', 'Centre of the Narmada Bachao Andolan.'] }),
  P('dam', 'Ukai Dam', 21.25, 73.59, { lvl: 3, st: 'gujarat', rel: { onRiver: ['river.tapi'] }, f: ['The largest reservoir of Gujarat, on the Tapi.'] }),
  P('dam', 'Hirakud Dam', 21.57, 83.87, { lvl: 1, st: 'odisha', rel: { onRiver: ['river.mahanadi'] }, f: ['One of the world’s longest earthen dams (about 25.8 km with dykes), on the Mahanadi.'] }),
  P('dam', 'Maithon Dam', 23.78, 86.8, { lvl: 3, st: 'jharkhand', f: ['Damodar Valley Corporation dam on the Barakar, a Damodar tributary.'] }),
  P('dam', 'Koyna Dam', 17.4, 73.75, { lvl: 2, st: 'maharashtra', rel: { onRiver: ['river.koyna'] }, f: ['Serves one of India’s largest hydroelectric complexes; the Shivsagar reservoir.'] }),
  P('dam', 'Almatti Dam', 16.33, 75.89, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.krishna'] }, f: ['Upper Krishna project in Karnataka.'] }),
  P('dam', 'Tungabhadra Dam', 15.27, 76.34, { lvl: 2, st: 'karnataka', rel: { onRiver: ['river.tungabhadra'] }, f: ['At Hosapete; a joint project of Karnataka and Andhra Pradesh.'] }),
  P('dam', 'Srisailam Dam', 16.09, 78.9, { lvl: 2, st: ['andhra-pradesh', 'telangana'], rel: { onRiver: ['river.krishna'] }, f: ['On the Krishna in the Nallamala hills.'] }),
  P('dam', 'Nagarjuna Sagar Dam', 16.57, 79.31, { lvl: 1, st: ['telangana', 'andhra-pradesh'], rel: { onRiver: ['river.krishna'] }, f: ['One of the world’s largest masonry dams, on the Krishna.'] }),
  P('dam', 'Polavaram Project', 17.25, 81.65, { lvl: 2, st: 'andhra-pradesh', rel: { onRiver: ['river.godavari'] }, f: ['National project on the Godavari with a link canal to the Krishna.'] }),
  P('dam', 'Krishna Raja Sagara', 12.42, 76.57, { lvl: 2, st: 'karnataka', rel: { onRiver: ['river.kaveri'] }, f: ['Dam on the Kaveri near Mysuru, designed by M. Visvesvaraya; Brindavan gardens.'] }),
  P('dam', 'Mettur Dam', 11.79, 77.8, { lvl: 2, st: 'tamil-nadu', rel: { onRiver: ['river.kaveri'] }, f: ['Its reservoir, Stanley Reservoir, is one of Tamil Nadu’s largest.'] }),
  P('dam', 'Grand Anicut', 10.83, 78.82, { lvl: 2, st: 'tamil-nadu', aka: ['Kallanai'], rel: { onRiver: ['river.kaveri'] }, f: ['Built by the Chola king Karikalan around the 2nd century CE; still in use.'] }),
  P('dam', 'Idukki Dam', 9.84, 76.97, { lvl: 2, st: 'kerala', rel: { onRiver: ['river.periyar'] }, f: ['A double-curvature arch dam on the Periyar between the Kuravan and Kurathi hills.'] }),
  P('dam', 'Mullaperiyar Dam', 9.53, 77.14, { lvl: 2, st: 'kerala', rel: { onRiver: ['river.periyar'] }, f: ['Built in 1895 in Kerala but operated by Tamil Nadu; the subject of a long dispute.'] }),
]
