import { P } from './dsl.mjs'

const TR = ['tiger-reserve']
const WH = ['world-heritage']
const BR = ['biosphere']

/** Capitals, cities, ports, protected areas and heritage sites. */
export default [
  // ── National and state capitals ─────────────────────────────────────────
  P('capital', 'New Delhi', 28.6139, 77.209, { lvl: 1, st: 'delhi', tags: ['national'], rel: { onRiver: ['river.yamuna'] }, f: ['Capital of India, inaugurated in 1931 and designed by Lutyens and Baker.'] }),
  P('capital', 'Amaravati', 16.5131, 80.5165, { lvl: 1, st: 'andhra-pradesh', rel: { onRiver: ['river.krishna'] }, f: ['Capital of Andhra Pradesh, on the Krishna; an ancient Satavahana Buddhist centre.'] }),
  P('capital', 'Itanagar', 27.0844, 93.6053, { lvl: 1, st: 'arunachal-pradesh', f: ['Capital of Arunachal Pradesh; the Ita fort gives it its name.'] }),
  P('capital', 'Dispur', 26.1433, 91.7898, { lvl: 1, st: 'assam', f: ['Capital of Assam, a locality of Guwahati.'] }),
  P('capital', 'Patna', 25.5941, 85.1376, { lvl: 1, st: 'bihar', rel: { onRiver: ['river.ganga'] }, aka: ['Pataliputra'], f: ['Capital of Bihar on the Ganga; ancient Pataliputra, capital of the Mauryas.'] }),
  P('capital', 'Raipur', 21.2514, 81.6296, { lvl: 1, st: 'chhattisgarh', f: ['Capital of Chhattisgarh; Nava Raipur is the planned administrative city.'] }),
  P('capital', 'Panaji', 15.4909, 73.8278, { lvl: 1, st: 'goa', rel: { onRiver: ['river.mandovi'] }, f: ['Capital of Goa on the Mandovi estuary.'] }),
  P('capital', 'Gandhinagar', 23.2156, 72.6369, { lvl: 1, st: 'gujarat', rel: { onRiver: ['river.sabarmati'] }, f: ['Planned capital of Gujarat on the Sabarmati.'] }),
  P('capital', 'Chandigarh', 30.7333, 76.7794, { lvl: 1, st: 'chandigarh', f: ['Le Corbusier’s planned city; capital of Punjab and Haryana and itself a Union Territory.'] }),
  P('capital', 'Shimla', 31.1048, 77.1734, { lvl: 1, st: 'himachal-pradesh', f: ['Capital of Himachal Pradesh and former summer capital of British India.'] }),
  P('capital', 'Ranchi', 23.3441, 85.3096, { lvl: 1, st: 'jharkhand', f: ['Capital of Jharkhand on the Ranchi plateau; the Subarnarekha rises nearby.'] }),
  P('capital', 'Bengaluru', 12.9716, 77.5946, { lvl: 1, st: 'karnataka', f: ['Capital of Karnataka on the Mysore plateau; India’s technology capital.'] }),
  P('capital', 'Thiruvananthapuram', 8.5241, 76.9366, { lvl: 1, st: 'kerala', f: ['Capital of Kerala; Vizhinjam port and the VSSC space centre are nearby.'] }),
  P('capital', 'Bhopal', 23.2599, 77.4126, { lvl: 1, st: 'madhya-pradesh', f: ['Capital of Madhya Pradesh, the “city of lakes”; the Bhimbetka shelters are nearby.'] }),
  P('capital', 'Mumbai', 19.076, 72.8777, { lvl: 1, st: 'maharashtra', f: ['Capital of Maharashtra and India’s financial capital, built on seven islands.'] }),
  P('capital', 'Imphal', 24.817, 93.9368, { lvl: 1, st: 'manipur', f: ['Capital of Manipur in the Imphal valley.'] }),
  P('capital', 'Shillong', 25.5788, 91.8933, { lvl: 1, st: 'meghalaya', f: ['Capital of Meghalaya on the Khasi hills, the “Scotland of the East”.'] }),
  P('capital', 'Aizawl', 23.7271, 92.7176, { lvl: 1, st: 'mizoram', f: ['Capital of Mizoram, on a ridge of the Mizo hills.'] }),
  P('capital', 'Kohima', 25.6751, 94.1086, { lvl: 1, st: 'nagaland', f: ['Capital of Nagaland; the 1944 battle of Kohima; the Hornbill festival is held nearby.'] }),
  P('capital', 'Bhubaneswar', 20.2961, 85.8245, { lvl: 1, st: 'odisha', f: ['Capital of Odisha, the “temple city”, planned by Otto Koenigsberger.'] }),
  P('capital', 'Jaipur', 26.9124, 75.7873, { lvl: 1, st: 'rajasthan', f: ['Capital of Rajasthan, the “pink city”, a World Heritage city.'] }),
  P('capital', 'Gangtok', 27.3389, 88.6065, { lvl: 1, st: 'sikkim', f: ['Capital of Sikkim, on the road to Nathu La.'] }),
  P('capital', 'Chennai', 13.0827, 80.2707, { lvl: 1, st: 'tamil-nadu', f: ['Capital of Tamil Nadu on the Coromandel coast; Marina beach.'] }),
  P('capital', 'Hyderabad', 17.385, 78.4867, { lvl: 1, st: 'telangana', rel: { onRiver: ['river.musi'] }, f: ['Capital of Telangana on the Musi; the Charminar.'] }),
  P('capital', 'Agartala', 23.8315, 91.2868, { lvl: 1, st: 'tripura', f: ['Capital of Tripura, close to the Bangladesh border; linked to Akhaura by rail.'] }),
  P('capital', 'Lucknow', 26.8467, 80.9462, { lvl: 1, st: 'uttar-pradesh', rel: { onRiver: ['river.gomti'] }, f: ['Capital of Uttar Pradesh on the Gomti; the city of the Nawabs of Awadh.'] }),
  P('capital', 'Dehradun', 30.3165, 78.0322, { lvl: 1, st: 'uttarakhand', rel: { within: 'valley.doon-valley' }, f: ['Capital of Uttarakhand in the Doon valley; Gairsain is the summer capital.'] }),
  P('capital', 'Kolkata', 22.5726, 88.3639, { lvl: 1, st: 'west-bengal', rel: { onRiver: ['river.hooghly'] }, f: ['Capital of West Bengal on the Hooghly; capital of British India until 1911.'] }),
  P('capital', 'Sri Vijaya Puram', 11.6234, 92.7265, { lvl: 1, st: 'andaman-and-nicobar', aka: ['Port Blair'], f: ['Capital of the Andaman and Nicobar Islands, renamed from Port Blair in 2024.', 'The Cellular Jail is here.'] }),
  P('capital', 'Daman', 20.3974, 72.8328, { lvl: 2, st: 'dnh-and-dd', f: ['Capital of Dadra and Nagar Haveli and Daman and Diu.'] }),
  P('capital', 'Srinagar', 34.0837, 74.7973, { lvl: 1, st: 'jammu-and-kashmir', rel: { onRiver: ['river.jhelum'] }, f: ['Summer capital of Jammu and Kashmir, on the Jhelum and Dal lake.'] }),
  P('capital', 'Jammu', 32.7266, 74.857, { lvl: 1, st: 'jammu-and-kashmir', f: ['Winter capital of Jammu and Kashmir, on the Tawi.'] }),
  P('capital', 'Leh', 34.1526, 77.5771, { lvl: 1, st: 'ladakh', rel: { onRiver: ['river.indus'] }, f: ['Capital of Ladakh near the Indus, at about 3,500 m.'] }),
  P('capital', 'Kavaratti', 10.5667, 72.6417, { lvl: 1, st: 'lakshadweep', f: ['Capital of Lakshadweep, on a coral atoll.'] }),
  P('capital', 'Puducherry', 11.9416, 79.8083, { lvl: 1, st: 'puducherry', f: ['Capital of the UT; former French colony (until 1954); Auroville is nearby.'] }),
  // Neighbours
  P('capital', 'Islamabad', 33.6844, 73.0479, { lvl: 1, co: 'PAK', tags: ['national'], f: ['Capital of Pakistan at the foot of the Margalla hills.'] }),
  P('capital', 'Kabul', 34.5553, 69.2075, { lvl: 2, co: 'AFG', tags: ['national'], f: ['Capital of Afghanistan on the Kabul river.'] }),
  P('capital', 'Kathmandu', 27.7172, 85.324, { lvl: 1, co: 'NPL', tags: ['national'], f: ['Capital of Nepal in the Kathmandu valley.'] }),
  P('capital', 'Thimphu', 27.4728, 89.639, { lvl: 1, co: 'BTN', tags: ['national'], f: ['Capital of Bhutan in the Wang Chu valley.'] }),
  P('capital', 'Dhaka', 23.8103, 90.4125, { lvl: 1, co: 'BGD', tags: ['national'], f: ['Capital of Bangladesh on the Buriganga.'] }),
  P('capital', 'Naypyidaw', 19.7633, 96.0785, { lvl: 1, co: 'MMR', tags: ['national'], f: ['Capital of Myanmar since 2006, replacing Yangon.'] }),
  P('capital', 'Sri Jayawardenepura Kotte', 6.8868, 79.9187, { lvl: 2, co: 'LKA', tags: ['national'], f: ['Legislative capital of Sri Lanka; Colombo is the commercial capital.'] }),

  // ── Cities ──────────────────────────────────────────────────────────────
  P('city', 'Varanasi', 25.3176, 82.9739, { lvl: 1, st: 'uttar-pradesh', aka: ['Kashi', 'Banaras'], rel: { onRiver: ['river.ganga'] }, f: ['One of the world’s oldest living cities, on the left bank of the Ganga.', 'Sarnath, where the Buddha first preached, is nearby.'] }),
  P('city', 'Prayagraj', 25.4358, 81.8463, { lvl: 1, st: 'uttar-pradesh', aka: ['Allahabad'], rel: { onRiver: ['river.ganga', 'river.yamuna'] }, f: ['At the Triveni Sangam; hosts the Kumbh mela.'] }),
  P('city', 'Agra', 27.1767, 78.0081, { lvl: 1, st: 'uttar-pradesh', rel: { onRiver: ['river.yamuna'] }, f: ['Mughal capital on the Yamuna: Taj Mahal, Agra Fort and nearby Fatehpur Sikri.'] }),
  P('city', 'Kanpur', 26.4499, 80.3319, { lvl: 2, st: 'uttar-pradesh', rel: { onRiver: ['river.ganga'] }, f: ['Industrial city on the Ganga, known for leather.'] }),
  P('city', 'Ayodhya', 26.7922, 82.1998, { lvl: 2, st: 'uttar-pradesh', rel: { onRiver: ['river.ghaghara'] }, f: ['On the Saryu (Ghaghara); the Ram Mandir opened in 2024.'] }),
  P('city', 'Gorakhpur', 26.7606, 83.3732, { lvl: 2, st: 'uttar-pradesh', rel: { onRiver: ['river.rapti'] }, f: ['On the Rapti; has one of the world’s longest railway platforms.'] }),
  P('city', 'Jhansi', 25.4484, 78.5685, { lvl: 2, st: 'uttar-pradesh', rel: { within: 'plateau.bundelkhand' }, f: ['Gateway to Bundelkhand; Rani Lakshmibai’s fort.'] }),
  P('city', 'Mathura', 27.4924, 77.6737, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.yamuna'] }, f: ['On the Yamuna; a centre of the Mathura school of Kushan sculpture.'] }),
  P('city', 'Meerut', 28.9845, 77.7064, { lvl: 3, st: 'uttar-pradesh', f: ['Where the revolt of 1857 began.'] }),
  P('city', 'Bareilly', 28.367, 79.4304, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.ramganga'] }, f: ['Rohilkhand city on the Ramganga.'] }),
  P('city', 'Ahmedabad', 23.0225, 72.5714, { lvl: 1, st: 'gujarat', rel: { onRiver: ['river.sabarmati'] }, f: ['India’s first World Heritage city (2017), on the Sabarmati.'] }),
  P('city', 'Surat', 21.1702, 72.8311, { lvl: 2, st: 'gujarat', rel: { onRiver: ['river.tapi'] }, f: ['On the Tapi estuary; a world centre of diamond cutting.'] }),
  P('city', 'Bhuj', 23.242, 69.6669, { lvl: 3, st: 'gujarat', f: ['Kutch town rebuilt after the 2001 earthquake.'] }),
  P('city', 'Pune', 18.5204, 73.8567, { lvl: 2, st: 'maharashtra', f: ['On the Deccan plateau, east of the Bhor Ghat.'] }),
  P('city', 'Nagpur', 21.1458, 79.0882, { lvl: 1, st: 'maharashtra', f: ['Near the geographical centre of India (Zero Mile Stone); famous for oranges.'] }),
  P('city', 'Nashik', 19.9975, 73.7898, { lvl: 2, st: 'maharashtra', rel: { onRiver: ['river.godavari'] }, f: ['On the Godavari near its source; hosts a Kumbh mela.'] }),
  P('city', 'Indore', 22.7196, 75.8577, { lvl: 2, st: 'madhya-pradesh', rel: { within: 'plateau.malwa-plateau' }, f: ['Largest city of Madhya Pradesh, on the Malwa plateau.'] }),
  P('city', 'Ujjain', 23.1765, 75.7885, { lvl: 2, st: 'madhya-pradesh', f: ['On the Kshipra; its meridian was the prime meridian of ancient Indian astronomy.', 'The Tropic of Cancer passes close to it.'] }),
  P('city', 'Jabalpur', 23.1815, 79.9864, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.narmada'] }, f: ['On the Narmada; the marble rocks of Bhedaghat are nearby.'] }),
  P('city', 'Kota', 25.2138, 75.8648, { lvl: 2, st: 'rajasthan', rel: { onRiver: ['river.chambal'] }, f: ['On the Chambal; the Kota barrage.'] }),
  P('city', 'Jodhpur', 26.2389, 73.0243, { lvl: 2, st: 'rajasthan', f: ['The “blue city” on the edge of the Thar, below Mehrangarh fort.'] }),
  P('city', 'Jaisalmer', 26.9157, 70.9083, { lvl: 2, st: 'rajasthan', rel: { within: 'desert.thar-desert' }, f: ['The “golden city” in the heart of the Thar; its fort is a World Heritage hill fort.'] }),
  P('city', 'Udaipur', 24.5854, 73.7125, { lvl: 2, st: 'rajasthan', f: ['The “city of lakes” in the Aravalli: Pichola and Fateh Sagar.'] }),
  P('city', 'Amritsar', 31.634, 74.8723, { lvl: 2, st: 'punjab', f: ['Home of the Golden Temple; the Attari–Wagah border is nearby.'] }),
  P('city', 'Haridwar', 29.9457, 78.1642, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.ganga'] }, f: ['Where the Ganga leaves the hills and enters the plains; hosts a Kumbh mela.'] }),
  P('city', 'Madurai', 9.9252, 78.1198, { lvl: 2, st: 'tamil-nadu', rel: { onRiver: ['river.vaigai'] }, f: ['Temple city on the Vaigai: the Meenakshi Amman temple.'] }),
  P('city', 'Coimbatore', 11.0168, 76.9558, { lvl: 2, st: 'tamil-nadu', f: ['The “Manchester of south India”, at the eastern end of the Palghat Gap.'] }),
  P('city', 'Mysuru', 12.2958, 76.6394, { lvl: 2, st: 'karnataka', f: ['Former capital of the Wodeyars; famous for its Dasara.'] }),
  P('city', 'Kochi', 9.9312, 76.2673, { lvl: 1, st: 'kerala', rel: { within: 'lake.vembanad-lake' }, f: ['Queen of the Arabian Sea; port on the Vembanad backwaters.'] }),
  P('city', 'Kozhikode', 11.2588, 75.7804, { lvl: 3, st: 'kerala', aka: ['Calicut'], f: ['Vasco da Gama landed near here (Kappad) in 1498.'] }),
  P('city', 'Visakhapatnam', 17.6868, 83.2185, { lvl: 1, st: 'andhra-pradesh', f: ['HQ of the Eastern Naval Command; a natural harbour protected by the Dolphin’s Nose.'] }),
  P('city', 'Vijayawada', 16.5062, 80.648, { lvl: 3, st: 'andhra-pradesh', rel: { onRiver: ['river.krishna'] }, f: ['On the Krishna at the Prakasam barrage.'] }),
  P('city', 'Guwahati', 26.1445, 91.7362, { lvl: 1, st: 'assam', rel: { onRiver: ['river.brahmaputra'] }, f: ['Gateway to the Northeast on the Brahmaputra; the Kamakhya temple.'] }),
  P('city', 'Dibrugarh', 27.4728, 94.912, { lvl: 3, st: 'assam', rel: { onRiver: ['river.brahmaputra'] }, f: ['The “tea city of India”; the Bogibeel rail-road bridge is nearby.'] }),
  P('city', 'Silchar', 24.8333, 92.7789, { lvl: 3, st: 'assam', rel: { onRiver: ['river.barak'] }, f: ['Main town of the Barak valley.'] }),
  P('city', 'Tawang', 27.5861, 91.8594, { lvl: 2, st: 'arunachal-pradesh', f: ['Home of India’s largest Buddhist monastery, birthplace of the 6th Dalai Lama.'] }),
  P('city', 'Darjeeling', 27.041, 88.2663, { lvl: 2, st: 'west-bengal', f: ['Hill station famous for tea (a GI product) and the Darjeeling Himalayan Railway.'] }),
  P('city', 'Siliguri', 26.7271, 88.3953, { lvl: 3, st: 'west-bengal', rel: { within: 'region.siliguri-corridor' }, f: ['Commercial hub in the Siliguri corridor.'] }),
  P('city', 'Sohra', 25.2702, 91.7323, { lvl: 1, st: 'meghalaya', aka: ['Cherrapunji'], f: ['Once the wettest place on Earth; living root bridges nearby.'] }),
  P('city', 'Mawsynram', 25.2976, 91.5822, { lvl: 1, st: 'meghalaya', f: ['Receives the highest average annual rainfall on Earth, about 11,800 mm.'] }),
  P('city', 'Dras', 34.4297, 75.751, { lvl: 2, st: 'ladakh', f: ['One of the coldest inhabited places in India; the Kargil War Memorial.'] }),
  P('city', 'Kargil', 34.5539, 76.1349, { lvl: 2, st: 'ladakh', f: ['On the Suru river; the 1999 Kargil War.'] }),
  P('city', 'Manali', 32.2432, 77.1892, { lvl: 3, st: 'himachal-pradesh', rel: { onRiver: ['river.beas'] }, f: ['Head of the Kullu valley, below the Rohtang pass.'] }),
  P('city', 'Jamshedpur', 22.8046, 86.2029, { lvl: 1, st: 'jharkhand', rel: { onRiver: ['river.subarnarekha'] }, f: ['India’s first planned industrial city, founded around the Tata steel plant (1907).'] }),
  P('city', 'Dhanbad', 23.7957, 86.4304, { lvl: 2, st: 'jharkhand', rel: { within: 'valley.damodar-valley' }, f: ['The “coal capital of India”, beside the Jharia coalfield.'] }),
  P('city', 'Bhilai', 21.1938, 81.3509, { lvl: 2, st: 'chhattisgarh', f: ['Steel plant built with Soviet help (1959).'] }),
  P('city', 'Rourkela', 22.2604, 84.8536, { lvl: 2, st: 'odisha', rel: { onRiver: ['river.brahmani'] }, f: ['Steel plant built with West German help (1959).'] }),
  P('city', 'Durgapur', 23.5204, 87.3119, { lvl: 3, st: 'west-bengal', rel: { onRiver: ['river.damodar'] }, f: ['Steel plant built with British help (1959), on the Damodar.'] }),
  P('city', 'Puri', 19.8135, 85.8312, { lvl: 2, st: 'odisha', f: ['Seat of the Jagannath temple and the Rath Yatra.'] }),
  P('city', 'Lhasa', 29.652, 91.172, { lvl: 2, co: 'CHN', f: ['Capital of the Tibet Autonomous Region on the Lhasa river, a tributary of the Yarlung Tsangpo.'] }),

  // ── Ports ───────────────────────────────────────────────────────────────
  P('port', 'Deendayal Port', 23.0333, 70.2167, { lvl: 1, st: 'gujarat', aka: ['Kandla'], rel: { within: 'gulf.gulf-of-kutch' }, f: ['A tidal port on the Gulf of Kutch, built after Partition to replace Karachi.', 'Handles the most cargo of India’s major ports.'] }),
  P('port', 'Mundra Port', 22.74, 69.72, { lvl: 2, st: 'gujarat', rel: { within: 'gulf.gulf-of-kutch' }, f: ['India’s largest private port.'] }),
  P('port', 'Mumbai Port', 18.95, 72.85, { lvl: 2, st: 'maharashtra', f: ['A natural harbour, one of India’s oldest major ports.'] }),
  P('port', 'Jawaharlal Nehru Port', 18.95, 72.95, { lvl: 1, st: 'maharashtra', aka: ['Nhava Sheva'], f: ['India’s busiest container port, across the harbour from Mumbai.'] }),
  P('port', 'Mormugao Port', 15.41, 73.8, { lvl: 1, st: 'goa', f: ['Goa’s natural harbour, historically India’s main iron-ore export port.'] }),
  P('port', 'New Mangalore Port', 12.93, 74.81, { lvl: 2, st: 'karnataka', f: ['Exports Kudremukh iron ore and handles petroleum.'] }),
  P('port', 'Cochin Port', 9.97, 76.27, { lvl: 1, st: 'kerala', f: ['A natural harbour on Willingdon Island with the Vallarpadam transshipment terminal.'] }),
  P('port', 'Vizhinjam Port', 8.38, 76.99, { lvl: 1, st: 'kerala', f: ['India’s first deep-water container transshipment port, near the international shipping lane (2025).'] }),
  P('port', 'V. O. Chidambaranar Port', 8.76, 78.2, { id: 'tuticorin', lvl: 2, st: 'tamil-nadu', aka: ['Tuticorin'], f: ['On the Gulf of Mannar; famous for pearl fishing.'] }),
  P('port', 'Chennai Port', 13.1, 80.3, { lvl: 2, st: 'tamil-nadu', f: ['An artificial harbour, one of India’s oldest ports.'] }),
  P('port', 'Kamarajar Port', 13.25, 80.33, { lvl: 3, st: 'tamil-nadu', aka: ['Ennore'], f: ['India’s first corporatised major port.'] }),
  P('port', 'Visakhapatnam Port', 17.69, 83.28, { lvl: 1, st: 'andhra-pradesh', f: ['India’s deepest landlocked and protected port.'] }),
  P('port', 'Paradip Port', 20.26, 86.67, { lvl: 1, st: 'odisha', f: ['Near the Mahanadi mouth; exports iron ore and handles coal.'] }),
  P('port', 'Syama Prasad Mookerjee Port', 22.55, 88.32, { id: 'kolkata-port', lvl: 1, st: 'west-bengal', aka: ['Kolkata Port'], f: ['India’s only major river port, on the Hooghly; Haldia is its dock system downstream.'] }),
  P('port', 'Haldia', 22.03, 88.06, { lvl: 2, st: 'west-bengal', f: ['Deep-draft dock complex of Kolkata port at the Haldi–Hooghly confluence.'] }),
  P('port', 'Gwadar', 25.13, 62.32, { lvl: 2, co: 'PAK', f: ['Pakistani port built with China as part of CPEC.'] }),
  P('port', 'Chittagong', 22.33, 91.8, { lvl: 3, co: 'BGD', aka: ['Chattogram'], f: ['Bangladesh’s main port; India has transit access to it.'] }),
  P('port', 'Sittwe', 20.14, 92.9, { lvl: 3, co: 'MMR', f: ['Myanmar port built by India for the Kaladan project.'] }),
  P('port', 'Hambantota', 6.12, 81.11, { lvl: 3, co: 'LKA', f: ['Sri Lankan port leased to a Chinese company in 2017.'] }),

  // ── Protected areas ─────────────────────────────────────────────────────
  P('park', 'Jim Corbett National Park', 29.53, 78.77, { lvl: 1, st: 'uttarakhand', tags: TR, rel: { onRiver: ['river.ramganga'] }, f: ['India’s first national park (1936, as Hailey NP) where Project Tiger was launched in 1973.'] }),
  P('park', 'Rajaji National Park', 30.0, 78.2, { lvl: 3, st: 'uttarakhand', tags: TR, f: ['Shiwalik park known for elephants, near Haridwar.'] }),
  P('park', 'Valley of Flowers', 30.728, 79.605, { lvl: 2, st: 'uttarakhand', tags: WH, f: ['High-altitude alpine meadow; with Nanda Devi, a World Heritage Site.'] }),
  P('park', 'Nanda Devi National Park', 30.42, 79.87, { lvl: 2, st: 'uttarakhand', tags: [...WH, ...BR], f: ['Glacial basin around Nanda Devi; core of a UNESCO biosphere reserve.'] }),
  P('park', 'Great Himalayan National Park', 31.75, 77.55, { lvl: 2, st: 'himachal-pradesh', tags: WH, f: ['World Heritage Site in Kullu, home of the western tragopan.'] }),
  P('park', 'Pin Valley National Park', 31.95, 78.0, { lvl: 3, st: 'himachal-pradesh', f: ['Cold-desert park in Spiti; snow leopard and ibex.'] }),
  P('park', 'Hemis National Park', 33.9, 77.35, { lvl: 2, st: 'ladakh', f: ['India’s largest national park, famous for snow leopards.'] }),
  P('park', 'Dachigam National Park', 34.13, 75.05, { lvl: 3, st: 'jammu-and-kashmir', f: ['Last stronghold of the hangul (Kashmir stag).'] }),
  P('park', 'Dudhwa National Park', 28.5, 80.65, { lvl: 1, st: 'uttar-pradesh', tags: TR, rel: { within: 'plain.terai' }, f: ['Terai park on the Nepal border; swamp deer (barasingha) and rhinos reintroduced in 1984.'] }),
  P('park', 'Pilibhit Tiger Reserve', 28.7, 80.0, { lvl: 2, st: 'uttar-pradesh', tags: TR, f: ['Won the TX2 award (2020) for doubling its tiger numbers; on the Sharda.'] }),
  P('park', 'Amangarh Tiger Reserve', 29.5, 78.65, { lvl: 3, st: 'uttar-pradesh', tags: TR, f: ['Buffer of Corbett in Bijnor district.'] }),
  P('park', 'Ranipur Tiger Reserve', 25.2, 80.95, { lvl: 3, st: 'uttar-pradesh', tags: TR, f: ['Uttar Pradesh’s fourth tiger reserve (2022), in Chitrakoot district.'] }),
  P('park', 'Katarniaghat Wildlife Sanctuary', 28.3, 81.2, { lvl: 3, st: 'uttar-pradesh', f: ['On the Girwa river; gharials and Gangetic dolphins.'] }),
  P('park', 'National Chambal Sanctuary', 26.6, 78.6, { lvl: 2, st: ['rajasthan', 'madhya-pradesh', 'uttar-pradesh'], rel: { onRiver: ['river.chambal'] }, f: ['Tri-state sanctuary for the critically endangered gharial and the Gangetic dolphin.'] }),
  P('park', 'Valmiki Tiger Reserve', 27.35, 84.1, { lvl: 3, st: 'bihar', tags: TR, rel: { onRiver: ['river.gandak'] }, f: ['Bihar’s only tiger reserve, where the Gandak enters India.'] }),
  P('park', 'Kaziranga National Park', 26.58, 93.17, { lvl: 1, st: 'assam', tags: [...TR, ...WH], rel: { onRiver: ['river.brahmaputra'] }, f: ['Home of two-thirds of the world’s one-horned rhinoceroses; a World Heritage Site.'] }),
  P('park', 'Manas National Park', 26.72, 91.0, { lvl: 1, st: 'assam', tags: [...TR, ...WH, ...BR], rel: { onRiver: ['river.manas'] }, f: ['World Heritage Site on the Bhutan border; pygmy hog and golden langur.'] }),
  P('park', 'Nameri National Park', 26.95, 92.85, { lvl: 3, st: 'assam', tags: TR, rel: { onRiver: ['river.kameng'] }, f: ['On the Jia Bharali, adjoining Pakke.'] }),
  P('park', 'Dibru-Saikhowa National Park', 27.65, 95.4, { lvl: 3, st: 'assam', tags: BR, f: ['Riverine park known for its feral horses.'] }),
  P('park', 'Pakke Tiger Reserve', 27.05, 92.95, { lvl: 3, st: 'arunachal-pradesh', tags: TR, f: ['Known for hornbill conservation.'] }),
  P('park', 'Namdapha National Park', 27.5, 96.4, { lvl: 1, st: 'arunachal-pradesh', tags: TR, f: ['The only park with four big cats: tiger, leopard, snow leopard and clouded leopard.'] }),
  P('park', 'Keibul Lamjao National Park', 24.5, 93.83, { lvl: 1, st: 'manipur', rel: { within: 'lake.loktak-lake' }, f: ['The world’s only floating national park, on Loktak lake; last home of the sangai deer.'] }),
  P('park', 'Nokrek National Park', 25.67, 90.3, { lvl: 3, st: 'meghalaya', tags: BR, f: ['Garo hills biosphere reserve, a gene pool of wild citrus.'] }),
  P('park', 'Khangchendzonga National Park', 27.65, 88.3, { lvl: 1, st: 'sikkim', tags: [...WH, ...BR], f: ['India’s first “mixed” World Heritage Site (2016).'] }),
  P('park', 'Singalila National Park', 27.1, 88.02, { lvl: 3, st: 'west-bengal', f: ['Red panda habitat on the Singalila ridge.'] }),
  P('park', 'Buxa Tiger Reserve', 26.65, 89.6, { lvl: 3, st: 'west-bengal', tags: TR, f: ['In the Dooars on the Bhutan border.'] }),
  P('park', 'Sundarbans National Park', 21.95, 88.9, { lvl: 1, st: 'west-bengal', tags: [...TR, ...WH, ...BR, 'ramsar'], rel: { within: 'delta.sundarbans-delta' }, f: ['The largest mangrove forest in the world; Royal Bengal tigers swim between islands.'] }),
  P('park', 'Similipal National Park', 21.83, 86.33, { lvl: 2, st: 'odisha', tags: [...TR, ...BR], f: ['Known for melanistic (pseudo-melanistic) tigers; Barehipani falls.'] }),
  P('park', 'Bhitarkanika National Park', 20.7, 86.9, { lvl: 1, st: 'odisha', tags: ['ramsar'], f: ['Mangroves of the Brahmani–Baitarani delta with India’s largest saltwater crocodile population.'] }),
  P('park', 'Gahirmatha Marine Sanctuary', 20.55, 87.05, { lvl: 1, st: 'odisha', f: ['The world’s largest mass-nesting (arribada) site of Olive Ridley turtles.'] }),
  P('park', 'Palamau Tiger Reserve', 23.85, 84.2, { lvl: 3, st: 'jharkhand', tags: TR, f: ['One of the first nine Project Tiger reserves (1973); Betla National Park.'] }),
  P('park', 'Kanha National Park', 22.33, 80.61, { lvl: 1, st: 'madhya-pradesh', tags: TR, f: ['Saved the hard-ground barasingha; the setting of The Jungle Book.'] }),
  P('park', 'Bandhavgarh National Park', 23.7, 81.0, { lvl: 2, st: 'madhya-pradesh', tags: TR, f: ['One of the highest tiger densities in India; home of the first white tigers found in the wild.'] }),
  P('park', 'Pench National Park', 21.7, 79.3, { lvl: 2, st: ['madhya-pradesh', 'maharashtra'], tags: TR, rel: { onRiver: ['river.wainganga'] }, f: ['On the Pench river along the MP–Maharashtra border.'] }),
  P('park', 'Panna National Park', 24.6, 80.0, { lvl: 2, st: 'madhya-pradesh', tags: [...TR, ...BR], rel: { onRiver: ['river.ken'] }, f: ['Tigers were successfully reintroduced after local extinction (2009).'] }),
  P('park', 'Satpura National Park', 22.5, 78.3, { lvl: 3, st: 'madhya-pradesh', tags: TR, f: ['Includes Pachmarhi; part of a UNESCO biosphere reserve.'] }),
  P('park', 'Kuno National Park', 25.6, 77.3, { lvl: 1, st: 'madhya-pradesh', f: ['Where cheetahs from Namibia and South Africa were reintroduced in 2022.'] }),
  P('park', 'Tadoba-Andhari Tiger Reserve', 20.25, 79.35, { lvl: 2, st: 'maharashtra', tags: TR, f: ['Maharashtra’s oldest and largest national park.'] }),
  P('park', 'Melghat Tiger Reserve', 21.45, 77.2, { lvl: 3, st: 'maharashtra', tags: TR, f: ['In the Gavilgarh hills of the Satpura.'] }),
  P('park', 'Sanjay Gandhi National Park', 19.22, 72.91, { lvl: 3, st: 'maharashtra', f: ['A national park inside Mumbai with the Kanheri caves.'] }),
  P('park', 'Ranthambore National Park', 26.02, 76.5, { lvl: 1, st: 'rajasthan', tags: TR, f: ['Tigers among the ruins of Ranthambore fort, where the Aravalli meets the Vindhya.'] }),
  P('park', 'Sariska Tiger Reserve', 27.3, 76.4, { lvl: 2, st: 'rajasthan', tags: TR, f: ['Lost all its tigers by 2005; the first successful tiger relocation followed.'] }),
  P('park', 'Keoladeo National Park', 27.16, 77.52, { lvl: 1, st: 'rajasthan', tags: [...WH, 'ramsar'], aka: ['Bharatpur Bird Sanctuary'], f: ['A man-made wetland, once the winter home of the Siberian crane.'] }),
  P('park', 'Desert National Park', 26.5, 70.6, { lvl: 2, st: 'rajasthan', f: ['Last stronghold of the Great Indian Bustard; fossil park at Akal.'] }),
  P('park', 'Mukundra Hills Tiger Reserve', 24.8, 75.9, { lvl: 3, st: 'rajasthan', tags: TR, f: ['Between the Chambal and Kali Sindh near Kota.'] }),
  P('park', 'Gir National Park', 21.13, 70.8, { lvl: 1, st: 'gujarat', f: ['The only natural home of the Asiatic lion.'] }),
  P('park', 'Marine National Park', 22.5, 69.9, { id: 'gulf-of-kutch-marine', lvl: 2, st: 'gujarat', rel: { within: 'gulf.gulf-of-kutch' }, f: ['India’s first marine national park (1982), in the Gulf of Kutch.'] }),
  P('park', 'Wild Ass Sanctuary', 23.5, 71.3, { lvl: 2, st: 'gujarat', rel: { within: 'desert.rann-of-kutch' }, f: ['Little Rann of Kutch; last home of the Indian wild ass (khur).'] }),
  P('park', 'Velavadar Blackbuck National Park', 22.03, 72.03, { lvl: 3, st: 'gujarat', f: ['Grassland park for blackbuck on the Gulf of Khambhat.'] }),
  P('park', 'Nagarjunasagar-Srisailam Tiger Reserve', 16.1, 78.9, { lvl: 2, st: ['andhra-pradesh', 'telangana'], tags: TR, rel: { within: 'range.nallamala-hills' }, f: ['India’s largest tiger reserve, in the Nallamala hills.'] }),
  P('park', 'Indravati National Park', 19.0, 80.7, { lvl: 3, st: 'chhattisgarh', tags: TR, rel: { onRiver: ['river.indravati'] }, f: ['Home of the wild water buffalo.'] }),
  P('park', 'Achanakmar Tiger Reserve', 22.5, 81.8, { lvl: 3, st: 'chhattisgarh', tags: [...TR, ...BR], f: ['Part of the Achanakmar-Amarkantak biosphere reserve.'] }),
  P('park', 'Nagarhole National Park', 12.05, 76.15, { lvl: 2, st: 'karnataka', tags: TR, rel: { onRiver: ['river.kabini'] }, f: ['Also called Rajiv Gandhi NP; the Kabini separates it from Bandipur.'] }),
  P('park', 'Bandipur National Park', 11.67, 76.63, { lvl: 2, st: 'karnataka', tags: TR, f: ['Part of the Nilgiri biosphere reserve, with India’s largest tiger and elephant populations nearby.'] }),
  P('park', 'Kudremukh National Park', 13.2, 75.25, { lvl: 3, st: 'karnataka', f: ['Shola grasslands where the Tunga, Bhadra and Netravati rise.'] }),
  P('park', 'Mudumalai National Park', 11.57, 76.55, { lvl: 2, st: 'tamil-nadu', tags: TR, f: ['Where the Nilgiris meet the Mysore plateau; the Theppakadu elephant camp.'] }),
  P('park', 'Nilgiri Biosphere Reserve', 11.45, 76.55, { lvl: 1, st: ['tamil-nadu', 'kerala', 'karnataka'], tags: BR, f: ['India’s first biosphere reserve (1986), spanning three states.'] }),
  P('park', 'Anamalai Tiger Reserve', 10.4, 77.0, { lvl: 3, st: 'tamil-nadu', tags: TR, aka: ['Indira Gandhi Wildlife Sanctuary'], f: ['In the Anaimalai hills south of the Palghat Gap.'] }),
  P('park', 'Gulf of Mannar Biosphere Reserve', 9.15, 79.2, { lvl: 2, st: 'tamil-nadu', tags: BR, rel: { within: 'gulf.gulf-of-mannar' }, f: ['India’s first marine biosphere reserve (1989); dugongs and coral islands.'] }),
  P('park', 'Kalakkad-Mundanthurai Tiger Reserve', 8.6, 77.35, { lvl: 3, st: 'tamil-nadu', tags: TR, f: ['Part of the Agasthyamalai biosphere reserve; the Tamirabarani rises here.'] }),
  P('park', 'Periyar Tiger Reserve', 9.5, 77.2, { lvl: 1, st: 'kerala', tags: TR, rel: { onRiver: ['river.periyar'] }, f: ['Around the Mullaperiyar reservoir at Thekkady, in the Cardamom hills.'] }),
  P('park', 'Silent Valley National Park', 11.08, 76.43, { lvl: 1, st: 'kerala', f: ['Undisturbed tropical evergreen forest saved from a dam by a 1970s movement.', 'Home of the lion-tailed macaque; the Kunthipuzha flows through it.'] }),
  P('park', 'Eravikulam National Park', 10.2, 77.08, { lvl: 2, st: 'kerala', f: ['Home of the Nilgiri tahr; Anamudi lies within it; neelakurinji blooms every 12 years.'] }),
  P('park', 'Mahatma Gandhi Marine National Park', 11.55, 92.6, { lvl: 3, st: 'andaman-and-nicobar', aka: ['Wandoor'], f: ['Coral reefs off South Andaman.'] }),

  // ── Heritage sites ──────────────────────────────────────────────────────
  P('monument', 'Taj Mahal', 27.1751, 78.0421, { lvl: 1, st: 'uttar-pradesh', tags: WH, rel: { onRiver: ['river.yamuna'] }, f: ['Shah Jahan’s marble mausoleum on the Yamuna (World Heritage 1983).'] }),
  P('monument', 'Fatehpur Sikri', 27.0945, 77.6679, { lvl: 2, st: 'uttar-pradesh', tags: WH, f: ['Akbar’s red-sandstone capital with the Buland Darwaza.'] }),
  P('monument', 'Sarnath', 25.3811, 83.0214, { lvl: 1, st: 'uttar-pradesh', f: ['Where the Buddha gave his first sermon; its Ashokan lion capital is India’s national emblem.'] }),
  P('monument', 'Kushinagar', 26.7399, 83.8878, { lvl: 2, st: 'uttar-pradesh', f: ['Where the Buddha attained mahaparinirvana.'] }),
  P('monument', 'Red Fort', 28.6562, 77.241, { lvl: 1, st: 'delhi', tags: WH, f: ['Shah Jahan’s fort in Shahjahanabad; the Prime Minister speaks here on Independence Day.'] }),
  P('monument', 'Qutub Minar', 28.5245, 77.1855, { lvl: 1, st: 'delhi', tags: WH, f: ['Begun by Qutb-ud-din Aibak; the iron pillar stands in its complex.'] }),
  P('monument', 'Khajuraho', 24.8318, 79.9199, { lvl: 1, st: 'madhya-pradesh', tags: WH, f: ['Chandela temples in the Nagara style (c. 950–1050).'] }),
  P('monument', 'Sanchi Stupa', 23.4793, 77.7399, { lvl: 1, st: 'madhya-pradesh', tags: WH, f: ['Buddhist stupa begun by Ashoka.'] }),
  P('monument', 'Bhimbetka', 22.9395, 77.6124, { lvl: 1, st: 'madhya-pradesh', tags: WH, f: ['Rock shelters with paintings from the Palaeolithic onwards, in the Vindhya.'] }),
  P('monument', 'Ajanta Caves', 20.5519, 75.7033, { lvl: 1, st: 'maharashtra', tags: WH, f: ['Buddhist caves with celebrated murals (2nd century BCE–6th century CE).'] }),
  P('monument', 'Ellora Caves', 20.0268, 75.1771, { lvl: 1, st: 'maharashtra', tags: WH, f: ['Buddhist, Hindu and Jain caves, including the monolithic Kailasa temple.'] }),
  P('monument', 'Chhatrapati Shivaji Terminus', 18.9398, 72.8355, { lvl: 3, st: 'maharashtra', tags: WH, f: ['Victorian Gothic railway station in Mumbai.'] }),
  P('monument', 'Raigad Fort', 18.2335, 73.4406, { lvl: 3, st: 'maharashtra', tags: WH, f: ['Shivaji’s capital; part of the Maratha Military Landscapes (World Heritage 2025).'] }),
  P('monument', 'Hampi', 15.335, 76.46, { lvl: 1, st: 'karnataka', tags: WH, rel: { onRiver: ['river.tungabhadra'] }, f: ['Ruins of Vijayanagara on the Tungabhadra.'] }),
  P('monument', 'Pattadakal', 15.9486, 75.8166, { lvl: 2, st: 'karnataka', tags: WH, rel: { onRiver: ['river.malaprabha'] }, f: ['Chalukyan temples blending Nagara and Dravida styles.'] }),
  P('monument', 'Belur', 13.1624, 75.8653, { lvl: 3, st: 'karnataka', tags: WH, f: ['Hoysala temple; the Sacred Ensembles of the Hoysalas became World Heritage in 2023.'] }),
  P('monument', 'Konark Sun Temple', 19.8876, 86.0945, { lvl: 1, st: 'odisha', tags: WH, f: ['13th-century chariot-shaped temple to Surya, the “Black Pagoda”.'] }),
  P('monument', 'Mahabalipuram', 12.6208, 80.1945, { lvl: 1, st: 'tamil-nadu', tags: WH, aka: ['Mamallapuram'], f: ['Pallava rathas and the Shore Temple.'] }),
  P('monument', 'Brihadisvara Temple', 10.7828, 79.1318, { lvl: 1, st: 'tamil-nadu', tags: WH, f: ['Built by Rajaraja Chola I at Thanjavur; part of the Great Living Chola Temples.'] }),
  P('monument', 'Ramappa Temple', 18.2593, 79.943, { lvl: 3, st: 'telangana', tags: WH, f: ['Kakatiya temple, a World Heritage Site since 2021.'] }),
  P('monument', 'Rani ki Vav', 23.8589, 72.1016, { lvl: 2, st: 'gujarat', tags: WH, f: ['Stepwell at Patan on the Saraswati.'] }),
  P('monument', 'Dholavira', 23.8878, 70.2135, { lvl: 1, st: 'gujarat', tags: WH, f: ['Harappan city on Khadir island in the Rann of Kutch (World Heritage 2021).'] }),
  P('monument', 'Lothal', 22.522, 72.2493, { lvl: 1, st: 'gujarat', f: ['Harappan port with one of the world’s oldest known dockyards.'] }),
  P('monument', 'Rakhigarhi', 29.2867, 76.1133, { lvl: 2, st: 'haryana', f: ['The largest known Harappan site in India, in the Ghaggar basin.'] }),
  P('monument', 'Kalibangan', 29.47, 74.13, { lvl: 3, st: 'rajasthan', rel: { onRiver: ['river.ghaggar'] }, f: ['Harappan site with the earliest ploughed field.'] }),
  P('monument', 'Chittorgarh Fort', 24.8887, 74.6269, { lvl: 2, st: 'rajasthan', tags: WH, f: ['One of the Hill Forts of Rajasthan; Vijay Stambha.'] }),
  P('monument', 'Jantar Mantar', 26.9248, 75.8246, { lvl: 3, st: 'rajasthan', tags: WH, f: ['Astronomical observatory built by Sawai Jai Singh II.'] }),
  P('monument', 'Mahabodhi Temple', 24.6959, 84.9913, { lvl: 1, st: 'bihar', tags: WH, f: ['At Bodh Gaya, where the Buddha attained enlightenment.'] }),
  P('monument', 'Nalanda', 25.1357, 85.4439, { lvl: 1, st: 'bihar', tags: WH, f: ['Ruins of the ancient university (5th–12th century).'] }),
  P('monument', 'Santiniketan', 23.6793, 87.6862, { lvl: 3, st: 'west-bengal', tags: WH, f: ['Tagore’s university town, World Heritage in 2023.'] }),
  P('monument', 'Moidams of Charaideo', 26.9407, 94.819, { lvl: 3, st: 'assam', tags: WH, f: ['Ahom royal burial mounds, World Heritage in 2024.'] }),
  P('monument', 'Churches of Goa', 15.5009, 73.9116, { lvl: 3, st: 'goa', tags: WH, f: ['Basilica of Bom Jesus in Old Goa, with the relics of St Francis Xavier.'] }),
  P('monument', 'Statue of Unity', 21.838, 73.7191, { lvl: 2, st: 'gujarat', rel: { near: ['dam.sardar-sarovar-dam'] }, f: ['The world’s tallest statue (182 m), of Sardar Vallabhbhai Patel.'] }),
  P('monument', 'Kedarnath', 30.7352, 79.0669, { lvl: 2, st: 'uttarakhand', f: ['Jyotirlinga temple at the head of the Mandakini valley.'] }),
  P('monument', 'Badrinath', 30.7433, 79.4938, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['Char Dham shrine on the Alaknanda, near the Mana pass.'] }),
]
