import { P } from './dsl.mjs'

const R = ['ramsar']

/** Lakes, wetlands, confluences, waterfalls, dams and barrages. */
export default [
  // ── Lakes and lagoons ───────────────────────────────────────────────────
  P('lake', 'Wular Lake', 34.36, 74.6, { lvl: 1, st: 'jammu-and-kashmir', tags: R, rel: { onRiver: ['river.jhelum'] }, f: ['One of Asia’s largest freshwater lakes, formed by tectonic activity and fed by the Jhelum.', 'A Ramsar site (1990).'] }),
  P('lake', 'Dal Lake', 34.12, 74.87, { lvl: 1, st: 'jammu-and-kashmir', f: ['Srinagar’s lake of houseboats and floating gardens (rad).'] }),
  P('lake', 'Pangong Tso', 33.75, 78.66, { lvl: 1, st: 'ladakh', f: ['A 134 km long endorheic brackish lake at about 4,225 m, about a third in India.', 'The Line of Actual Control crosses it; site of the 2020–21 standoff.'] }),
  P('lake', 'Tso Moriri', 32.9, 78.3, { lvl: 2, st: 'ladakh', tags: R, f: ['High-altitude lake in Changthang; breeding ground of the bar-headed goose and black-necked crane.'] }),
  P('lake', 'Tso Kar', 33.3, 78.0, { lvl: 3, st: 'ladakh', tags: R, f: ['Saline lake complex of Changthang, a Ramsar site since 2020.'] }),
  P('lake', 'Chandra Taal', 32.48, 77.61, { lvl: 3, st: 'himachal-pradesh', tags: R, f: ['Crescent lake near the source of the Chandra, in Lahaul-Spiti.'] }),
  P('lake', 'Renuka Lake', 30.61, 77.46, { lvl: 3, st: 'himachal-pradesh', tags: R, f: ['The largest natural lake of Himachal Pradesh, in Sirmaur.'] }),
  P('lake', 'Nainital', 29.39, 79.45, { lvl: 3, st: 'uttarakhand', aka: ['Naini Lake'], f: ['A tectonic lake of the Kumaon; the “lake district of India”.'] }),
  P('lake', 'Loktak Lake', 24.55, 93.8, { lvl: 1, st: 'manipur', tags: [...R, 'montreux'], f: ['The largest freshwater lake of the Northeast, known for floating phumdis.', 'Keibul Lamjao, the only floating national park, lies on it; on the Montreux Record.'] }),
  P('lake', 'Chilika Lake', 19.72, 85.32, { lvl: 1, st: 'odisha', tags: R, f: ['Asia’s largest brackish-water lagoon and India’s first Ramsar site (1981).', 'Winter home of migratory birds and of Irrawaddy dolphins; Nalabana is a bird sanctuary.'] }),
  P('lake', 'Pulicat Lake', 13.55, 80.17, { lvl: 1, st: ['andhra-pradesh', 'tamil-nadu'], f: ['India’s second-largest brackish lagoon; Sriharikota separates it from the sea.'] }),
  P('lake', 'Kolleru Lake', 16.65, 81.2, { lvl: 2, st: 'andhra-pradesh', tags: R, f: ['Large freshwater lake between the Godavari and Krishna deltas.'] }),
  P('lake', 'Vembanad Lake', 9.6, 76.4, { lvl: 1, st: 'kerala', tags: R, aka: ['Vembanad-Kol'], f: ['India’s longest lake and Kerala’s largest; Kochi port lies at its mouth.', 'Scene of the Nehru Trophy boat race; the Kuttanad below-sea-level farms border it.'] }),
  P('lake', 'Ashtamudi Lake', 8.95, 76.58, { lvl: 3, st: 'kerala', tags: R, f: ['Palm-shaped estuary near Kollam, the gateway to the backwaters.'] }),
  P('lake', 'Sasthamkotta Lake', 9.03, 76.63, { lvl: 3, st: 'kerala', tags: R, f: ['The largest freshwater lake of Kerala.'] }),
  P('lake', 'Sambhar Lake', 26.96, 75.08, { lvl: 1, st: 'rajasthan', tags: R, f: ['India’s largest inland saline lake and a major source of salt.'] }),
  P('lake', 'Pushkar Lake', 26.49, 74.55, { lvl: 3, st: 'rajasthan', f: ['Sacred lake near Ajmer with the rare Brahma temple; famous camel fair.'] }),
  P('lake', 'Lonar Lake', 19.98, 76.51, { lvl: 1, st: 'maharashtra', tags: R, f: ['A saline lake in a meteorite impact crater in basalt, about 50,000 years old.'] }),
  P('lake', 'Hussain Sagar', 17.42, 78.47, { lvl: 3, st: 'telangana', f: ['A 16th-century lake between Hyderabad and Secunderabad.'] }),
  P('lake', 'Sukhna Lake', 30.74, 76.81, { lvl: 3, st: 'chandigarh', f: ['Man-made lake at the foot of the Shiwalik in Chandigarh.'] }),
  P('lake', 'Gurudongmar Lake', 28.03, 88.71, { lvl: 3, st: 'sikkim', f: ['One of the world’s highest lakes (about 5,150 m), in north Sikkim.'] }),
  P('lake', 'Tsomgo Lake', 27.37, 88.76, { lvl: 3, st: 'sikkim', aka: ['Changu Lake'], f: ['Glacial lake on the road from Gangtok to Nathu La.'] }),
  P('lake', 'Manasarovar', 30.67, 81.47, { lvl: 1, co: 'CHN', aka: ['Mapam Yumco'], f: ['Sacred freshwater lake near Mount Kailash, at about 4,590 m.', 'Pilgrims reach it by the Lipulekh and Nathu La routes.'] }),
  P('lake', 'Rakshastal', 30.7, 81.25, { lvl: 3, co: 'CHN', f: ['Saline lake west of Manasarovar; the Sutlej rises near it.'] }),

  // ── Wetlands ────────────────────────────────────────────────────────────
  P('wetland', 'Harike Wetland', 31.17, 75.0, { lvl: 1, st: 'punjab', tags: R, rel: { onRiver: ['river.sutlej', 'river.beas'] }, f: ['Formed by the Harike barrage at the confluence of the Sutlej and Beas.', 'Source of the Indira Gandhi Canal that irrigates the Thar.'] }),
  P('wetland', 'Deepor Beel', 26.12, 91.66, { lvl: 3, st: 'assam', tags: R, f: ['Permanent freshwater lake in a former Brahmaputra channel near Guwahati.'] }),
  P('wetland', 'Kanwar Taal', 25.62, 86.13, { lvl: 3, st: 'bihar', tags: R, aka: ['Kabartal'], f: ['Bihar’s first Ramsar site, an oxbow lake of the Gandak in Begusarai.'] }),
  P('wetland', 'East Kolkata Wetlands', 22.55, 88.45, { lvl: 2, st: 'west-bengal', tags: R, f: ['Treats Kolkata’s sewage naturally through fisheries and farms.'] }),
  P('wetland', 'Rudrasagar Lake', 23.5, 91.32, { lvl: 3, st: 'tripura', tags: R, f: ['Lake with the Neermahal water palace.'] }),
  P('wetland', 'Nal Sarovar', 22.8, 72.04, { lvl: 3, st: 'gujarat', tags: R, f: ['Gujarat’s largest wetland bird sanctuary.'] }),
  P('wetland', 'Hokersar', 34.1, 74.72, { lvl: 3, st: 'jammu-and-kashmir', tags: R, f: ['“Queen of wetlands” of Kashmir, near Srinagar.'] }),
  P('wetland', 'Nawabganj Bird Sanctuary', 26.61, 80.66, { lvl: 3, st: 'uttar-pradesh', tags: R, aka: ['Nawabganj Wetland'], f: ['Ramsar site between Lucknow and Kanpur.'] }),
  P('wetland', 'Sur Sarovar', 27.23, 77.84, { lvl: 3, st: 'uttar-pradesh', tags: R, aka: ['Keetham Lake'], f: ['Ramsar site near Agra on the Yamuna.'] }),
  P('wetland', 'Sultanpur National Park', 28.46, 76.89, { lvl: 3, st: 'haryana', tags: R, f: ['Bird sanctuary near Gurugram, a Ramsar site.'] }),

  // ── Confluences ─────────────────────────────────────────────────────────
  P('confluence', 'Devprayag', 30.146, 78.598, { lvl: 1, st: 'uttarakhand', rel: { onRiver: ['river.bhagirathi', 'river.alaknanda', 'river.ganga'] }, f: ['The Bhagirathi and Alaknanda meet here to form the Ganga; the last of the Panch Prayag.'] }),
  P('confluence', 'Rudraprayag', 30.285, 78.981, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Mandakini, from Kedarnath, joins the Alaknanda.'] }),
  P('confluence', 'Karnaprayag', 30.263, 79.221, { lvl: 2, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Pindar joins the Alaknanda.'] }),
  P('confluence', 'Nandprayag', 30.333, 79.328, { lvl: 3, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Nandakini joins the Alaknanda.'] }),
  P('confluence', 'Vishnuprayag', 30.565, 79.575, { lvl: 3, st: 'uttarakhand', rel: { onRiver: ['river.alaknanda'] }, f: ['The Dhauliganga joins the Alaknanda; the first of the Panch Prayag.'] }),
  P('confluence', 'Triveni Sangam', 25.424, 81.885, { lvl: 1, st: 'uttar-pradesh', rel: { onRiver: ['river.ganga', 'river.yamuna'] }, f: ['Meeting of the Ganga, the Yamuna and the mythical Saraswati at Prayagraj.', 'Site of the Kumbh and Maha Kumbh melas.'] }),
  P('confluence', 'Tandi', 32.55, 76.97, { lvl: 2, st: 'himachal-pradesh', rel: { onRiver: ['river.chenab'] }, f: ['The Chandra and Bhaga meet to form the Chenab (Chandrabhaga) in Lahaul.'] }),
  P('confluence', 'Nimmu', 34.19, 77.33, { lvl: 2, st: 'ladakh', rel: { onRiver: ['river.indus', 'river.zanskar'] }, f: ['The Zanskar joins the Indus west of Leh.'] }),
  P('confluence', 'Sadiya', 27.83, 95.65, { lvl: 2, st: 'assam', rel: { onRiver: ['river.brahmaputra', 'river.siang', 'river.dibang', 'river.lohit'] }, f: ['Near here the Siang, Dibang and Lohit unite as the Brahmaputra.'] }),
  P('confluence', 'Kaleshwaram', 18.81, 79.91, { lvl: 3, st: 'telangana', rel: { onRiver: ['river.godavari'] }, f: ['The Pranhita joins the Godavari; site of the Kaleshwaram lift irrigation project.'] }),
  P('confluence', 'Koodli', 13.87, 75.72, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.tungabhadra'] }, f: ['The Tunga and Bhadra meet to form the Tungabhadra.'] }),
  P('confluence', 'Pachnada', 26.43, 79.24, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.yamuna', 'river.chambal'] }, f: ['Five rivers meet: the Yamuna, Chambal, Sind, Kwari and Pahuj.'] }),

  // ── Waterfalls ──────────────────────────────────────────────────────────
  P('waterfall', 'Jog Falls', 14.229, 74.812, { aka: ['Gersoppa Falls'], lvl: 1, st: 'karnataka', el: 253, rel: { onRiver: ['river.sharavathi'] }, f: ['The Sharavathi plunges 253 m in four streams: Raja, Rani, Roarer and Rocket.'] }),
  P('waterfall', 'Kunchikal Falls', 13.53, 75.05, { lvl: 3, st: 'karnataka', f: ['Often cited as India’s highest waterfall (about 455 m), on the Varahi.'] }),
  P('waterfall', 'Nohkalikai Falls', 25.27, 91.69, { lvl: 2, st: 'meghalaya', f: ['India’s tallest plunge waterfall (about 340 m), near Sohra.'] }),
  P('waterfall', 'Dudhsagar Falls', 15.318, 74.314, { lvl: 2, st: 'goa', rel: { onRiver: ['river.mandovi'] }, f: ['Four-tiered falls on the Mandovi on the Goa–Karnataka border.'] }),
  P('waterfall', 'Athirappilly Falls', 10.285, 76.57, { lvl: 2, st: 'kerala', f: ['The largest waterfall of Kerala, on the Chalakudy river.'] }),
  P('waterfall', 'Chitrakote Falls', 19.206, 81.699, { lvl: 1, st: 'chhattisgarh', rel: { onRiver: ['river.indravati'] }, f: ['The widest waterfall in India, the “Niagara of India”, on the Indravati.'] }),
  P('waterfall', 'Dhuandhar Falls', 23.12, 79.8, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.narmada'] }, f: ['The Narmada’s “smoke cascade” at Bhedaghat, below the marble rocks.'] }),
  P('waterfall', 'Hundru Falls', 23.45, 85.65, { lvl: 3, st: 'jharkhand', rel: { onRiver: ['river.subarnarekha'] }, f: ['The Subarnarekha falls about 98 m near Ranchi.'] }),
  P('waterfall', 'Shivanasamudra Falls', 12.29, 77.17, { aka: ['Sivasamudram'], lvl: 2, st: 'karnataka', rel: { onRiver: ['river.kaveri'] }, f: ['Asia’s first hydroelectric station was built here in 1902.'] }),
  P('waterfall', 'Hogenakkal Falls', 12.12, 77.78, { lvl: 3, st: 'tamil-nadu', rel: { onRiver: ['river.kaveri'] }, f: ['Kaveri falls on carbonatite rocks, known for coracle rides.'] }),
  P('waterfall', 'Gokak Falls', 16.2, 74.78, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.ghataprabha'] }, f: ['Horseshoe falls on the Ghataprabha.'] }),

  // ── Dams and barrages ───────────────────────────────────────────────────
  P('dam', 'Bhakra Nangal Dam', 31.41, 76.43, { aka: ['Gobind Sagar'], lvl: 1, st: 'himachal-pradesh', rel: { onRiver: ['river.sutlej'] }, f: ['Concrete gravity dam on the Sutlej forming the Gobind Sagar reservoir.', 'Called a “temple of resurgent India” by Nehru; serves Punjab, Haryana and Rajasthan.'] }),
  P('dam', 'Pong Dam', 31.97, 75.95, { lvl: 2, st: 'himachal-pradesh', tags: R, rel: { onRiver: ['river.beas'] }, f: ['Earth-fill dam on the Beas; its reservoir, Maharana Pratap Sagar, is a Ramsar site.'] }),
  P('dam', 'Ranjit Sagar Dam', 32.44, 75.73, { lvl: 3, st: 'punjab', aka: ['Thein Dam'], rel: { onRiver: ['river.ravi'] }, f: ['On the Ravi on the Punjab–J&K border.'] }),
  P('dam', 'Salal Dam', 33.14, 74.81, { lvl: 3, st: 'jammu-and-kashmir', rel: { onRiver: ['river.chenab'] }, f: ['Run-of-the-river project on the Chenab near Reasi.'] }),
  P('dam', 'Baglihar Dam', 33.16, 75.33, { lvl: 3, st: 'jammu-and-kashmir', rel: { onRiver: ['river.chenab'] }, f: ['Chenab project whose design was examined by a neutral expert under the Indus Waters Treaty (2007).'] }),
  P('dam', 'Tehri Dam', 30.38, 78.48, { lvl: 1, st: 'uttarakhand', rel: { onRiver: ['river.bhagirathi'] }, f: ['India’s tallest dam (about 260 m), on the Bhagirathi.'] }),
  P('dam', 'Farakka Barrage', 24.8, 87.93, { lvl: 1, st: 'west-bengal', rel: { onRiver: ['river.ganga'] }, f: ['Diverts Ganga water to the Hooghly to keep Kolkata port navigable.', 'Water sharing is governed by the India–Bangladesh Ganga Treaty (1996).'] }),
  P('dam', 'Rihand Dam', 24.2, 83.01, { lvl: 2, st: 'uttar-pradesh', aka: ['Govind Ballabh Pant Sagar'], f: ['Its reservoir, Govind Ballabh Pant Sagar, is one of India’s largest artificial lakes.', 'The Singrauli power hub surrounds it.'] }),
  P('dam', 'Matatila Dam', 25.1, 78.37, { lvl: 3, st: 'uttar-pradesh', rel: { onRiver: ['river.betwa'] }, f: ['On the Betwa near Lalitpur on the UP–MP border.'] }),
  P('dam', 'Gandhi Sagar Dam', 24.7, 75.55, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.chambal'] }, f: ['First of the Chambal valley dams, upstream of Rana Pratap Sagar and Jawahar Sagar.'] }),
  P('dam', 'Indira Sagar Dam', 22.28, 76.47, { lvl: 2, st: 'madhya-pradesh', rel: { onRiver: ['river.narmada'] }, f: ['Has India’s largest reservoir by volume, on the Narmada.'] }),
  P('dam', 'Sardar Sarovar Dam', 21.83, 73.75, { lvl: 1, st: 'gujarat', rel: { onRiver: ['river.narmada'] }, f: ['Concrete gravity dam on the Narmada at Kevadia; the Statue of Unity stands downstream.', 'Centre of the Narmada Bachao Andolan.'] }),
  P('dam', 'Ukai Dam', 21.25, 73.59, { lvl: 3, st: 'gujarat', rel: { onRiver: ['river.tapi'] }, f: ['The largest reservoir of Gujarat, on the Tapi.'] }),
  P('dam', 'Hirakud Dam', 21.57, 83.87, { lvl: 1, st: 'odisha', rel: { onRiver: ['river.mahanadi'] }, f: ['One of the world’s longest earthen dams (about 25.8 km with dykes), on the Mahanadi.'] }),
  P('dam', 'Maithon Dam', 23.78, 86.8, { lvl: 3, st: 'jharkhand', f: ['Damodar Valley Corporation dam on the Barakar, a Damodar tributary.'] }),
  P('dam', 'Koyna Dam', 17.4, 73.75, { lvl: 2, st: 'maharashtra', rel: { onRiver: ['river.koyna'] }, f: ['Serves one of India’s largest hydroelectric complexes; the Shivsagar reservoir.'] }),
  P('dam', 'Almatti Dam', 16.33, 75.89, { lvl: 3, st: 'karnataka', rel: { onRiver: ['river.krishna'] }, f: ['Upper Krishna project in Karnataka.'] }),
  P('dam', 'Tungabhadra Dam', 15.27, 76.34, { lvl: 2, st: 'karnataka', rel: { onRiver: ['river.tungabhadra'] }, f: ['At Hosapete; a joint project of Karnataka and Andhra Pradesh.'] }),
  P('dam', 'Srisailam Dam', 16.09, 78.9, { lvl: 2, st: ['andhra-pradesh', 'telangana'], rel: { onRiver: ['river.krishna'] }, f: ['On the Krishna in the Nallamala hills.'] }),
  P('dam', 'Nagarjuna Sagar Dam', 16.57, 79.31, { lvl: 1, st: ['telangana', 'andhra-pradesh'], rel: { onRiver: ['river.krishna'] }, f: ['One of the world’s largest masonry dams, on the Krishna.'] }),
  P('dam', 'Polavaram Project', 17.25, 81.65, { lvl: 2, st: 'andhra-pradesh', rel: { onRiver: ['river.godavari'] }, f: ['National project on the Godavari with a link canal to the Krishna.'] }),
  P('dam', 'Krishna Raja Sagara', 12.42, 76.57, { lvl: 2, st: 'karnataka', rel: { onRiver: ['river.kaveri'] }, f: ['Dam on the Kaveri near Mysuru, designed by M. Visvesvaraya; Brindavan gardens.'] }),
  P('dam', 'Mettur Dam', 11.79, 77.8, { lvl: 2, st: 'tamil-nadu', rel: { onRiver: ['river.kaveri'] }, f: ['Its reservoir, Stanley Reservoir, is one of Tamil Nadu’s largest.'] }),
  P('dam', 'Grand Anicut', 10.83, 78.82, { lvl: 2, st: 'tamil-nadu', aka: ['Kallanai'], rel: { onRiver: ['river.kaveri'] }, f: ['Built by the Chola king Karikalan around the 2nd century CE; still in use.'] }),
  P('dam', 'Idukki Dam', 9.84, 76.97, { lvl: 2, st: 'kerala', rel: { onRiver: ['river.periyar'] }, f: ['A double-curvature arch dam on the Periyar between the Kuravan and Kurathi hills.'] }),
  P('dam', 'Mullaperiyar Dam', 9.53, 77.14, { lvl: 2, st: 'kerala', rel: { onRiver: ['river.periyar'] }, f: ['Built in 1895 in Kerala but operated by Tamil Nadu; the subject of a long dispute.'] }),

  // ── Added for previous-year papers (M7): position and facts from the cited sources (src) ──
  P('lake', 'Kaliveli Lake', 12.1197, 79.8577, { lvl: 3, f: ['Kaliveli Lake or Kazhuveli wetland, is a coastal lake and lagoon with wetlands in the Viluppuram District of Tamil Nadu state, in eastern South India.'], src: [{ title: 'Wikipedia: Kaliveli Lake', url: 'https://en.wikipedia.org/wiki/Kaliveli_Lake' }] }),
  P('lake', 'Fulhar Lake', 28.6124, 80.1165, { lvl: 3, aka: ['Phulhar Lake'], f: ['Phulhar Lake, also known as Pangaiti Phulhar Tal or Gomat Tal, is a lake located near Madhotanda in Pilibhit district of Uttar Pradesh.'], src: [{ title: 'Wikipedia: Phulhar Lake', url: 'https://en.wikipedia.org/wiki/Phulhar_Lake' }] }),
  P('lake', 'Nakki Lake', 24.5961, 72.7031, { lvl: 3, f: ['Nakki Lake is a lake situated in the Indian hill station of Mount Abu in Aravalli range.'], src: [{ title: 'Wikipedia: Nakki Lake', url: 'https://en.wikipedia.org/wiki/Nakki_Lake' }] }),
  P('lake', 'Hamirsar Lake', 23.2514, 69.6642, { lvl: 3, f: ['Hamirsar Lake is a man-made lake situated in the centre of Bhuj, the headquarters of Kutch district in the Indian state of Gujarat.'], src: [{ title: 'Wikipedia: Hamirsar Lake', url: 'https://en.wikipedia.org/wiki/Hamirsar_Lake' }] }),
  P('lake', 'Roopkund', 30.2622, 79.7317, { lvl: 3, f: ['Roopkund, locally known as Mystery Lake or Skeleton Lake, is a high-altitude glacial lake in Himalayas at an altitude of 5,020 m, between Trishul peak and Nanda Ghunti peak, in the Chamoli District of Uttarakhand state of India.'], src: [{ title: 'Wikipedia: Roopkund', url: 'https://en.wikipedia.org/wiki/Roopkund' }] }),
  P('wetland', 'Samaspur Bird Sanctuary', 25.9958, 81.3917, { lvl: 3, tags: ['ramsar'], f: ['Samaspur Bird Sanctuary is a protected area situated near Salon in Raebareli district, Uttar Pradesh, India, about 122 km from Lucknow on Lucknow-Varanasi highway.'], src: [{ title: 'Wikipedia: Samaspur Bird Sanctuary', url: 'https://en.wikipedia.org/wiki/Samaspur_Bird_Sanctuary' }] }),
  P('wetland', 'Suraha Tal', 25.85, 84.1667, { lvl: 3, aka: ['Surha Tal'], f: ['Surha Tal, locally called Suraha Taal, officially recognised as Jai Prakash Narayan Bird Sanctuary, is an oxbow lake located in Mairitar in Ballia District of Uttar Pradesh, India.'], src: [{ title: 'Wikipedia: Surha Tal', url: 'https://en.wikipedia.org/wiki/Surha_Tal' }] }),
  P('wetland', 'Surinsar-Mansar Lakes', 32.6961, 75.1468, { lvl: 3, tags: ['ramsar'], f: ['Mansar Lake is a lake located in Mansar in the Samba district in the Indian union territory of Jammu and Kashmir.'], src: [{ title: 'Wikipedia: Mansar Lake', url: 'https://en.wikipedia.org/wiki/Mansar_Lake' }] }),
  P('wetland', 'Pichavaram Mangroves', 11.4325, 79.7808, { lvl: 3, aka: ['Pichavaram'], f: ['Pichavaram is one of the villages of Parangipettai near Chidambaram in Cuddalore District, Tamil Nadu, India.', 'It is located between the Vellar estuary in the north and Coleroon estuary in the south.'], src: [{ title: 'Wikipedia: Pichavaram', url: 'https://en.wikipedia.org/wiki/Pichavaram' }] }),
  P('wetland', 'Coringa', 16.8314, 82.3367, { lvl: 3, aka: ['Coringa'], f: ['Coringa Wildlife Sanctuary is an estuary situated near Kakinada in Andhra Pradesh, India.', 'It is the third largest stretch of mangrove forests in India with 24 mangrove tree species and more than 120 bird species.'], src: [{ title: 'Wikipedia: Coringa Wildlife Sanctuary', url: 'https://en.wikipedia.org/wiki/Coringa_Wildlife_Sanctuary' }] }),
  P('waterfall', 'Duduma Falls', 18.5185, 82.4536, { lvl: 3, f: ['Duduma Waterfall is situated in the border of Koraput districts of India.'], src: [{ title: 'Wikipedia: Duduma Waterfalls', url: 'https://en.wikipedia.org/wiki/Duduma_Waterfalls' }] }),
  P('waterfall', 'Khandadhar Falls', 21.7613, 85.1172, { lvl: 3, f: ['The Khandadhar Falls is located in Nandapani, Bonaigarh in the Sundargarh district on the Indian state of Odisha.'], src: [{ title: 'Wikipedia: Khandadhar Falls (Sundargarh)', url: 'https://en.wikipedia.org/wiki/Khandadhar_Falls_(Sundargarh)' }, { title: 'Wikidata (coordinates)', url: 'https://www.wikidata.org/wiki/Q38183' }] }),
  P('dam', 'Rana Pratap Sagar Dam', 24.9178, 75.5814, { lvl: 3, aka: ['Rana Pratap Sagar'], f: ['The Rana Pratap Sagar Dam is a gravity masonry dam of 53.8 metres height built on the Chambal River at Rawatbhata in Rajasthan in India.'], src: [{ title: 'Wikipedia: Rana Pratap Sagar Dam', url: 'https://en.wikipedia.org/wiki/Rana_Pratap_Sagar_Dam' }] }),
  P('dam', 'Jawahar Sagar Dam', 25.0372, 75.678, { lvl: 3, aka: ['Jawahar Sagar'], f: ['The Jawahar Sagar Dam is the third dam in the series of Chambal Valley Projects on the Chambal River, located 29 km upstream of Kota city and 26 km downstream of Rana Pratap Sagar dam.'], src: [{ title: 'Wikipedia: Jawahar Sagar Dam', url: 'https://en.wikipedia.org/wiki/Jawahar_Sagar_Dam' }] }),
  P('dam', 'Sriram Sagar Dam', 18.9675, 78.3431, { lvl: 3, aka: ['Pochampad', 'Sriram Sagar'], f: ['The Sriram Sagar Project is also known as the Pochampadu Project is an Indian flood-flow project on the Godavari.'], src: [{ title: 'Wikipedia: Sriram Sagar Project', url: 'https://en.wikipedia.org/wiki/Sriram_Sagar_Project' }] }),
  P('dam', 'Panchet Dam', 23.6819, 86.7478, { lvl: 3, f: ['Panchet Dam was the last of the four multi-purpose dams included in the first phase of the Damodar Valley Corporation.'], src: [{ title: 'Wikipedia: Panchet Dam', url: 'https://en.wikipedia.org/wiki/Panchet_Dam' }] }),
  P('dam', 'Tilaiya Dam', 24.3239, 85.5211, { lvl: 3, f: ['Tilaiya Dam was the first of the four multi-purpose dams included in the first phase of the Damodar Valley Corporation.'], src: [{ title: 'Wikipedia: Tilaiya Dam', url: 'https://en.wikipedia.org/wiki/Tilaiya_Dam' }] }),
  P('dam', 'Parichha Dam', 25.52, 78.75, { lvl: 3, f: ['A dam on the Betwa River at Parichha, near Jhansi.', 'Parichha is a census town in Jhansi district in the Indian state of Uttar Pradesh.', 'It is located on Jhansi-Kanpur highway on the bank of Betwa River.'], src: [{ title: 'Wikipedia: Parichha', url: 'https://en.wikipedia.org/wiki/Parichha' }, { title: 'UPPSC Question Papers 1990–2026 (Uttar Pradesh Special), p. 32', url: 'pdf:UPPSC 1990-2026 Papers - Uttar Pradesh Special.pdf#p32' }] }),
  P('dam', 'Pandoh Dam', 31.6714, 77.0669, { lvl: 3, f: ['The Pandoh Dam is an embankment dam on the Beas River in Mandi district of Himachal Pradesh, India.', 'Under the Beas Project, the dam was completed in 1977 and its primary purpose is hydroelectric power generation.'], src: [{ title: 'Wikipedia: Pandoh Dam', url: 'https://en.wikipedia.org/wiki/Pandoh_Dam' }] }),
  P('dam', 'Bhadra Dam', 13.7, 75.64, { lvl: 3, f: ['The Bhadra Dam or Lakkavalli Dam, which has created the Bhadra Reservoir, is located on the Bhadra River a tributary of Tungabhadra River.'], src: [{ title: 'Wikipedia: Bhadra Dam', url: 'https://en.wikipedia.org/wiki/Bhadra_Dam' }, { title: 'Wikidata (coordinates)', url: 'https://www.wikidata.org/wiki/Q4900535' }] }),
  P('dam', 'Bhavanisagar Dam', 11.4708, 77.1139, { lvl: 3, f: ['Bhavanisagar Dam or Lower Bhavani Dam, is an earthen dam located in Erode district in the Indian state of Tamil Nadu.'], src: [{ title: 'Wikipedia: Bhavanisagar Dam', url: 'https://en.wikipedia.org/wiki/Bhavanisagar_Dam' }] }),
  P('dam', 'Malampuzha Dam', 10.8305, 76.6838, { lvl: 3, f: ['Malampuzha Dam is the largest dam and reservoir in Kerala, located near Palakkad, in the state of Kerala in South India, built post-independence by the then Madras state.'], src: [{ title: 'Wikipedia: Malampuzha Dam', url: 'https://en.wikipedia.org/wiki/Malampuzha_Dam' }] }),
  P('dam', 'Aliyar Dam', 10.4739, 76.9728, { lvl: 3, aka: ['Aliyar'], f: ['Aliyar Reservoir is a 6.48 km2 reservoir located in Aliyar village near Pollachi town in Coimbatore District, Tamil Nadu, South India.'], src: [{ title: 'Wikipedia: Aliyar Reservoir', url: 'https://en.wikipedia.org/wiki/Aliyar_Reservoir' }] }),
  P('dam', 'Isapur', 19.7643, 77.3765, { lvl: 3, aka: ['Isapur'], f: ['Isapur Dam, on Painganga River, is an earthfill dam on Painganga River near Kalamnuri in the state of Maharashtra in India.'], src: [{ title: 'Wikipedia: Isapur Dam', url: 'https://en.wikipedia.org/wiki/Isapur_Dam' }] }),
  P('wetland', 'Marakkanam', 12.2, 79.95, { lvl: 3, f: ['Marakkanam is a developing town and taluk in Villupuram district of Tamil Nadu.', 'It is well connected to the state capital Chennai and the nearby union territory of Puducherry by the East Coast Road.'], src: [{ title: 'Wikipedia: Marakkanam', url: 'https://en.wikipedia.org/wiki/Marakkanam' }] }),
  // ── end of previous-year-paper additions ──
]
