/**
 * States and Union Territories of India (28 + 8), keyed to DataMeet's `ST_NM`.
 * Capitals and formation facts are the official ones as of 2026.
 */
export const STATES = [
  { dm: 'Andhra Pradesh', id: 'andhra-pradesh', abbr: 'A.P.', name: 'Andhra Pradesh', type: 'state', capital: 'Amaravati', region: 'south', fact: 'Longest coastline among the states on the east coast; Godavari and Krishna deltas.' },
  { dm: 'Arunachal Pradesh', id: 'arunachal-pradesh', abbr: 'ARUN. P.', name: 'Arunachal Pradesh', type: 'state', capital: 'Itanagar', region: 'northeast', fact: 'Largest state of the Northeast; borders Bhutan, China and Myanmar.' },
  { dm: 'Assam', id: 'assam', abbr: 'ASSAM', name: 'Assam', type: 'state', capital: 'Dispur', region: 'northeast', fact: 'Brahmaputra and Barak valleys; home to Kaziranga and Manas.' },
  { dm: 'Bihar', id: 'bihar', abbr: 'BIHAR', name: 'Bihar', type: 'state', capital: 'Patna', region: 'north', fact: 'Middle Ganga plain; the Kosi is called the “Sorrow of Bihar”.' },
  { dm: 'Chhattisgarh', id: 'chhattisgarh', abbr: 'C.G.', name: 'Chhattisgarh', type: 'state', capital: 'Raipur', region: 'central', fact: 'Formed in 2000 from Madhya Pradesh; Mahanadi basin and Bastar plateau.' },
  { dm: 'Goa', id: 'goa', abbr: 'GOA', name: 'Goa', type: 'state', capital: 'Panaji', region: 'west', fact: 'Smallest state by area; Mandovi and Zuari estuaries.' },
  { dm: 'Gujarat', id: 'gujarat', abbr: 'GUJ.', name: 'Gujarat', type: 'state', capital: 'Gandhinagar', region: 'west', fact: 'Longest coastline of any Indian state; Rann of Kutch and Kathiawar peninsula.' },
  { dm: 'Haryana', id: 'haryana', abbr: 'HAR.', name: 'Haryana', type: 'state', capital: 'Chandigarh', region: 'north', fact: 'Formed in 1966 from Punjab; surrounds Delhi on three sides.' },
  { dm: 'Himachal Pradesh', id: 'himachal-pradesh', abbr: 'H.P.', name: 'Himachal Pradesh', type: 'state', capital: 'Shimla', region: 'north', fact: 'Western Himalaya; Sutlej, Beas, Ravi and Chenab flow through it.' },
  { dm: 'Jharkhand', id: 'jharkhand', abbr: 'JHAR.', name: 'Jharkhand', type: 'state', capital: 'Ranchi', region: 'east', fact: 'Formed in 2000 from Bihar; Chota Nagpur plateau, rich in minerals.' },
  { dm: 'Karnataka', id: 'karnataka', abbr: 'KAR.', name: 'Karnataka', type: 'state', capital: 'Bengaluru', region: 'south', fact: 'Western Ghats and Deccan plateau; Kaveri rises at Talakaveri.' },
  { dm: 'Kerala', id: 'kerala', abbr: 'KER.', name: 'Kerala', type: 'state', capital: 'Thiruvananthapuram', region: 'south', fact: 'Malabar coast backwaters; Vembanad and Ashtamudi are Ramsar sites.' },
  { dm: 'Madhya Pradesh', id: 'madhya-pradesh', abbr: 'M.P.', name: 'Madhya Pradesh', type: 'state', capital: 'Bhopal', region: 'central', fact: 'Heart of India; Narmada flows west between the Vindhya and Satpura ranges.' },
  { dm: 'Maharashtra', id: 'maharashtra', abbr: 'MAH.', name: 'Maharashtra', type: 'state', capital: 'Mumbai', region: 'west', fact: 'Deccan traps; Godavari, Krishna and Bhima rise in its Western Ghats.' },
  { dm: 'Manipur', id: 'manipur', abbr: 'MAN.', name: 'Manipur', type: 'state', capital: 'Imphal', region: 'northeast', fact: 'Loktak lake with floating phumdis and Keibul Lamjao, the only floating national park.' },
  { dm: 'Meghalaya', id: 'meghalaya', abbr: 'MEG.', name: 'Meghalaya', type: 'state', capital: 'Shillong', region: 'northeast', fact: 'Garo, Khasi and Jaintia hills; Mawsynram and Cherrapunji are among the wettest places.' },
  { dm: 'Mizoram', id: 'mizoram', abbr: 'MIZ.', name: 'Mizoram', type: 'state', capital: 'Aizawl', region: 'northeast', fact: 'Lushai hills; borders Myanmar and Bangladesh.' },
  { dm: 'Nagaland', id: 'nagaland', abbr: 'NAG.', name: 'Nagaland', type: 'state', capital: 'Kohima', region: 'northeast', fact: 'Naga hills; Saramati is its highest peak.' },
  { dm: 'Odisha', id: 'odisha', abbr: 'ODISHA', name: 'Odisha', type: 'state', capital: 'Bhubaneswar', region: 'east', fact: 'Mahanadi delta; Chilika is Asia’s largest brackish-water lagoon.' },
  { dm: 'Punjab', id: 'punjab', abbr: 'PUN.', name: 'Punjab', type: 'state', capital: 'Chandigarh', region: 'north', fact: 'Land of five rivers; Sutlej, Beas and Ravi flow through it.' },
  { dm: 'Rajasthan', id: 'rajasthan', abbr: 'RAJ.', name: 'Rajasthan', type: 'state', capital: 'Jaipur', region: 'west', fact: 'Largest state by area; the Aravalli range divides the Thar desert from the east.' },
  { dm: 'Sikkim', id: 'sikkim', abbr: 'SK.', name: 'Sikkim', type: 'state', capital: 'Gangtok', region: 'northeast', fact: 'Eastern Himalaya; Kangchenjunga and the Nathu La pass to Tibet.' },
  { dm: 'Tamil Nadu', id: 'tamil-nadu', abbr: 'T.N.', name: 'Tamil Nadu', type: 'state', capital: 'Chennai', region: 'south', fact: 'Coromandel coast; Kaveri delta and the Nilgiri hills.' },
  { dm: 'Telangana', id: 'telangana', abbr: 'TEL.', name: 'Telangana', type: 'state', capital: 'Hyderabad', region: 'south', fact: 'Formed in 2014 from Andhra Pradesh; on the Deccan plateau.' },
  { dm: 'Tripura', id: 'tripura', abbr: 'TRI.', name: 'Tripura', type: 'state', capital: 'Agartala', region: 'northeast', fact: 'Surrounded by Bangladesh on three sides.' },
  { dm: 'Uttar Pradesh', id: 'uttar-pradesh', abbr: 'U.P.', name: 'Uttar Pradesh', type: 'state', capital: 'Lucknow', region: 'north', fact: 'Most populous state; the Ganga–Yamuna doab and the Terai.' },
  { dm: 'Uttarakhand', id: 'uttarakhand', abbr: 'UK.', name: 'Uttarakhand', type: 'state', capital: 'Dehradun', region: 'north', fact: 'Formed in 2000 from Uttar Pradesh; source of the Ganga and Yamuna.' },
  { dm: 'West Bengal', id: 'west-bengal', abbr: 'W.B.', name: 'West Bengal', type: 'state', capital: 'Kolkata', region: 'east', fact: 'From the Darjeeling Himalaya to the Sundarbans delta.' },
  { dm: 'Andaman & Nicobar', id: 'andaman-and-nicobar', abbr: 'A&N', name: 'Andaman and Nicobar Islands', type: 'ut', capital: 'Sri Vijaya Puram (Port Blair)', region: 'islands', fact: 'Separated by the Ten Degree Channel; Barren Island is India’s only active volcano.' },
  { dm: 'Chandigarh', id: 'chandigarh', abbr: 'CH.', name: 'Chandigarh', type: 'ut', capital: 'Chandigarh', region: 'north', fact: 'Planned city by Le Corbusier; capital of both Punjab and Haryana.' },
  { dm: 'Dadra and Nagar Haveli and Daman and Diu', id: 'dnh-and-dd', abbr: 'DNH&DD', name: 'Dadra and Nagar Haveli and Daman and Diu', type: 'ut', capital: 'Daman', region: 'west', fact: 'Two UTs merged into one in January 2020.' },
  { dm: 'Delhi', id: 'delhi', abbr: 'DELHI', name: 'Delhi', type: 'ut', capital: 'New Delhi', region: 'north', fact: 'National Capital Territory on the Yamuna.' },
  { dm: 'Jammu & Kashmir', id: 'jammu-and-kashmir', abbr: 'J&K', name: 'Jammu and Kashmir', type: 'ut', capital: 'Srinagar (summer) / Jammu (winter)', region: 'north', fact: 'Became a Union Territory in 2019; Jhelum flows through the Kashmir valley.' },
  { dm: 'Ladakh', id: 'ladakh', abbr: 'LADAKH', name: 'Ladakh', type: 'ut', capital: 'Leh', region: 'north', fact: 'Union Territory since 2019; cold desert between the Karakoram and the Great Himalaya.' },
  { dm: 'Lakshadweep', id: 'lakshadweep', abbr: 'LAK.', name: 'Lakshadweep', type: 'ut', capital: 'Kavaratti', region: 'islands', fact: 'Coral atolls in the Arabian Sea; smallest UT by area.' },
  { dm: 'Puducherry', id: 'puducherry', abbr: 'PUD.', name: 'Puducherry', type: 'ut', capital: 'Puducherry', region: 'south', fact: 'Four enclaves: Puducherry, Karaikal, Mahe and Yanam.' },
]
