import { P } from './dsl.mjs'

/** World physical geography (sheet: world). Countries are ISO 3166 alpha-3 codes. */
export default [
  // ── Oceans and seas ─────────────────────────────────────────────────────
  P('sea', 'Pacific Ocean', 5, -150, { lvl: 1, f: ['The largest and deepest ocean, covering about a third of the Earth.', 'Ringed by the “Ring of Fire” of volcanoes and trenches.'] }),
  P('sea', 'Atlantic Ocean', 15, -40, { lvl: 1, f: ['The second-largest ocean; the Mid-Atlantic Ridge runs down its centre.'] }),
  P('sea', 'Indian Ocean', -20, 80, { lvl: 1, f: ['The third-largest ocean and the only one named after a country.', 'Its monsoon winds reverse with the seasons.'] }),
  P('sea', 'Mediterranean Sea', 35, 18, { lvl: 1, f: ['Nearly enclosed sea linked to the Atlantic by the Strait of Gibraltar and to the Red Sea by the Suez Canal.'] }),
  P('sea', 'Red Sea', 20, 38.5, { lvl: 1, f: ['A young rift sea between Africa and Arabia, among the saltiest seas.'] }),
  P('sea', 'Black Sea', 43.2, 34, { lvl: 2, f: ['Linked to the Mediterranean through the Bosporus and Dardanelles; the Danube drains into it.'] }),
  P('sea', 'South China Sea', 12, 114, { lvl: 1, f: ['Contested sea with the Spratly and Paracel islands; a key trade route.'] }),
  P('sea', 'Caribbean Sea', 15, -75, { lvl: 2, f: ['Bounded by the Greater and Lesser Antilles and Central America.'] }),
  P('sea', 'North Sea', 56, 3, { lvl: 2, f: ['Shallow sea with the Dogger Bank fishing ground and oil and gas fields.'] }),
  P('sea', 'Baltic Sea', 58, 20, { lvl: 2, f: ['Brackish, nearly enclosed sea of northern Europe.'] }),
  P('sea', 'Sargasso Sea', 30, -60, { lvl: 2, f: ['The only sea with no coastline, bounded by ocean currents; named after sargassum seaweed.'] }),
  P('sea', 'Mariana Trench', 11.35, 142.2, { lvl: 1, sub: 'Ocean trench', f: ['The deepest part of the oceans; the Challenger Deep is about 10,935 m deep.'] }),
  P('gulf', 'Persian Gulf', 27, 51, { lvl: 1, f: ['Holds about half the world’s proven oil reserves; exits through the Strait of Hormuz.'] }),
  P('gulf', 'Gulf of Aden', 12.5, 48, { lvl: 2, f: ['Between Yemen and Somalia; linked to the Red Sea by the Bab-el-Mandeb.'] }),
  P('gulf', 'Gulf of Mexico', 25, -90, { lvl: 1, f: ['The Gulf Stream begins here; the Mississippi drains into it.'] }),
  P('gulf', 'Gulf of Guinea', 2, 4, { lvl: 2, f: ['The Equator and the Prime Meridian cross in it.'] }),
  P('gulf', 'Hudson Bay', 60, -85, { lvl: 2, f: ['Huge inland sea of Canada, frozen for much of the year.'] }),
  P('gulf', 'Gulf of Oman', 24.5, 58.5, { lvl: 3, f: ['Links the Arabian Sea with the Strait of Hormuz.'] }),
  P('gulf', 'Gulf of Thailand', 9.5, 102, { lvl: 3, f: ['Shallow arm of the South China Sea.'] }),
  P('gulf', 'Bay of Biscay', 45, -4, { lvl: 3, f: ['Stormy bay between France and Spain.'] }),

  // ── Straits and canals ──────────────────────────────────────────────────
  P('strait', 'Strait of Hormuz', 26.57, 56.25, { lvl: 1, co: ['IRN', 'OMN'], rel: { connects: ['gulf.persian-gulf', 'gulf.gulf-of-oman'] }, f: ['The world’s most important oil chokepoint, between Iran and Oman’s Musandam.'] }),
  P('strait', 'Strait of Malacca', 3.5, 100.5, { lvl: 1, co: ['MYS', 'IDN'], f: ['Busiest shipping lane between the Indian and Pacific Oceans, between Malaysia and Sumatra.'] }),
  P('strait', 'Bab-el-Mandeb', 12.58, 43.33, { lvl: 1, co: ['YEM', 'DJI'], rel: { connects: ['sea.red-sea', 'gulf.gulf-of-aden'] }, f: ['“Gate of Tears” between Yemen and Djibouti, linking the Red Sea to the Gulf of Aden.'] }),
  P('strait', 'Strait of Gibraltar', 35.95, -5.6, { lvl: 1, co: ['ESP', 'MAR'], rel: { connects: ['sea.mediterranean-sea', 'sea.atlantic-ocean'] }, f: ['Separates Europe (Spain) from Africa (Morocco); about 14 km wide.'] }),
  P('strait', 'Bosporus', 41.12, 29.07, { lvl: 1, co: 'TUR', rel: { connects: ['sea.black-sea', 'sea.mediterranean-sea'] }, f: ['Divides Istanbul between Europe and Asia; links the Black Sea with the Sea of Marmara.'] }),
  P('strait', 'Dardanelles', 40.2, 26.4, { lvl: 2, co: 'TUR', f: ['Links the Sea of Marmara with the Aegean; the Gallipoli campaign (1915).'] }),
  P('strait', 'Bering Strait', 65.75, -168.9, { lvl: 1, co: ['RUS', 'USA'], f: ['Separates Asia from North America; the International Date Line runs through it.'] }),
  P('strait', 'Strait of Dover', 51.0, 1.45, { lvl: 2, co: ['GBR', 'FRA'], f: ['Narrowest part of the English Channel; the Channel Tunnel runs beneath it.'] }),
  P('strait', 'Sunda Strait', -6.0, 105.8, { lvl: 2, co: 'IDN', f: ['Between Java and Sumatra; the Krakatoa volcano lies in it.'] }),
  P('strait', 'Lombok Strait', -8.5, 115.8, { lvl: 3, co: 'IDN', f: ['Deep strait along the Wallace Line between Bali and Lombok.'] }),
  P('strait', 'Taiwan Strait', 24.5, 119.5, { lvl: 2, co: ['CHN', 'TWN'], f: ['Separates Taiwan from mainland China.'] }),
  P('strait', 'Strait of Magellan', -53.5, -70.8, { lvl: 2, co: 'CHL', f: ['Navigable route around South America, north of Tierra del Fuego.'] }),
  P('strait', 'Drake Passage', -58, -65, { lvl: 2, f: ['Between Cape Horn and Antarctica; the Antarctic Circumpolar Current flows through it.'] }),
  P('strait', 'Mozambique Channel', -18, 41.5, { lvl: 2, co: ['MOZ', 'MDG'], f: ['Separates Madagascar from mainland Africa.'] }),
  P('strait', 'Cook Strait', -41.2, 174.5, { lvl: 3, co: 'NZL', f: ['Separates the North and South Islands of New Zealand.'] }),
  P('strait', 'Bass Strait', -39.5, 146, { lvl: 3, co: 'AUS', f: ['Separates Tasmania from mainland Australia.'] }),
  P('canal', 'Suez Canal', 30.6, 32.33, { lvl: 1, co: 'EGY', rel: { connects: ['sea.mediterranean-sea', 'sea.red-sea'] }, f: ['Opened in 1869; a sea-level canal with no locks linking the Mediterranean and the Red Sea.', 'Shortens the Europe–India voyage by avoiding the Cape of Good Hope.'] }),
  P('canal', 'Panama Canal', 9.08, -79.68, { lvl: 1, co: 'PAN', f: ['Opened in 1914; uses locks and the Gatun lake to link the Atlantic and Pacific.'] }),
  P('canal', 'Kiel Canal', 54.2, 9.6, { lvl: 3, co: 'DEU', f: ['Links the North Sea with the Baltic across Germany; one of the busiest artificial waterways.'] }),

  // ── Mountains ───────────────────────────────────────────────────────────
  P('range', 'Himalaya', 28.5, 84.0, { lvl: 1, co: ['IND', 'NPL', 'BTN', 'CHN', 'PAK'], f: ['The world’s highest range, raised by the collision of India with Asia.'] }),
  P('range', 'Alps', 46.5, 10.0, { lvl: 1, co: ['FRA', 'CHE', 'ITA', 'AUT', 'DEU'], f: ['Young fold mountains of Europe; Mont Blanc is the highest peak.'] }),
  P('range', 'Andes', -20, -67, { lvl: 1, co: ['VEN', 'COL', 'ECU', 'PER', 'BOL', 'CHL', 'ARG'], f: ['The world’s longest continental range (about 7,000 km); Aconcagua is its highest peak.'] }),
  P('range', 'Rocky Mountains', 45, -112, { lvl: 1, co: ['USA', 'CAN'], f: ['Western North American range forming the continental divide.'] }),
  P('range', 'Atlas Mountains', 31.5, -6, { lvl: 2, co: ['MAR', 'DZA', 'TUN'], f: ['Fold mountains of north-west Africa separating the Mediterranean coast from the Sahara.'] }),
  P('range', 'Ural Mountains', 60, 59.5, { lvl: 1, co: 'RUS', f: ['Old range traditionally dividing Europe from Asia.'] }),
  P('range', 'Caucasus', 42.5, 44.5, { lvl: 2, co: ['RUS', 'GEO', 'AZE', 'ARM'], f: ['Between the Black and Caspian seas; Elbrus is the highest peak.'] }),
  P('range', 'Appalachian Mountains', 38, -80, { lvl: 2, co: 'USA', f: ['Old, worn-down range of eastern North America rich in coal.'] }),
  P('range', 'Great Dividing Range', -25, 148, { lvl: 2, co: 'AUS', f: ['Eastern Australian range separating the coast from the interior.'] }),
  P('range', 'Drakensberg', -29.5, 29.5, { lvl: 3, co: ['ZAF', 'LSO'], f: ['Basalt escarpment of southern Africa.'] }),
  P('range', 'Hindu Kush', 35.5, 70.5, { lvl: 1, co: ['AFG', 'PAK'], f: ['Western extension of the Himalayan system into Afghanistan.'] }),
  P('range', 'Tian Shan', 42, 80, { lvl: 2, co: ['CHN', 'KGZ', 'KAZ'], f: ['“Celestial mountains” of Central Asia.'] }),
  P('range', 'Kunlun Mountains', 36, 85, { lvl: 3, co: 'CHN', f: ['Northern rim of the Tibetan plateau.'] }),
  P('range', 'Pamir', 38.5, 73.5, { lvl: 1, co: ['TJK', 'AFG', 'CHN'], aka: ['Pamir Knot'], f: ['The “roof of the world”, a knot where the Himalaya, Karakoram, Hindu Kush, Kunlun and Tian Shan meet.'] }),
  P('range', 'Pyrenees', 42.7, 0.5, { lvl: 3, co: ['ESP', 'FRA', 'AND'], f: ['Separates the Iberian peninsula from France.'] }),
  P('range', 'Zagros Mountains', 32, 50, { lvl: 3, co: ['IRN', 'IRQ'], f: ['Fold mountains of Iran with rich oil fields at their foot.'] }),
  P('range', 'Carpathian Mountains', 47.5, 25, { lvl: 3, co: ['ROU', 'UKR', 'SVK', 'POL'], f: ['Arc-shaped range of central and eastern Europe.'] }),
  P('peak', 'Aconcagua', -32.653, -70.011, { lvl: 1, el: 6961, co: 'ARG', f: ['The highest peak outside Asia, in the Andes.'] }),
  P('peak', 'Denali', 63.069, -151.007, { lvl: 1, el: 6190, co: 'USA', aka: ['Mount McKinley'], f: ['The highest peak of North America, in Alaska.'] }),
  P('peak', 'Kilimanjaro', -3.0674, 37.3556, { lvl: 1, el: 5895, co: 'TZA', f: ['Africa’s highest peak, a dormant volcano near the Equator with shrinking glaciers.'] }),
  P('peak', 'Mount Elbrus', 43.355, 42.439, { lvl: 1, el: 5642, co: 'RUS', f: ['The highest peak of Europe, a dormant volcano in the Caucasus.'] }),
  P('peak', 'Mont Blanc', 45.833, 6.865, { lvl: 2, el: 4806, co: ['FRA', 'ITA'], f: ['The highest peak of the Alps.'] }),
  P('peak', 'Puncak Jaya', -4.078, 137.158, { lvl: 3, el: 4884, co: 'IDN', f: ['The highest peak of Oceania, on New Guinea.'] }),
  P('peak', 'Mount Kosciuszko', -36.456, 148.263, { lvl: 3, el: 2228, co: 'AUS', f: ['The highest peak of mainland Australia.'] }),
  P('peak', 'Mount Kenya', -0.152, 37.308, { lvl: 3, el: 5199, co: 'KEN', f: ['Africa’s second-highest peak, an extinct volcano on the Equator.'] }),
  P('peak', 'Chimborazo', -1.469, -78.817, { lvl: 3, el: 6263, co: 'ECU', f: ['Its summit is the point farthest from the Earth’s centre, because of the equatorial bulge.'] }),
  P('volcano', 'Mount Fuji', 35.361, 138.727, { lvl: 2, el: 3776, co: 'JPN', f: ['Japan’s highest peak, an active stratovolcano.'] }),
  P('volcano', 'Mount Etna', 37.751, 14.993, { lvl: 2, el: 3357, co: 'ITA', f: ['Europe’s most active volcano, on Sicily.'] }),
  P('volcano', 'Mount Vesuvius', 40.821, 14.426, { lvl: 2, el: 1281, co: 'ITA', f: ['Buried Pompeii and Herculaneum in 79 CE.'] }),
  P('volcano', 'Krakatoa', -6.102, 105.423, { lvl: 2, co: 'IDN', f: ['Its 1883 eruption was heard thousands of kilometres away.'] }),
  P('volcano', 'Mauna Loa', 19.475, -155.608, { lvl: 3, el: 4169, co: 'USA', f: ['The largest active volcano on Earth by volume, a shield volcano over the Hawaii hotspot.'] }),
  P('volcano', 'Cotopaxi', -0.681, -78.438, { lvl: 3, el: 5897, co: 'ECU', f: ['One of the world’s highest active volcanoes.'] }),

  // ── Rivers ──────────────────────────────────────────────────────────────
  P('river', 'Nile', 16.0, 32.6, { lvl: 1, co: ['UGA', 'SSD', 'SDN', 'EGY'], f: ['Often listed as the world’s longest river (about 6,650 km).', 'The White Nile (from Lake Victoria) and the Blue Nile (from Lake Tana) meet at Khartoum.', 'The Aswan High Dam forms Lake Nasser.'] }),
  P('river', 'Amazon', -3.4, -60, { lvl: 1, geom: 'river:amazonas', co: ['PER', 'COL', 'BRA'], f: ['The largest river by discharge, about a fifth of all river water reaching the oceans.', 'Rises in the Peruvian Andes and crosses Brazil to the Atlantic.'] }),
  P('river', 'Yangtze', 30.5, 112, { lvl: 1, co: 'CHN', aka: ['Chang Jiang'], f: ['Asia’s longest river; the Three Gorges Dam is the world’s largest power station.'] }),
  P('river', 'Huang He', 36.0, 110.5, { lvl: 1, geom: 'river:huang', co: 'CHN', aka: ['Yellow River'], f: ['Carries loess silt; called “China’s sorrow” for its floods.'] }),
  P('river', 'Mississippi', 35, -90, { lvl: 1, co: 'USA', f: ['With the Missouri, North America’s largest river system; ends in a bird’s-foot delta.'] }),
  P('river', 'Congo', -1.5, 18, { lvl: 1, co: ['COD', 'COG'], f: ['Crosses the Equator twice; the deepest river in the world.'] }),
  P('river', 'Niger', 14.0, -4.0, { lvl: 2, co: ['GIN', 'MLI', 'NER', 'NGA'], f: ['Flows in a great boomerang past Timbuktu; forms an inland delta in Mali.'] }),
  P('river', 'Zambezi', -16.0, 28.5, { lvl: 2, co: ['ZMB', 'ZWE', 'MOZ'], f: ['Victoria Falls and the Kariba and Cahora Bassa dams are on it.'] }),
  P('river', 'Mekong', 16, 105, { lvl: 1, co: ['CHN', 'MMR', 'LAO', 'THA', 'KHM', 'VNM'], f: ['Flows through six countries; the Tonle Sap reverses its flow in the monsoon.'] }),
  P('river', 'Danube', 45.3, 24.0, { lvl: 1, co: ['DEU', 'AUT', 'SVK', 'HUN', 'HRV', 'SRB', 'BGR', 'ROU', 'MDA', 'UKR'], f: ['Flows through ten countries, more than any other river; Vienna, Budapest and Belgrade stand on it.'] }),
  P('river', 'Rhine', 50.5, 7.6, { lvl: 2, co: ['CHE', 'DEU', 'FRA', 'NLD'], f: ['Europe’s busiest waterway, from the Swiss Alps to Rotterdam.'] }),
  P('river', 'Volga', 53, 48, { lvl: 1, co: 'RUS', f: ['Europe’s longest river; drains into the Caspian Sea.'] }),
  P('river', 'Ob', 60, 70, { lvl: 3, co: 'RUS', f: ['Siberian river flowing north to the Kara Sea.'] }),
  P('river', 'Yenisei', 62, 89, { lvl: 2, geom: 'river:yenisey', co: ['MNG', 'RUS'], f: ['The largest river system flowing into the Arctic Ocean.'] }),
  P('river', 'Lena', 64, 127, { lvl: 3, co: 'RUS', f: ['Siberian river flowing through permafrost to the Laptev Sea.'] }),
  P('river', 'Amur', 50.5, 130, { lvl: 3, co: ['RUS', 'CHN'], f: ['Forms much of the Russia–China border.'] }),
  P('river', 'Tigris', 34.5, 43.6, { lvl: 1, co: ['TUR', 'SYR', 'IRQ'], f: ['With the Euphrates it enclosed Mesopotamia; Baghdad stands on it.'] }),
  P('river', 'Euphrates', 34.8, 40.5, { lvl: 1, co: ['TUR', 'SYR', 'IRQ'], f: ['Joins the Tigris to form the Shatt al-Arab, which enters the Persian Gulf.'] }),
  P('river', 'Murray', -34.3, 142, { lvl: 2, co: 'AUS', f: ['Australia’s longest river; the Murray–Darling basin is its farm belt.'] }),
  P('river', 'Orinoco', 7.5, -65, { lvl: 3, co: ['VEN', 'COL'], f: ['Drains the Llanos of Venezuela and Colombia.'] }),
  P('river', 'Paraná', -27.5, -58.5, { id: 'parana', lvl: 2, co: ['BRA', 'PRY', 'ARG'], f: ['The Itaipu dam on the Brazil–Paraguay border is one of the world’s largest.'] }),
  P('river', 'St. Lawrence', 46.8, -71.2, { id: 'st-lawrence', lvl: 3, co: ['CAN', 'USA'], f: ['Outlet of the Great Lakes; the St. Lawrence Seaway lets ships reach the interior.'] }),
  P('river', 'Colorado', 36.1, -112.1, { lvl: 3, co: ['USA', 'MEX'], f: ['Carved the Grand Canyon; the Hoover Dam forms Lake Mead.'] }),
  P('river', 'Mackenzie', 64, -124, { lvl: 3, co: 'CAN', f: ['Canada’s longest river, flowing to the Arctic Ocean.'] }),
  P('river', 'Limpopo', -22.3, 31.2, { lvl: 3, co: ['ZAF', 'BWA', 'ZWE', 'MOZ'], f: ['Crosses the Tropic of Capricorn twice.'] }),
  P('river', 'Jordan', 32.0, 35.55, { lvl: 3, co: ['JOR', 'ISR'], f: ['Flows through the Sea of Galilee into the Dead Sea.'] }),

  // ── Lakes ───────────────────────────────────────────────────────────────
  P('lake', 'Caspian Sea', 41.5, 50.5, { lvl: 1, co: ['RUS', 'KAZ', 'TKM', 'IRN', 'AZE'], f: ['The world’s largest lake by area, saline and below sea level.'] }),
  P('lake', 'Lake Superior', 47.7, -87.5, { lvl: 1, co: ['USA', 'CAN'], f: ['The largest freshwater lake by area; one of the Great Lakes.'] }),
  P('lake', 'Lake Baikal', 53.5, 108, { lvl: 1, co: 'RUS', f: ['The world’s deepest (about 1,640 m) and oldest lake; holds about a fifth of unfrozen fresh surface water.'] }),
  P('lake', 'Lake Victoria', -1, 33, { lvl: 1, co: ['UGA', 'KEN', 'TZA'], f: ['Africa’s largest lake; source of the White Nile.'] }),
  P('lake', 'Lake Tanganyika', -6, 29.5, { lvl: 2, co: ['TZA', 'COD', 'BDI', 'ZMB'], f: ['The world’s longest freshwater lake, in the Great Rift Valley.'] }),
  P('lake', 'Lake Malawi', -12, 34.5, { lvl: 3, co: ['MWI', 'MOZ', 'TZA'], f: ['Rift valley lake with hundreds of endemic cichlid fish.'] }),
  P('lake', 'Lake Titicaca', -15.9, -69.3, { lvl: 1, co: ['PER', 'BOL'], f: ['The highest navigable lake (about 3,810 m), on the Altiplano.'] }),
  P('lake', 'Aral Sea', 45, 60, { lvl: 1, co: ['KAZ', 'UZB'], f: ['Shrank drastically after the Amu Darya and Syr Darya were diverted for cotton.'] }),
  P('lake', 'Dead Sea', 31.5, 35.5, { lvl: 1, co: ['JOR', 'ISR', 'PSE'], f: ['Its shore is the lowest land on Earth, about 430 m below sea level.'] }),
  P('lake', 'Great Salt Lake', 41.1, -112.5, { lvl: 3, co: 'USA', f: ['Saline remnant of the ice-age Lake Bonneville.'] }),
  P('lake', 'Lake Chad', 13.3, 14.1, { lvl: 2, co: ['TCD', 'NGA', 'NER', 'CMR'], f: ['A shallow Sahel lake that has shrunk dramatically since the 1960s.'] }),
  P('lake', 'Lake Ladoga', 61, 31.5, { lvl: 3, co: 'RUS', f: ['Europe’s largest lake, near St Petersburg.'] }),
  P('lake', 'Lake Balkhash', 46.5, 74.5, { lvl: 3, co: 'KAZ', f: ['Freshwater in the west and saline in the east.'] }),
  P('lake', 'Lake Eyre', -28.4, 137.3, { lvl: 3, co: 'AUS', aka: ['Kati Thanda'], f: ['Australia’s lowest point; usually a dry salt pan.'] }),

  // ── Deserts, plateaus and grasslands ────────────────────────────────────
  P('desert', 'Sahara', 23, 13, { lvl: 1, f: ['The largest hot desert, covering most of North Africa.'] }),
  P('desert', 'Arabian Desert', 21, 50, { lvl: 1, aka: ['Rub’ al Khali'], f: ['Its Rub’ al Khali (Empty Quarter) is the largest continuous sand desert.'] }),
  P('desert', 'Gobi Desert', 43, 105, { lvl: 1, co: ['MNG', 'CHN'], f: ['A cold rain-shadow desert of Mongolia and China.'] }),
  P('desert', 'Kalahari Desert', -23, 22, { lvl: 2, co: ['BWA', 'NAM', 'ZAF'], f: ['A semi-arid sandy savanna; home of the San people.'] }),
  P('desert', 'Namib Desert', -24, 15.2, { lvl: 2, co: 'NAM', f: ['Coastal fog desert, among the oldest on Earth, caused by the cold Benguela current.'] }),
  P('desert', 'Atacama Desert', -24.5, -69.25, { lvl: 1, co: 'CHL', f: ['The driest non-polar desert, caused by the cold Humboldt current; rich in copper and nitrates.'] }),
  P('desert', 'Great Victoria Desert', -28.5, 127, { lvl: 3, co: 'AUS', f: ['Australia’s largest desert.'] }),
  P('desert', 'Taklamakan Desert', 38.9, 82, { lvl: 2, co: 'CHN', f: ['Sandy desert of the Tarim basin, skirted by the Silk Road oases.'] }),
  P('desert', 'Patagonian Desert', -45, -69, { lvl: 3, co: 'ARG', f: ['Cold rain-shadow desert east of the Andes.'] }),
  P('plateau', 'Tibetan Plateau', 32, 88, { lvl: 1, co: 'CHN', f: ['The highest and largest plateau, average height over 4,500 m; the “Third Pole”.'] }),
  P('plateau', 'Ethiopian Highlands', 10, 39, { lvl: 2, co: 'ETH', f: ['The “roof of Africa”; the Blue Nile rises at Lake Tana.'] }),
  P('plateau', 'Altiplano', -18, -67.5, { lvl: 2, co: ['BOL', 'PER'], f: ['High Andean plateau with Lake Titicaca and the Uyuni salt flat.'] }),
  P('plateau', 'Anatolian Plateau', 39, 33, { lvl: 3, co: 'TUR', f: ['Central plateau of Türkiye.'] }),
  P('plateau', 'Colorado Plateau', 37, -110.5, { lvl: 3, co: 'USA', f: ['Layered plateau cut by the Grand Canyon.'] }),
  P('plateau', 'Brazilian Highlands', -15, -47, { lvl: 3, co: 'BRA', f: ['Ancient plateau of eastern Brazil with the Cerrado savanna.'] }),
  P('grassland', 'Prairies', 45, -100, { lvl: 1, co: ['USA', 'CAN'], f: ['Temperate grasslands of North America, the “wheat basket of the world”.'] }),
  P('grassland', 'Pampas', -35, -62, { lvl: 1, co: 'ARG', f: ['Temperate grasslands of Argentina known for cattle and wheat.'] }),
  P('grassland', 'Steppes', 48, 65, { lvl: 1, co: ['KAZ', 'RUS', 'UKR'], f: ['Temperate grasslands of Eurasia.'] }),
  P('grassland', 'Veld', -27, 27, { lvl: 1, co: 'ZAF', aka: ['Veldt'], f: ['Temperate grasslands of South Africa.'] }),
  P('grassland', 'Downs', -24, 144, { lvl: 2, co: 'AUS', f: ['Temperate grasslands of Australia, famed for merino sheep.'] }),
  P('grassland', 'Llanos', 7, -69, { lvl: 2, co: ['VEN', 'COL'], f: ['Tropical grasslands of the Orinoco basin.'] }),
  P('grassland', 'Campos', -20, -48, { lvl: 3, co: 'BRA', f: ['Tropical grasslands of the Brazilian Highlands.'] }),
  P('grassland', 'Serengeti', -2.33, 34.83, { lvl: 2, co: 'TZA', f: ['Savanna famous for the annual wildebeest migration.'] }),

  // ── Regions, valleys and reefs ──────────────────────────────────────────
  P('valley', 'Great Rift Valley', -3, 36, { lvl: 1, co: ['ETH', 'KEN', 'TZA'], f: ['A continental rift from the Red Sea to Mozambique, with deep lakes and volcanoes.'] }),
  P('valley', 'Grand Canyon', 36.1, -112.1, { lvl: 2, co: 'USA', f: ['Gorge up to 1.8 km deep carved by the Colorado river.'] }),
  P('valley', 'Death Valley', 36.5, -117.0, { lvl: 3, co: 'USA', f: ['The lowest and hottest place in North America.'] }),
  P('region', 'Great Barrier Reef', -18.3, 147.7, { lvl: 1, co: 'AUS', sub: 'Coral reef', f: ['The world’s largest coral reef system, off Queensland; threatened by bleaching.'] }),
  P('region', 'Amazon Rainforest', -4, -63, { lvl: 1, co: 'BRA', f: ['The largest tropical rainforest, with about a tenth of the world’s species.'] }),
  P('region', 'Sahel', 14, 5, { lvl: 2, f: ['Semi-arid belt south of the Sahara, facing desertification; the Great Green Wall is planted across it.'] }),
  P('region', 'Horn of Africa', 8, 47, { lvl: 2, co: ['SOM', 'ETH', 'ERI', 'DJI'], f: ['Peninsula of north-east Africa guarding the Bab-el-Mandeb.'] }),
  P('region', 'Golden Triangle', 20.35, 100.08, { lvl: 2, co: ['MMR', 'LAO', 'THA'], f: ['Where Myanmar, Laos and Thailand meet on the Mekong; notorious for opium.'] }),
  P('region', 'Golden Crescent', 32, 65, { lvl: 2, co: ['AFG', 'IRN', 'PAK'], f: ['Opium-producing region of Afghanistan, Iran and Pakistan.'] }),
  P('region', 'Congo Basin', -1, 22, { lvl: 3, co: 'COD', f: ['The second-largest tropical rainforest.'] }),

  // ── Islands and capes ───────────────────────────────────────────────────
  P('island', 'Greenland', 72, -40, { lvl: 1, co: 'GRL', f: ['The world’s largest island, mostly under an ice sheet.'] }),
  P('island', 'New Guinea', -5.5, 141, { lvl: 2, co: ['IDN', 'PNG'], f: ['The world’s second-largest island, shared by Indonesia and Papua New Guinea.'] }),
  P('island', 'Borneo', 0.5, 114, { lvl: 1, co: ['IDN', 'MYS', 'BRN'], f: ['The only island shared by three countries.'] }),
  P('island', 'Madagascar', -19, 46.7, { lvl: 1, co: 'MDG', f: ['The fourth-largest island; lemurs and baobabs found nowhere else.'] }),
  P('island', 'Sumatra', 0, 102, { lvl: 3, co: 'IDN', f: ['The 2004 Indian Ocean earthquake struck off its north-west coast.'] }),
  P('island', 'Honshu', 36, 138.5, { lvl: 3, co: 'JPN', f: ['Japan’s largest island, with Tokyo and Mount Fuji.'] }),
  P('island', 'Great Britain', 53, -1.5, { lvl: 3, co: 'GBR', f: ['The largest island of Europe.'] }),
  P('island', 'Sri Lanka', 7.8, 80.7, { lvl: 1, co: 'LKA', f: ['Separated from India by the Palk Strait and the Gulf of Mannar.'] }),
  P('island', 'Iceland', 64.9, -18.6, { lvl: 2, co: 'ISL', f: ['Sits on the Mid-Atlantic Ridge over a hotspot; geysers and geothermal power.'] }),
  P('island', 'Hawaii', 19.9, -155.6, { lvl: 2, co: 'USA', f: ['Volcanic islands formed over a mid-Pacific hotspot.'] }),
  P('island', 'Galápagos Islands', -0.8, -91, { id: 'galapagos', lvl: 2, co: 'ECU', f: ['Their wildlife inspired Darwin’s theory of evolution.'] }),
  P('island', 'Maldives', 3.2, 73.2, { lvl: 1, co: 'MDV', f: ['The world’s lowest-lying country, of coral atolls, threatened by sea-level rise.'] }),
  P('island', 'Mauritius', -20.3, 57.6, { lvl: 2, co: 'MUS', f: ['Volcanic island with a large population of Indian origin.'] }),
  P('island', 'Diego Garcia', -7.32, 72.42, { lvl: 2, co: 'MUS', f: ['Atoll of the Chagos archipelago hosting a US–UK base; the UK agreed in 2024–25 to return sovereignty of the Chagos to Mauritius.'] }),
  P('island', 'Socotra', 12.5, 53.9, { lvl: 3, co: 'YEM', f: ['Island of Yemen with the dragon’s blood tree.'] }),
  P('island', 'Svalbard', 78, 16, { lvl: 3, co: 'NOR', f: ['Arctic archipelago with the Global Seed Vault and India’s Himadri research station.'] }),
  P('island', 'Tasmania', -42, 146.6, { lvl: 3, co: 'AUS', f: ['Island state south of mainland Australia.'] }),
  P('cape', 'Cape of Good Hope', -34.357, 18.474, { lvl: 1, co: 'ZAF', f: ['Rounded by Vasco da Gama in 1497 on the way to India.'] }),
  P('cape', 'Cape Agulhas', -34.83, 20.0, { lvl: 2, co: 'ZAF', f: ['The southernmost point of Africa, where the Atlantic and Indian Oceans officially meet.'] }),
  P('cape', 'Cape Horn', -55.98, -67.27, { lvl: 1, co: 'CHL', f: ['Southern tip of South America, notorious for storms.'] }),
  P('cape', 'Cape Verde', 14.72, -17.53, { lvl: 3, co: 'SEN', f: ['The westernmost point of mainland Africa, at Dakar.'] }),
  P('cape', 'Cabo da Roca', 38.78, -9.5, { lvl: 3, co: 'PRT', f: ['The westernmost point of mainland Europe.'] }),
  P('cape', 'Cape York', -10.69, 142.53, { lvl: 3, co: 'AUS', f: ['The northernmost point of mainland Australia.'] }),

  // ── Waterfalls ──────────────────────────────────────────────────────────
  P('waterfall', 'Angel Falls', 5.968, -62.536, { lvl: 1, co: 'VEN', f: ['The world’s highest uninterrupted waterfall (979 m), off a tepui.'] }),
  P('waterfall', 'Victoria Falls', -17.925, 25.857, { lvl: 1, co: ['ZMB', 'ZWE'], aka: ['Mosi-oa-Tunya'], rel: { onRiver: ['river.zambezi'] }, f: ['The largest curtain of falling water, on the Zambezi.'] }),
  P('waterfall', 'Niagara Falls', 43.08, -79.07, { lvl: 1, co: ['USA', 'CAN'], f: ['Between Lakes Erie and Ontario on the US–Canada border.'] }),
  P('waterfall', 'Iguazu Falls', -25.695, -54.437, { lvl: 2, co: ['ARG', 'BRA'], f: ['A system of about 275 falls on the Argentina–Brazil border.'] }),

  // ── Capitals, cities and ports ──────────────────────────────────────────
  P('capital', 'Washington, D.C.', 38.9072, -77.0369, { id: 'washington', lvl: 1, co: 'USA', tags: ['national'], f: ['Capital of the United States on the Potomac.'] }),
  P('capital', 'Ottawa', 45.4215, -75.6972, { lvl: 2, co: 'CAN', tags: ['national'], f: ['Capital of Canada.'] }),
  P('capital', 'Mexico City', 19.4326, -99.1332, { lvl: 2, co: 'MEX', tags: ['national'], f: ['Built on a drained lake bed at about 2,240 m.'] }),
  P('capital', 'Brasília', -15.7939, -47.8828, { id: 'brasilia', lvl: 1, co: 'BRA', tags: ['national'], f: ['Planned capital of Brazil since 1960.'] }),
  P('capital', 'Buenos Aires', -34.6037, -58.3816, { lvl: 2, co: 'ARG', tags: ['national'], f: ['Capital of Argentina on the Río de la Plata.'] }),
  P('capital', 'Lima', -12.0464, -77.0428, { lvl: 3, co: 'PER', tags: ['national'], f: ['Coastal desert capital of Peru.'] }),
  P('capital', 'Bogotá', 4.711, -74.0721, { id: 'bogota', lvl: 3, co: 'COL', tags: ['national'], f: ['High Andean capital of Colombia.'] }),
  P('capital', 'Santiago', -33.4489, -70.6693, { lvl: 3, co: 'CHL', tags: ['national'], f: ['Capital of Chile in the central valley.'] }),
  P('capital', 'London', 51.5074, -0.1278, { lvl: 1, co: 'GBR', tags: ['national'], f: ['On the Thames; Greenwich marks the Prime Meridian.'] }),
  P('capital', 'Paris', 48.8566, 2.3522, { lvl: 1, co: 'FRA', tags: ['national'], f: ['On the Seine; the Paris climate agreement (2015).'] }),
  P('capital', 'Berlin', 52.52, 13.405, { lvl: 2, co: 'DEU', tags: ['national'], f: ['Capital of Germany on the Spree.'] }),
  P('capital', 'Moscow', 55.7558, 37.6173, { lvl: 1, co: 'RUS', tags: ['national'], f: ['Capital of Russia on the Moskva.'] }),
  P('capital', 'Rome', 41.9028, 12.4964, { lvl: 2, co: 'ITA', tags: ['national'], f: ['On the Tiber; encloses Vatican City.'] }),
  P('capital', 'Madrid', 40.4168, -3.7038, { lvl: 3, co: 'ESP', tags: ['national'], f: ['On the Meseta plateau at the centre of Spain.'] }),
  P('capital', 'Kyiv', 50.4501, 30.5234, { lvl: 3, co: 'UKR', tags: ['national'], f: ['On the Dnipro.'] }),
  P('capital', 'Ankara', 39.9334, 32.8597, { lvl: 3, co: 'TUR', tags: ['national'], f: ['Capital of Türkiye on the Anatolian plateau.'] }),
  P('capital', 'Cairo', 30.0444, 31.2357, { lvl: 1, co: 'EGY', tags: ['national'], f: ['At the head of the Nile delta; the Giza pyramids are nearby.'] }),
  P('capital', 'Addis Ababa', 9.03, 38.74, { lvl: 2, co: 'ETH', tags: ['national'], f: ['Headquarters of the African Union.'] }),
  P('capital', 'Nairobi', -1.2921, 36.8219, { lvl: 2, co: 'KEN', tags: ['national'], f: ['Headquarters of UNEP.'] }),
  P('capital', 'Abuja', 9.0765, 7.3986, { lvl: 3, co: 'NGA', tags: ['national'], f: ['Planned capital of Nigeria since 1991.'] }),
  P('capital', 'Pretoria', -25.7479, 28.2293, { lvl: 3, co: 'ZAF', tags: ['national'], f: ['Executive capital of South Africa (Cape Town legislative, Bloemfontein judicial).'] }),
  P('capital', 'Kinshasa', -4.4419, 15.2663, { lvl: 3, co: 'COD', tags: ['national'], f: ['On the Congo, facing Brazzaville across the river.'] }),
  P('capital', 'Riyadh', 24.7136, 46.6753, { lvl: 2, co: 'SAU', tags: ['national'], f: ['Capital of Saudi Arabia in the Najd.'] }),
  P('capital', 'Tehran', 35.6892, 51.389, { lvl: 2, co: 'IRN', tags: ['national'], f: ['At the foot of the Alborz mountains.'] }),
  P('capital', 'Baghdad', 33.3152, 44.3661, { lvl: 3, co: 'IRQ', tags: ['national'], f: ['On the Tigris.'] }),
  P('capital', 'Astana', 51.1694, 71.4491, { lvl: 3, co: 'KAZ', tags: ['national'], f: ['Steppe capital of Kazakhstan since 1997.'] }),
  P('capital', 'Beijing', 39.9042, 116.4074, { lvl: 1, co: 'CHN', tags: ['national'], f: ['Capital of China at the northern edge of the North China Plain.'] }),
  P('capital', 'Tokyo', 35.6762, 139.6503, { lvl: 1, co: 'JPN', tags: ['national'], f: ['On Honshu; the world’s largest metropolitan area.'] }),
  P('capital', 'Seoul', 37.5665, 126.978, { lvl: 2, co: 'KOR', tags: ['national'], f: ['On the Han river.'] }),
  P('capital', 'Bangkok', 13.7563, 100.5018, { lvl: 2, co: 'THA', tags: ['national'], f: ['On the Chao Phraya delta.'] }),
  P('capital', 'Hanoi', 21.0278, 105.8342, { lvl: 3, co: 'VNM', tags: ['national'], f: ['On the Red River delta.'] }),
  P('capital', 'Jakarta', -6.2088, 106.8456, { lvl: 2, co: 'IDN', tags: ['national'], f: ['Sinking coastal capital on Java; Nusantara on Borneo is being built as its successor.'] }),
  P('capital', 'Kuala Lumpur', 3.139, 101.6869, { lvl: 3, co: 'MYS', tags: ['national'], f: ['Capital of Malaysia; Putrajaya is the administrative centre.'] }),
  P('capital', 'Singapore', 1.3521, 103.8198, { lvl: 1, co: 'SGP', tags: ['national'], f: ['City-state at the southern end of the Strait of Malacca; one of the busiest ports.'] }),
  P('capital', 'Manila', 14.5995, 120.9842, { lvl: 3, co: 'PHL', tags: ['national'], f: ['On Manila Bay, Luzon.'] }),
  P('capital', 'Canberra', -35.2809, 149.13, { lvl: 1, co: 'AUS', tags: ['national'], f: ['Planned capital of Australia, chosen as a compromise between Sydney and Melbourne.'] }),
  P('capital', 'Wellington', -41.2865, 174.7762, { lvl: 3, co: 'NZL', tags: ['national'], f: ['On Cook Strait; the world’s southernmost national capital.'] }),
  P('capital', 'New Delhi', 28.6139, 77.209, { id: 'new-delhi', lvl: 1, co: 'IND', tags: ['national'], f: ['Capital of India.'] }),
  P('city', 'New York', 40.7128, -74.006, { lvl: 1, co: 'USA', f: ['Headquarters of the United Nations.'] }),
  P('city', 'Geneva', 46.2044, 6.1432, { lvl: 3, co: 'CHE', f: ['Hosts the WHO, WTO, ILO and the UN Human Rights Council.'] }),
  P('port', 'Chabahar', 25.29, 60.64, { lvl: 1, co: 'IRN', f: ['Iranian port developed with India (Shahid Beheshti terminal), giving access to Afghanistan and Central Asia.'] }),
  P('port', 'Bandar Abbas', 27.18, 56.27, { lvl: 3, co: 'IRN', f: ['Iranian port on the Strait of Hormuz; a node of the International North–South Transport Corridor.'] }),
  P('port', 'Duqm', 19.67, 57.7, { lvl: 3, co: 'OMN', f: ['Omani port where the Indian Navy has access.'] }),
  P('port', 'Sabang', 5.89, 95.32, { lvl: 3, co: 'IDN', f: ['Indonesian port at the northern mouth of the Malacca Strait; India is helping develop it.'] }),
  P('port', 'Rotterdam', 51.95, 4.14, { lvl: 2, co: 'NLD', f: ['Europe’s largest port, at the mouth of the Rhine.'] }),
  P('port', 'Shanghai', 31.23, 121.47, { lvl: 2, co: 'CHN', f: ['The world’s busiest container port, at the mouth of the Yangtze.'] }),
]
